SELECT
	MEPN.PTOMEDICODI,
	MEPN.PTOMEDIDESC,
	SI.TIPOINFODESC,
	to_char(ME1.MEDIFECHA, 'DD/MM/YYYY') MEDIFECHA_DDMMYYYY,
	ME1.H1,
	ME1.LASTUSER,
	ME1.LASTDATE
FROM
	ME_MEDICION1 ME1
INNER JOIN ME_PTOMEDICION MEPN ON
	MEPN.PTOMEDICODI = ME1.PTOMEDICODI
INNER JOIN SI_TIPOINFORMACION SI ON
	SI.TIPOINFOCODI = ME1.TIPOINFOCODI
WHERE
	MEDIFECHA >= to_date('{0}', 'yyyy-mm-dd hh24:mi:ss')
	AND MEDIFECHA <= to_date('{1}', 'yyyy-mm-dd hh24:mi:ss')
	AND (
		MEPN.PTOMEDIDESC LIKE '%CAHUA%'
		OR 
		MEPN.PTOMEDIDESC LIKE '%EDEGEL%'
		OR 
		MEPN.PTOMEDIDESC LIKE '%EGEMSA%'
		OR 
		MEPN.PTOMEDIDESC LIKE '%EGENOR%'
		OR 
		MEPN.PTOMEDIDESC LIKE '%EGESUR%'
		OR
		MEPN.PTOMEDIDESC LIKE '%ELECTROANDES%'
		OR
		MEPN.PTOMEDIDESC LIKE '%ELECTROPERU%'
		OR
		MEPN.PTOMEDIDESC LIKE '%SAN GABAN%'
		OR
		MEPN.PTOMEDIDESC LIKE '%EGASA%' 
	)
ORDER BY
	MEPN.PTOMEDIDESC ASC,
	ME1.MEDIFECHA ASC