// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;

namespace Intranet
{
    [TestFixture]
    public class FDTI43OperacionesVarias
    {
        private IWebDriver driver;
        public IDictionary<string, object> vars { get; private set; }


        [Test, Order(1)]
        public void Intranet_FDTI43_OperacionesVarias_Ingresar_a_la_opcion()
        {
            driver = Test_Suite.SetUpClass();
            Actions actions = new Actions(driver);
            FuncionesRecurrentes.EliminarYCrearCarpeta();
            FuncionesRecurrentes.loginIntranet(driver);
            FuncionesRecurrentes.WaitForElementToBeVisible(By.LinkText("Eventos"), driver, true);
            driver.FindElement(By.XPath("/html[1]/body[1]/div[4]/div[1]/div[1]/table[1]/tbody[1]/tr[1]/td[1]/div[1]/div[3]/ul[1]/li[2]/ul[1]/li[3]/a[1]")).Click();
        }

        [Test, Order(2)]
        public void Intranet_FDTI43_OperacionesVarias_Consulta_registros()
        {
            try
            {
                FuncionesRecurrentes.NavegarAFecha("MesAnteriorDia1", driver, By.XPath("//input[@name='FechaInicio']"));
                driver.FindElement(By.XPath("//input[@value='Buscar']")).Click();
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex.Message);
            }

        }

        [Test, Order(3)]
        public void Intranet_FDTI43_OperacionesVarias_Edicion_datos()
        {
            try
            {
                FuncionesRecurrentes.WaitFor(2);
                FuncionesRecurrentes.WaitForElementToBeVisible(By.XPath("/html[1]/body[1]/div[4]/div[1]/div[1]/table[1]/tbody[1]/tr[1]/td[2]/div[2]/div[2]/div[2]/div[2]/div[2]/table[1]/tbody[1]/tr[1]/td[1]/a[2]/img[1]"), driver, true);
                FuncionesRecurrentes.WaitFor(5);
                driver.FindElement(By.XPath("/html[1]/body[1]/div[4]/div[1]/div[1]/table[1]/tbody[1]/tr[1]/td[2]/div[2]/div[2]/form[1]/table[3]/tbody[1]/tr[1]/td[1]/table[1]/tbody[1]/tr[1]/td[2]/textarea[1]")).SendKeys("TEST");
                driver.FindElement(By.XPath("//input[@id='btnGrabar']")).Click();
                //FuncionesRecurrentes.WaitForElementToBeVisible(By.XPath("//div[@class='action-exito'][contains(.,'Los datos se grabaron correctamente. Se modificaron 1 datos.')]"), driver);
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex.Message);
            }

        }

        [Test, Order(4)]
        public void Intranet_FDTI43_OperacionesVarias_Eliminar_registro()
        {
            try
            {
                FuncionesRecurrentes.WaitFor(5);
                driver.FindElement(By.XPath("/html[1]/body[1]/div[4]/div[1]/div[1]/table[1]/tbody[1]/tr[1]/td[2]/div[2]/div[2]/div[2]/div[2]/div[2]/table[1]/tbody[1]/tr[1]/td[1]/a[3]/img[1]")).Click();
                FuncionesRecurrentes.WaitFor(2);
                //Saca error
                IAlert alert = driver.SwitchTo().Alert();
                alert.Accept();
                FuncionesRecurrentes.WaitFor(2);
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex.Message);
            }

        }

        [Test, Order(5)]
        public void Intranet_FDTI43_OperacionesVarias_Nuevo_registro()
        {
            try
            {
                FuncionesRecurrentes.WaitForElementToBeVisible(By.XPath("//input[@value='Nuevo']"), driver, true);
                FuncionesRecurrentes.WaitFor(5);
                FuncionesRecurrentes.WaitForElementToBeVisible(By.XPath("//input[@id='btnSeleccionar']"), driver, true);
                FuncionesRecurrentes.WaitFor(2);
                FuncionesRecurrentes.SelectOptionfromDropdown(By.XPath("/html[1]/body[1]/div[16]/div[3]/table[1]/tbody[1]/tr[1]/td[2]/select[1]"), driver, "ACEROS AREQUIPA");
                FuncionesRecurrentes.WaitForElementToBeVisible(By.XPath("/html[1]/body[1]/div[16]/table[1]/tbody[1]/tr[1]/td[3]/div[2]/table[1]/tbody[1]/tr[2]/td[1]"), driver, true);
                FuncionesRecurrentes.Otrasfechas("Manana", driver, By.XPath("//input[@id='valhorfin']"));
                FuncionesRecurrentes.WaitFor(2);
                driver.FindElement(By.XPath("//input[@id='btnGrabar']")).Click();
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex.Message);
            }
        }

        [Test, Order(6)]
        public void Intranet_FDTI43_OperacionesVarias_exportar_datos()
        {
            try
            {
                driver.FindElement(By.XPath("//input[@id='btnExportar']")).Click();
                FuncionesRecurrentes.VerificarArchivoDescargado();
                FuncionesRecurrentes.WaitFor(5);
            }
            catch (Exception ex)
            {
                //Assert.Fail(ex.Message);// es debido a que no realizó los pasos anteriores
                // quizá debido a la ejecución anterior y no se puede eliminar el registro
                Console.WriteLine(ex.Message);
            }
            finally
            {
                driver.Quit();
            }
        }

        private string CloseAlertAndGetItsText()
        {
            bool acceptNextAlert = true;
            try
            {
                IAlert alert = driver.SwitchTo().Alert();
                string alertText = alert.Text;
                if (acceptNextAlert)
                {
                    alert.Accept();
                }
                else
                {
                    alert.Dismiss();
                }
                return alertText;
            }
            finally
            {
                acceptNextAlert = true;
            }
        }
    }
}