// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;

namespace Intranet
{
    //[TestFixture]
    //[Ignore("21.06.24: CNalvarte indica que esta prueba no aplica")]
    public class Intranet_FDTI44_EnvioCorreos
    {
        //21.06: Carlos indica que esta prueba no aplica

        private IWebDriver driver;
        public IDictionary<string, object> vars { get; private set; }

        //[Test, Order(1)]
        public void Intranet_FDTI44_EnvioCorreos_Ingresar_a_la_opcion()
        {
            //driver = Test_Suite.SetUpClass();
            //Actions actions = new Actions(driver);
            //FuncionesRecurrentes.EliminarYCrearCarpeta();
            //FuncionesRecurrentes.loginIntranet(driver);
            //FuncionesRecurrentes.WaitForElementToBeVisible(By.LinkText("Eventos"), driver, true);
            //driver.FindElement(By.XPath("/html[1]/body[1]/div[4]/div[1]/div[1]/table[1]/tbody[1]/tr[1]/td[1]/div[1]/div[3]/ul[1]/li[2]/ul[1]/li[4]/a[1]")).Click();
        }

        //[Test, Order(2)]
        public void Intranet_FDTI44_EnvioCorreos_Nuevo_registro()
        {
            //try
            //{
            //    FuncionesRecurrentes.WaitForElementToBeVisible(By.XPath("//input[@value='Nuevo']"), driver, true);
            //    FuncionesRecurrentes.WaitFor(2);
            //    driver.FindElement(By.XPath("/html[1]/body[1]/div[4]/div[1]/div[1]/table[1]/tbody[1]/tr[1]/td[2]/div[2]/div[2]/form[1]/div[2]/table[1]/tbody[1]/tr[4]/td[2]/textarea[1]")).SendKeys("PRUEBA");
            //    {
            //        var dropdown = driver.FindElement(By.XPath("/html[1]/body[1]/div[4]/div[1]/div[1]/table[1]/tbody[1]/tr[1]/td[2]/div[2]/div[2]/form[1]/div[2]/table[1]/tbody[1]/tr[8]/td[2]/select[1]"));
            //        driver.FindElement(By.XPath("/html[1]/body[1]/div[4]/div[1]/div[1]/table[1]/tbody[1]/tr[1]/td[2]/div[2]/div[2]/form[1]/div[2]/table[1]/tbody[1]/tr[8]/td[2]/select[1]")).Click();
            //        dropdown.FindElement(By.CssSelector("*:nth-child(2)")).Click();
            //    }
            //    FuncionesRecurrentes.WaitFor(2);
            //    driver.FindElement(By.XPath("//input[@value='Grabar']")).Click();
            //    FuncionesRecurrentes.WaitForElementToBeVisible(By.XPath("//div[@class='popup-title'][contains(.,'Formato de correo')]"), driver);
            //    driver.FindElement(By.XPath("/html[1]/body[1]/div[10]/div[3]/form[1]/span[1]/span[1]")).Click();
            //    FuncionesRecurrentes.WaitForElementToBeVisible(By.XPath("//div[@class='action-exito'][contains(.,'La operación se realizó con éxito.')]"), driver);
            //    driver.FindElement(By.XPath("//input[@id='btnCancelar']")).Click();
            //}
            //catch (Exception ex)
            //{
            //    Console.WriteLine(ex.Message);
            //}
        }

        //[Test, Order(3)]
        public void Intranet_FDTI44_EnvioCorreos_Edicion_registro()
        {
            //try
            //{
            //    FuncionesRecurrentes.WaitForElementToBeVisible(By.XPath("/html[1]/body[1]/div[4]/div[1]/div[1]/table[1]/tbody[1]/tr[1]/td[2]/div[2]/div[2]/div[2]/div[2]/div[2]/table[1]/tbody[1]/tr[1]/td[1]/a[2]/img[1]"), driver, true);
            //    FuncionesRecurrentes.Otrasfechas("Ayer", driver, By.XPath("/html[1]/body[1]/div[4]/div[1]/div[1]/table[1]/tbody[1]/tr[1]/td[2]/div[2]/div[2]/form[1]/div[2]/table[1]/tbody[1]/tr[1]/td[2]/span[1]/input[1]"));
            //    driver.FindElement(By.XPath("//input[@value='Grabar']")).Click();
            //    FuncionesRecurrentes.WaitForElementToBeVisible(By.XPath("//div[@class='popup-title'][contains(.,'Formato de correo')]"), driver);
            //    driver.FindElement(By.XPath("/html[1]/body[1]/div[10]/div[3]/form[1]/span[1]/span[1]")).Click();
            //    FuncionesRecurrentes.WaitForElementToBeVisible(By.XPath("//div[@class='action-exito'][contains(.,'La operación se realizó con éxito.')]"), driver);
            //    driver.FindElement(By.XPath("//input[@id='btnCancelar']")).Click();
            //}
            //catch (Exception ex)
            //{
            //    Console.WriteLine(ex.Message);
            //}
        }

        //[Test, Order(4)]
        public void Intranet_FDTI44_EnvioCorreos_Exportar_datos()
        {
            //try
            //{
            //    FuncionesRecurrentes.WaitForElementToBeVisible(By.XPath("/html[1]/body[1]/div[4]/div[1]/div[1]/table[1]/tbody[1]/tr[1]/td[2]/div[2]/div[2]/div[2]/div[2]/div[2]/table[1]/tbody[1]/tr[1]/td[1]/a[3]/img[1]"), driver, true);
            //    IAlert alert = driver.SwitchTo().Alert();
            //    alert.Accept();
            //}
            //catch (Exception ex)
            //{
            //    Console.WriteLine(ex.Message);
            //}
        }

        //[Test, Order(5)]
        public void Intranet_FDTI44_Eliminar_registro()
        {
            //try
            //{
            //    driver.FindElement(By.XPath("/html[1]/body[1]/div[4]/div[1]/div[1]/table[1]/tbody[1]/tr[1]/td[2]/div[2]/div[1]/div[1]/div[2]/input[2]")).Click();
            //    FuncionesRecurrentes.VerificarArchivoDescargado();
            //    FuncionesRecurrentes.WaitFor();
            //}
            //catch (Exception ex)
            //{
            //    //Assert.Fail(ex.Message);// es debido a que no realizó los pasos anteriores
            //    // quizá debido a la ejecución anterior y no se puede eliminar el registro
            //    Console.WriteLine(ex.Message);
            //}
            //finally {
            //    driver.Quit();
            //}
        }

        //private string CloseAlertAndGetItsText()
        //{
            //bool acceptNextAlert = true;
            //try
            //{
            //    IAlert alert = driver.SwitchTo().Alert();
            //    string alertText = alert.Text;
            //    if (acceptNextAlert)
            //    {
            //        alert.Accept();
            //    }
            //    else
            //    {
            //        alert.Dismiss();
            //    }
            //    return alertText;
            //}
            //finally
            //{
            //    acceptNextAlert = true;
            //}
        //}
    }
}