//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Configuration;
using System.Diagnostics;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.Xml.Serialization;
using COES.MVC.Intranet.Helper;

// 
// This source code was auto-generated by wsdl, Version=4.0.30319.33440.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Web.Services.WebServiceBindingAttribute(Name="IndiceSupervisionSoap", Namespace="http://tempuri.org/")]
public partial class IndiceSupervision : System.Web.Services.Protocols.SoapHttpClientProtocol {
    
    private System.Threading.SendOrPostCallback ObtenerCuadrosOperationCompleted;
    
    /// <remarks/>
    public IndiceSupervision() {
        //this.Url = "http://www.coes.org.pe/wsIndSupervision/IndiceSupervision.asmx";
        this.Url = ConfigurationManager.AppSettings[Constantes.wsIndSupervision];
    }
    
    /// <remarks/>
    public event ObtenerCuadrosCompletedEventHandler ObtenerCuadrosCompleted;
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ObtenerCuadros", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public ResultadoIndSup ObtenerCuadros(System.DateTime fecha) {
        object[] results = this.Invoke("ObtenerCuadros", new object[] {
                    fecha});
        return ((ResultadoIndSup)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginObtenerCuadros(System.DateTime fecha, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("ObtenerCuadros", new object[] {
                    fecha}, callback, asyncState);
    }
    
    /// <remarks/>
    public ResultadoIndSup EndObtenerCuadros(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((ResultadoIndSup)(results[0]));
    }
    
    /// <remarks/>
    public void ObtenerCuadrosAsync(System.DateTime fecha) {
        this.ObtenerCuadrosAsync(fecha, null);
    }
    
    /// <remarks/>
    public void ObtenerCuadrosAsync(System.DateTime fecha, object userState) {
        if ((this.ObtenerCuadrosOperationCompleted == null)) {
            this.ObtenerCuadrosOperationCompleted = new System.Threading.SendOrPostCallback(this.OnObtenerCuadrosOperationCompleted);
        }
        this.InvokeAsync("ObtenerCuadros", new object[] {
                    fecha}, this.ObtenerCuadrosOperationCompleted, userState);
    }
    
    private void OnObtenerCuadrosOperationCompleted(object arg) {
        if ((this.ObtenerCuadrosCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.ObtenerCuadrosCompleted(this, new ObtenerCuadrosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    public new void CancelAsync(object userState) {
        base.CancelAsync(userState);
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
public partial class ResultadoIndSup {
    
    private double[][] cuadro1Field;
    
    private double[][] cuadro2Field;
    
    private double[][] cuadro3Field;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("ArrayOfDouble")]
    [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false, NestingLevel=1)]
    public double[][] Cuadro1 {
        get {
            return this.cuadro1Field;
        }
        set {
            this.cuadro1Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("ArrayOfDouble")]
    [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false, NestingLevel=1)]
    public double[][] Cuadro2 {
        get {
            return this.cuadro2Field;
        }
        set {
            this.cuadro2Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("ArrayOfDouble")]
    [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false, NestingLevel=1)]
    public double[][] Cuadro3 {
        get {
            return this.cuadro3Field;
        }
        set {
            this.cuadro3Field = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
public delegate void ObtenerCuadrosCompletedEventHandler(object sender, ObtenerCuadrosCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class ObtenerCuadrosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal ObtenerCuadrosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public ResultadoIndSup Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((ResultadoIndSup)(this.results[0]));
        }
    }
}
