//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.Xml.Serialization;

// 
// This source code was auto-generated by wsdl, Version=4.0.30319.1.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Web.Services.WebServiceBindingAttribute(Name="CFile_mngSoap", Namespace="http://www.coes.org.pe/")]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(CBase))]
public partial class CFile_mng : System.Web.Services.Protocols.SoapHttpClientProtocol {
    
    private System.Threading.SendOrPostCallback nf_UploadFileOperationCompleted;
    
    private System.Threading.SendOrPostCallback nf_MoveFileOperationCompleted;
    
    private System.Threading.SendOrPostCallback nf_ws_getInfoDirOperationCompleted;
    
    private System.Threading.SendOrPostCallback nf_GetPathfromDirVirtualOperationCompleted;
    
    private System.Threading.SendOrPostCallback nf_ws_getDirectoriosOperationCompleted;
    
    private System.Threading.SendOrPostCallback nf_ws_getFilesOperationCompleted;
    
    /// <remarks/>
    public CFile_mng() {
        this.Url = "http://sicoes.coes.org.pe:8090/wsstd/ws_std.asmx";
    }
    
    /// <remarks/>
    public event nf_UploadFileCompletedEventHandler nf_UploadFileCompleted;
    
    /// <remarks/>
    public event nf_MoveFileCompletedEventHandler nf_MoveFileCompleted;
    
    /// <remarks/>
    public event nf_ws_getInfoDirCompletedEventHandler nf_ws_getInfoDirCompleted;
    
    /// <remarks/>
    public event nf_GetPathfromDirVirtualCompletedEventHandler nf_GetPathfromDirVirtualCompleted;
    
    /// <remarks/>
    public event nf_ws_getDirectoriosCompletedEventHandler nf_ws_getDirectoriosCompleted;
    
    /// <remarks/>
    public event nf_ws_getFilesCompletedEventHandler nf_ws_getFilesCompleted;
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.coes.org.pe/nf_UploadFile", RequestNamespace="http://www.coes.org.pe/", ResponseNamespace="http://www.coes.org.pe/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public bool nf_UploadFile([System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")] byte[] an_flujo, string as_dir_virtual, string as_dir_relativo, string as_filename, out string as_msg) {
        object[] results = this.Invoke("nf_UploadFile", new object[] {
                    an_flujo,
                    as_dir_virtual,
                    as_dir_relativo,
                    as_filename});
        as_msg = ((string)(results[1]));
        return ((bool)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult Beginnf_UploadFile(byte[] an_flujo, string as_dir_virtual, string as_dir_relativo, string as_filename, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("nf_UploadFile", new object[] {
                    an_flujo,
                    as_dir_virtual,
                    as_dir_relativo,
                    as_filename}, callback, asyncState);
    }
    
    /// <remarks/>
    public bool Endnf_UploadFile(System.IAsyncResult asyncResult, out string as_msg) {
        object[] results = this.EndInvoke(asyncResult);
        as_msg = ((string)(results[1]));
        return ((bool)(results[0]));
    }
    
    /// <remarks/>
    public void nf_UploadFileAsync(byte[] an_flujo, string as_dir_virtual, string as_dir_relativo, string as_filename) {
        this.nf_UploadFileAsync(an_flujo, as_dir_virtual, as_dir_relativo, as_filename, null);
    }
    
    /// <remarks/>
    public void nf_UploadFileAsync(byte[] an_flujo, string as_dir_virtual, string as_dir_relativo, string as_filename, object userState) {
        if ((this.nf_UploadFileOperationCompleted == null)) {
            this.nf_UploadFileOperationCompleted = new System.Threading.SendOrPostCallback(this.Onnf_UploadFileOperationCompleted);
        }
        this.InvokeAsync("nf_UploadFile", new object[] {
                    an_flujo,
                    as_dir_virtual,
                    as_dir_relativo,
                    as_filename}, this.nf_UploadFileOperationCompleted, userState);
    }
    
    private void Onnf_UploadFileOperationCompleted(object arg) {
        if ((this.nf_UploadFileCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.nf_UploadFileCompleted(this, new nf_UploadFileCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.coes.org.pe/nf_MoveFile", RequestNamespace="http://www.coes.org.pe/", ResponseNamespace="http://www.coes.org.pe/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public bool nf_MoveFile(string as_dir_virtual, string as_filename_rel_orig, string as_dir_rel_dest, string as_filename_dest, bool ab_borrar, out string as_msg) {
        object[] results = this.Invoke("nf_MoveFile", new object[] {
                    as_dir_virtual,
                    as_filename_rel_orig,
                    as_dir_rel_dest,
                    as_filename_dest,
                    ab_borrar});
        as_msg = ((string)(results[1]));
        return ((bool)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult Beginnf_MoveFile(string as_dir_virtual, string as_filename_rel_orig, string as_dir_rel_dest, string as_filename_dest, bool ab_borrar, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("nf_MoveFile", new object[] {
                    as_dir_virtual,
                    as_filename_rel_orig,
                    as_dir_rel_dest,
                    as_filename_dest,
                    ab_borrar}, callback, asyncState);
    }
    
    /// <remarks/>
    public bool Endnf_MoveFile(System.IAsyncResult asyncResult, out string as_msg) {
        object[] results = this.EndInvoke(asyncResult);
        as_msg = ((string)(results[1]));
        return ((bool)(results[0]));
    }
    
    /// <remarks/>
    public void nf_MoveFileAsync(string as_dir_virtual, string as_filename_rel_orig, string as_dir_rel_dest, string as_filename_dest, bool ab_borrar) {
        this.nf_MoveFileAsync(as_dir_virtual, as_filename_rel_orig, as_dir_rel_dest, as_filename_dest, ab_borrar, null);
    }
    
    /// <remarks/>
    public void nf_MoveFileAsync(string as_dir_virtual, string as_filename_rel_orig, string as_dir_rel_dest, string as_filename_dest, bool ab_borrar, object userState) {
        if ((this.nf_MoveFileOperationCompleted == null)) {
            this.nf_MoveFileOperationCompleted = new System.Threading.SendOrPostCallback(this.Onnf_MoveFileOperationCompleted);
        }
        this.InvokeAsync("nf_MoveFile", new object[] {
                    as_dir_virtual,
                    as_filename_rel_orig,
                    as_dir_rel_dest,
                    as_filename_dest,
                    ab_borrar}, this.nf_MoveFileOperationCompleted, userState);
    }
    
    private void Onnf_MoveFileOperationCompleted(object arg) {
        if ((this.nf_MoveFileCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.nf_MoveFileCompleted(this, new nf_MoveFileCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.coes.org.pe/nf_ws_getInfoDir", RequestNamespace="http://www.coes.org.pe/", ResponseNamespace="http://www.coes.org.pe/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public object nf_ws_getInfoDir(string as_dir_virtual) {
        object[] results = this.Invoke("nf_ws_getInfoDir", new object[] {
                    as_dir_virtual});
        return ((object)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult Beginnf_ws_getInfoDir(string as_dir_virtual, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("nf_ws_getInfoDir", new object[] {
                    as_dir_virtual}, callback, asyncState);
    }
    
    /// <remarks/>
    public object Endnf_ws_getInfoDir(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((object)(results[0]));
    }
    
    /// <remarks/>
    public void nf_ws_getInfoDirAsync(string as_dir_virtual) {
        this.nf_ws_getInfoDirAsync(as_dir_virtual, null);
    }
    
    /// <remarks/>
    public void nf_ws_getInfoDirAsync(string as_dir_virtual, object userState) {
        if ((this.nf_ws_getInfoDirOperationCompleted == null)) {
            this.nf_ws_getInfoDirOperationCompleted = new System.Threading.SendOrPostCallback(this.Onnf_ws_getInfoDirOperationCompleted);
        }
        this.InvokeAsync("nf_ws_getInfoDir", new object[] {
                    as_dir_virtual}, this.nf_ws_getInfoDirOperationCompleted, userState);
    }
    
    private void Onnf_ws_getInfoDirOperationCompleted(object arg) {
        if ((this.nf_ws_getInfoDirCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.nf_ws_getInfoDirCompleted(this, new nf_ws_getInfoDirCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.coes.org.pe/nf_GetPathfromDirVirtual", RequestNamespace="http://www.coes.org.pe/", ResponseNamespace="http://www.coes.org.pe/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public string nf_GetPathfromDirVirtual(string as_dir_virtual) {
        object[] results = this.Invoke("nf_GetPathfromDirVirtual", new object[] {
                    as_dir_virtual});
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult Beginnf_GetPathfromDirVirtual(string as_dir_virtual, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("nf_GetPathfromDirVirtual", new object[] {
                    as_dir_virtual}, callback, asyncState);
    }
    
    /// <remarks/>
    public string Endnf_GetPathfromDirVirtual(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public void nf_GetPathfromDirVirtualAsync(string as_dir_virtual) {
        this.nf_GetPathfromDirVirtualAsync(as_dir_virtual, null);
    }
    
    /// <remarks/>
    public void nf_GetPathfromDirVirtualAsync(string as_dir_virtual, object userState) {
        if ((this.nf_GetPathfromDirVirtualOperationCompleted == null)) {
            this.nf_GetPathfromDirVirtualOperationCompleted = new System.Threading.SendOrPostCallback(this.Onnf_GetPathfromDirVirtualOperationCompleted);
        }
        this.InvokeAsync("nf_GetPathfromDirVirtual", new object[] {
                    as_dir_virtual}, this.nf_GetPathfromDirVirtualOperationCompleted, userState);
    }
    
    private void Onnf_GetPathfromDirVirtualOperationCompleted(object arg) {
        if ((this.nf_GetPathfromDirVirtualCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.nf_GetPathfromDirVirtualCompleted(this, new nf_GetPathfromDirVirtualCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.coes.org.pe/nf_ws_getDirectorios", RequestNamespace="http://www.coes.org.pe/", ResponseNamespace="http://www.coes.org.pe/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public n_InfoDirectory[] nf_ws_getDirectorios(string as_path_dir) {
        object[] results = this.Invoke("nf_ws_getDirectorios", new object[] {
                    as_path_dir});
        return ((n_InfoDirectory[])(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult Beginnf_ws_getDirectorios(string as_path_dir, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("nf_ws_getDirectorios", new object[] {
                    as_path_dir}, callback, asyncState);
    }
    
    /// <remarks/>
    public n_InfoDirectory[] Endnf_ws_getDirectorios(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((n_InfoDirectory[])(results[0]));
    }
    
    /// <remarks/>
    public void nf_ws_getDirectoriosAsync(string as_path_dir) {
        this.nf_ws_getDirectoriosAsync(as_path_dir, null);
    }
    
    /// <remarks/>
    public void nf_ws_getDirectoriosAsync(string as_path_dir, object userState) {
        if ((this.nf_ws_getDirectoriosOperationCompleted == null)) {
            this.nf_ws_getDirectoriosOperationCompleted = new System.Threading.SendOrPostCallback(this.Onnf_ws_getDirectoriosOperationCompleted);
        }
        this.InvokeAsync("nf_ws_getDirectorios", new object[] {
                    as_path_dir}, this.nf_ws_getDirectoriosOperationCompleted, userState);
    }
    
    private void Onnf_ws_getDirectoriosOperationCompleted(object arg) {
        if ((this.nf_ws_getDirectoriosCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.nf_ws_getDirectoriosCompleted(this, new nf_ws_getDirectoriosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.coes.org.pe/nf_ws_getFiles", RequestNamespace="http://www.coes.org.pe/", ResponseNamespace="http://www.coes.org.pe/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public n_InfoFile[] nf_ws_getFiles(string as_path_dir) {
        object[] results = this.Invoke("nf_ws_getFiles", new object[] {
                    as_path_dir});
        return ((n_InfoFile[])(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult Beginnf_ws_getFiles(string as_path_dir, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("nf_ws_getFiles", new object[] {
                    as_path_dir}, callback, asyncState);
    }
    
    /// <remarks/>
    public n_InfoFile[] Endnf_ws_getFiles(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((n_InfoFile[])(results[0]));
    }
    
    /// <remarks/>
    public void nf_ws_getFilesAsync(string as_path_dir) {
        this.nf_ws_getFilesAsync(as_path_dir, null);
    }
    
    /// <remarks/>
    public void nf_ws_getFilesAsync(string as_path_dir, object userState) {
        if ((this.nf_ws_getFilesOperationCompleted == null)) {
            this.nf_ws_getFilesOperationCompleted = new System.Threading.SendOrPostCallback(this.Onnf_ws_getFilesOperationCompleted);
        }
        this.InvokeAsync("nf_ws_getFiles", new object[] {
                    as_path_dir}, this.nf_ws_getFilesOperationCompleted, userState);
    }
    
    private void Onnf_ws_getFilesOperationCompleted(object arg) {
        if ((this.nf_ws_getFilesCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.nf_ws_getFilesCompleted(this, new nf_ws_getFilesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    public new void CancelAsync(object userState) {
        base.CancelAsync(userState);
    }
}

/// <remarks/>
[System.Xml.Serialization.XmlIncludeAttribute(typeof(CBaseDll))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(n_InfoFile))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(n_InfoDirectory))]
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.coes.org.pe/")]
public partial class CBase {
    
    private int codigoRetornoField;
    
    /// <remarks/>
    public int CodigoRetorno {
        get {
            return this.codigoRetornoField;
        }
        set {
            this.codigoRetornoField = value;
        }
    }
}

/// <remarks/>
[System.Xml.Serialization.XmlIncludeAttribute(typeof(n_InfoFile))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(n_InfoDirectory))]
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.coes.org.pe/")]
public partial class CBaseDll : CBase {
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.coes.org.pe/")]
public partial class n_InfoFile : CBaseDll {
    
    private string is_NameField;
    
    private string is_FullNameField;
    
    private FileAttributes in_AtributosField;
    
    private long id_SizeField;
    
    private System.DateTime idt_file_createField;
    
    private System.DateTime idt_file_last_accessField;
    
    private System.DateTime idt_file_last_writeField;
    
    private string is_DirectoryNameField;
    
    private string is_ExtensionField;
    
    private string is_PathField;
    
    private string is_TypeField;
    
    /// <remarks/>
    public string is_Name {
        get {
            return this.is_NameField;
        }
        set {
            this.is_NameField = value;
        }
    }
    
    /// <remarks/>
    public string is_FullName {
        get {
            return this.is_FullNameField;
        }
        set {
            this.is_FullNameField = value;
        }
    }
    
    /// <remarks/>
    public FileAttributes in_Atributos {
        get {
            return this.in_AtributosField;
        }
        set {
            this.in_AtributosField = value;
        }
    }
    
    /// <remarks/>
    public long id_Size {
        get {
            return this.id_SizeField;
        }
        set {
            this.id_SizeField = value;
        }
    }
    
    /// <remarks/>
    public System.DateTime idt_file_create {
        get {
            return this.idt_file_createField;
        }
        set {
            this.idt_file_createField = value;
        }
    }
    
    /// <remarks/>
    public System.DateTime idt_file_last_access {
        get {
            return this.idt_file_last_accessField;
        }
        set {
            this.idt_file_last_accessField = value;
        }
    }
    
    /// <remarks/>
    public System.DateTime idt_file_last_write {
        get {
            return this.idt_file_last_writeField;
        }
        set {
            this.idt_file_last_writeField = value;
        }
    }
    
    /// <remarks/>
    public string is_DirectoryName {
        get {
            return this.is_DirectoryNameField;
        }
        set {
            this.is_DirectoryNameField = value;
        }
    }
    
    /// <remarks/>
    public string is_Extension {
        get {
            return this.is_ExtensionField;
        }
        set {
            this.is_ExtensionField = value;
        }
    }
    
    /// <remarks/>
    public string is_Path {
        get {
            return this.is_PathField;
        }
        set {
            this.is_PathField = value;
        }
    }
    
    /// <remarks/>
    public string is_Type {
        get {
            return this.is_TypeField;
        }
        set {
            this.is_TypeField = value;
        }
    }
}

/// <remarks/>
[System.FlagsAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.coes.org.pe/")]
public enum FileAttributes {
    
    /// <remarks/>
    ReadOnly = 1,
    
    /// <remarks/>
    Hidden = 2,
    
    /// <remarks/>
    System = 4,
    
    /// <remarks/>
    Directory = 8,
    
    /// <remarks/>
    Archive = 16,
    
    /// <remarks/>
    Device = 32,
    
    /// <remarks/>
    Normal = 64,
    
    /// <remarks/>
    Temporary = 128,
    
    /// <remarks/>
    SparseFile = 256,
    
    /// <remarks/>
    ReparsePoint = 512,
    
    /// <remarks/>
    Compressed = 1024,
    
    /// <remarks/>
    Offline = 2048,
    
    /// <remarks/>
    NotContentIndexed = 4096,
    
    /// <remarks/>
    Encrypted = 8192,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.coes.org.pe/")]
public partial class n_InfoDirectory : CBaseDll {
    
    private string is_NameField;
    
    private string is_FullNameField;
    
    private FileAttributes in_AtributosField;
    
    private double id_SizeField;
    
    private int ii_nobjectosField;
    
    private System.DateTime idt_dir_createField;
    
    private System.DateTime idt_dir_last_accessField;
    
    private System.DateTime idt_dir_last_writeField;
    
    private string is_pathField;
    
    /// <remarks/>
    public string is_Name {
        get {
            return this.is_NameField;
        }
        set {
            this.is_NameField = value;
        }
    }
    
    /// <remarks/>
    public string is_FullName {
        get {
            return this.is_FullNameField;
        }
        set {
            this.is_FullNameField = value;
        }
    }
    
    /// <remarks/>
    public FileAttributes in_Atributos {
        get {
            return this.in_AtributosField;
        }
        set {
            this.in_AtributosField = value;
        }
    }
    
    /// <remarks/>
    public double id_Size {
        get {
            return this.id_SizeField;
        }
        set {
            this.id_SizeField = value;
        }
    }
    
    /// <remarks/>
    public int ii_nobjectos {
        get {
            return this.ii_nobjectosField;
        }
        set {
            this.ii_nobjectosField = value;
        }
    }
    
    /// <remarks/>
    public System.DateTime idt_dir_create {
        get {
            return this.idt_dir_createField;
        }
        set {
            this.idt_dir_createField = value;
        }
    }
    
    /// <remarks/>
    public System.DateTime idt_dir_last_access {
        get {
            return this.idt_dir_last_accessField;
        }
        set {
            this.idt_dir_last_accessField = value;
        }
    }
    
    /// <remarks/>
    public System.DateTime idt_dir_last_write {
        get {
            return this.idt_dir_last_writeField;
        }
        set {
            this.idt_dir_last_writeField = value;
        }
    }
    
    /// <remarks/>
    public string is_path {
        get {
            return this.is_pathField;
        }
        set {
            this.is_pathField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
public delegate void nf_UploadFileCompletedEventHandler(object sender, nf_UploadFileCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class nf_UploadFileCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal nf_UploadFileCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public bool Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((bool)(this.results[0]));
        }
    }
    
    /// <remarks/>
    public string as_msg {
        get {
            this.RaiseExceptionIfNecessary();
            return ((string)(this.results[1]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
public delegate void nf_MoveFileCompletedEventHandler(object sender, nf_MoveFileCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class nf_MoveFileCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal nf_MoveFileCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public bool Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((bool)(this.results[0]));
        }
    }
    
    /// <remarks/>
    public string as_msg {
        get {
            this.RaiseExceptionIfNecessary();
            return ((string)(this.results[1]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
public delegate void nf_ws_getInfoDirCompletedEventHandler(object sender, nf_ws_getInfoDirCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class nf_ws_getInfoDirCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal nf_ws_getInfoDirCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public object Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((object)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
public delegate void nf_GetPathfromDirVirtualCompletedEventHandler(object sender, nf_GetPathfromDirVirtualCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class nf_GetPathfromDirVirtualCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal nf_GetPathfromDirVirtualCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public string Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((string)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
public delegate void nf_ws_getDirectoriosCompletedEventHandler(object sender, nf_ws_getDirectoriosCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class nf_ws_getDirectoriosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal nf_ws_getDirectoriosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public n_InfoDirectory[] Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((n_InfoDirectory[])(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
public delegate void nf_ws_getFilesCompletedEventHandler(object sender, nf_ws_getFilesCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class nf_ws_getFilesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal nf_ws_getFilesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public n_InfoFile[] Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((n_InfoFile[])(this.results[0]));
        }
    }
}
