using OfficeOpenXml;
using OfficeOpenXml.Drawing;
using OfficeOpenXml.Style;
using System;
using System.Collections.Generic;
using System.Drawing;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Configuration;

namespace COES.MVC.Intranet.Areas.Coordinacion.Helper
{
    public class HelperCoordinacion
    {
        /// <summary>
        /// Lista las URS del sistema aislado
        /// </summary>
        /// <returns></returns>
        public static List<string> ObtieneCentralesURSAislado()
        {
            string[] list = {
                "C.H. CAÑÓN DEL PATO",
                "C.H. CARHUAQUERO",
                "C.H. CHARCANI V",
                "C.H. HUANZA",
                "C.H. HUINCO",
                "C.H. MACHUPICCHU",
                "C.H. MALPASO",
                "C.H. MANTARO",
                "C.H. MATUCANA",
                "C.H. RESTITUCIÓN",
                "C.H. SAN GABÁN",
                "C.H. YAUPI",
                "C.H. YUNCÁN",
                "C.T. CHILINA",
                "C.T. ILO1-TG1",
                "C.T. ILO1-TG2",
                "C.T. ILO2 TG1 - D2",
                "C.T. ILO2 TG2 - D2",         
                "C.T. ILO2 TG3 - D2 ",       
                "C.T. INDEPENDENCIA",
                "C.T. MALACAS3 TG 5 - D2", 
                "C.T. MOLLENDO",
                "C.T. PISCO-TG1",
                "C.T. PISCO-TG2",
                "C.T. SAN NICOLAS-TV1",
                "C.T. SAN NICOLAS-TV2",
                "C.T. SAN NICOLAS-TV3",
                "C.T. TUMBES"
            };

            return list.ToList();
        }

        /// <summary>
        /// Permite listar las subestaciones
        /// </summary>
        /// <returns></returns>
        public static List<string> ListarSubEstaciones()
        {
            string[] list = { 
            "ABANCAY 138 KV",
            "AGUAYTIA 138 KV",
            "AGUAYTIA 220 KV",
            "ARICOTA 138 KV",
            "ARICOTA66 KV",
            "AYAVIRI 138 KV",
            "AZANGARO 138 KV",
            "BALNEARIO 220 KV",
            "BALNEARIO 60 KV",
            "BARSI 220 KV",
            "BARSI 60 KV",
            "C.ILO 138 KV",
            "CACHIMAYO 138 KV",
            "CAJ NOR 220 KV",
            "CALLAHUANC 60 KV",
            "CALLALI 138 KV",
            "CANTERA 220 KV",
            "CARABAYLL 220 KV",
            "CARABAYLL 500 KV",
            "CARHUAMAY 138 KV",
            "CARHUAMAY 220 KV",
            "CARHUAMAYO 50 KV",
            "CARHUAQUE 220 KV",
            "CARIPA 138 KV",
            "CERROVERD 138 KV",
            "CHAVARR 60 1 KV",
            "CHAVARR 60 2 KV",
            "CHAVARRIA 220 KV",
            "CHICLAYO 220 KV",
            "CHILCA 220 KV",
            "CHILCAN 220 KV",
            "CHILCAN 500 KV",
            "CHILLON 220 KV",
            "CHILLON 60 KV",
            "CHIMBOTE 138 KV",
            "CHIMBOTE 220 KV",
            "CHIMBOTE 500 KV",
            "COMBAPATA 138 KV",
            "CONOCOCHA 220 KV",
            "COTARUSE 220 KV",
            "DESIERTO 220 KV",
            "DOLORESPA 138 KV",
            "EXCELSIOR 50 KV",
            "GUADALUPE 220 KV",
            "HUACAVELI 220 KV",
            "HUACHIPA 60 KV",
            "HUACHO 220 KV",
            "HUALLANCA 138 KV",
            "HUAMPANI 60 KV",
            "HUANUCO 138 KV",
            "HUANZA 220 KV",
            "HUARANGAL 60 KV",
            "HUAYUCACH 220 KV",
            "HUINCO 220 KV",
            "ICA 220 KV",
            "ILO2 220 KV",
            "ILO3- 138 KV",
            "INDEPENDE 220 KV",
            "INDEPENDE 60 KV",
            "INDUSTRI 60 KV",
            "INDUSTRIALES KV",
            "JULIACA 138 KV",
            "KYM AYLL 138 KV",
            "KYM AYLL 220 KV",
            "LHEROES 220 KV",
            "LHEROES66 KV",
            "LLNINA 220 KV",
            "LLNINA 500 KV",
            "MACCHUPIC 138 KV",
            "MACHALA KV",
            "MARCONA 220 KV",
            "MIRADOR 220 KV",
            "MIRADOR 60 KV",
            "MOLLENDO 138 KV",
            "MONTALVO 220 KV",
            "MONTALVO 500 KV",
            "MOQUEGUA 138 KV",
            "MOQUEGUA 220 KV",
            "MOYOPAMPA 60 KV",
            "NANA 60 KV",
            "OCOÑA 500 KV",
            "OQUEND 60 KV",
            "OROYA 138 KV",
            "OROYA 220 KV",
            "OROYA 50 KV",
            "PACHACHAC 220 KV",
            "PARAGSHA 138 KV",
            "PARAGSHA 220 KV",
            "PARAGSHA 50 KV",
            "PARAMONUE 220 KV",
            "PBLANCA 138 KV",
            "PEX 138 KV",
            "PIURA 220 KV",
            "PIURA 60 KV",
            "PLANICIE 220 KV",
            "POMACOCHA 220 KV",
            "POROMA 220 KV",
            "POROMA 500 KV",
            "PUCALLPA 138 KV",
            "PUCALLPA 60 KV",
            "PUERTO MALDONADO 138 KV",
            "PUNO 138 KV",
            "PUNO 220 KV",
            "QUENCORO 138 KV",
            "RAMADA 220 KV",
            "REPARTICI 138 KV",
            "RZINC 220 KV",
            "SAN JUAN 220 KV",
            "SANTAROSA 220 KV",
            "SANTAROSA 60 KV",
            "SOCABAYA 138 KV",
            "SOCABAYA 220 KV",
            "TALARA 220 KV",
            "TINGOMARI 138 KV",
            "TINGOMARI 220 KV",
            "TINTAYA 138 KV",
            "TINTAYA 220 KV",
            "TOMASIRI66 KV",
            "TRUJILLO 220 KV",
            "TRUJILLO 500 KV",
            "VENTANILL 220 KV",
            "VIZCARRA 220 KV",
            "ZAPALLAL 220 KV",
            "ZORRITOS 220 KV"
            };

            return list.ToList();
        }

        /// <summary>
        /// Permite listar las horas
        /// </summary>
        public static List<string> ListarHoras()
        {
            string[] list = {
                            "0:00",
                            "0:30",
                            "1:00",
                            "1:30",
                            "2:00",
                            "2:30",
                            "3:00",
                            "3:30",
                            "4:00",
                            "4:30",
                            "5:00",
                            "5:30",
                            "6:00",
                            "6:30",
                            "7:00",
                            "7:30",
                            "8:00",
                            "8:30",
                            "9:00",
                            "9:30",
                            "10:00",
                            "10:30",
                            "11:00",
                            "11:30",
                            "12:00",
                            "12:30",
                            "13:00",
                            "13:30",
                            "14:00",
                            "14:30",
                            "15:00",
                            "15:30",
                            "16:00",
                            "16:30",
                            "17:00",
                            "17:30",
                            "18:00",
                            "18:30",
                            "19:00",
                            "19:30",
                            "20:00",
                            "20:30",
                            "21:00",
                            "21:30",
                            "22:00",
                            "22:30",
                            "23:00",
                            "23:30",
                            "24 a más"
                            };

            return list.ToList();
        }

        /// <summary>
        /// Lista los equipos
        /// </summary>
        /// <returns></returns>
        public static List<string> ListarEquipos()
        {
            string[] list = {
                                "L-1001 MACHUPICCHU - CACHIMAYO",
                                "L-1002 MACHUPICCHU - QUENCORO",
                                "L-1003 CACHIMAYO - DOLORESPATA",
                                "L-1003 ICA - PARCANA",
                                "L-1004 ICA - ICA N",
                                "L-1004 QUENCORO - DOLORESPATA",
                                "L-1005/1 COMBAPATA - QUENCORO",
                                "L-1005_1 QUENCORO - TINTAYA",
                                "L-1005_2 TINTAYA - COMBAPATA",
                                "L-1006 AZÁNGARO - TINTAYA",
                                "L-1006/2 AYAVIRI - AZÁNGARO",
                                "L-1006_1 TINTAYA - AYAVIRI",
                                "L-1007 CACHIMAYO - ABANCAY",
                                "L-1008 TINTAYA - CALLALLI",
                                "L-1011 AZÁNGARO - JULIACA",
                                "L-1012 JULIACA - PUNO",
                                "L-1012 TRUJILLO NORTE - HUANCHACO",
                                "L-1020 CALLALLI - SANTUARIO",
                                "L-1021 SANTUARIO - SOCABAYA",
                                "L-1022 SANTUARIO - SOCABAYA",
                                "L-1025 HUÁNUCO",
                                "L-1025 MOQUEGUA - TOQUEPALA",
                                "L-1026 TOQUEPALA - ARICOTA 2",
                                "L-1029 CERRO VERDE - REPARTICIÓN",
                                "L-1030 HUÁNUCO - AMBO_HUASCAR",
                                "L-1030 REPARTICION - MOLLENDO",
                                "L-1037 TINTAYA - TINTAYA NUEVA",
                                "L-1042 AZÁNGARO - AYAVIRI",
                                "L-1101 PARAMONGA N. - PARAMONGA E.",
                                "L-1103 CHIMBOTE 1 - HUALLANCA",
                                "L-1104 CHIMBOTE 1 - HUALLANCA",
                                "L-1105 CHIMBOTE 1 - HUALLANCA",
                                "L-1120 PARAGSHA II - HUÁNUCO",
                                "L-1121 HUÁNUCO - TINGO MARÍA",
                                "L-1125 AGUAYTÍA - PUCALLPA",
                                "L-1131 HUALLANCA - KIMAN AYLLU",
                                "L-1142 PIEDRA BLANCA - TINGO MARIA",
                                "L-1381 MOQUEGUA - BOTIFLACA",
                                "L-1382 MOQUEGUA - BOTIFLACA",
                                "L-1383 ILO 1 - MOQUEGUA",
                                "L-1384 MOQUEGUA - MILL SITE",
                                "L-1385 ILO 1 - ILO-ELECTROSUR",
                                "L-1385 ILO 1 - MILLSITE",
                                "L-1385 ILO-ELECTROSUR - DERIV. QDA ONDA",
                                "L-1385 MILL SITE - DERIV. QDA HONDA",
                                "L-1386 MILL SITE - BOTIFLACA",
                                "L-1386 PUSH BACK - MILL SITE",
                                "L-1387 ILO 1 - REFINERÍA",
                                "L-1388 MILL SITE - TOQUEPALA",
                                "L-1702 CARHUAMAYO - CARIPA",
                                "L-1703 CARHUAMAYO - PARAGSHA II",
                                "L-1705 OROYA NUEVA - CARIPA",
                                "L-1706 CARIPA - CONDORCOCHA",
                                "L-1708 OXIDOS CERRO - CINCO MANANTIALES",
                                "L-1709 OXIDOS CERRO - PARAGSHA",
                                "L-2001 HUINCO - SANTA ROSA N.",
                                "L-2002 HUINCO - SANTA ROSA N.",
                                "L-2003 SANTA ROSA N. - CHAVARRÍA",
                                "L-2004 SANTA ROSA N. - CHAVARRÍA",
                                "L-2005 CHAVARRÍA - BARSI",
                                "L-2006 CHAVARRÍA - BARSI",
                                "L-2007 MATUCANA - CALLAHUANCA",
                                "L-2008 CALLAHUANCA - CAJAMARQUILLA",
                                "L-2009 CALLAHUANCA - CAJAMARQUILLA",
                                "L-2010 INDUSTRIALES - SANTA ROSA N.",
                                "L-2011 SAN JUAN - SANTA ROSA N.",
                                "L-2012 SAN JUAN - BALNEARIOS",
                                "L-2013 SAN JUAN - BALNEARIOS",
                                "L-2014 CAJAMARQUILLA - CHAVARRIA",
                                "L-2015 CAJAMARQUILLA - CHAVARRIA",
                                "L-2016 VENTANILLA - CHILLÓN",
                                "L-2017 VENTANILLA - CHILLÓN",
                                "L-2018 SAN JUAN - INDUSTRIALES",
                                "L-2022 SOCABAYA - TINTAYA NUEVA",
                                "L-2023 SOCABAYA - TINTAYA NUEVA",
                                "L-2024 TINTATA NUEVA - CONSTANCIA",
                                "L-2025 SOCABAYA - MOQUEGUA",
                                "L-2026 SOCABAYA - MOQUEGUA",
                                "L-2027 ILO 2 - MOQUEGUA",
                                "L-2028 ILO 2 - MOQUEGUA",
                                "L-2029 MOQUEGUA - TACNA",
                                "L-2030 MOQUEGUA - PUNO",
                                "L-2051 MANTARO - COTARUSE",
                                "L-2052 MANTARO - COTARUSE",
                                "L-2053 COTARUSE - SOCABAYA",
                                "L-2054 COTARUSE - SOCABAYA",
                                "L-2057 MONTALVO - MOQUEGUA",
                                "L-2061_62_64 CERRO VERDE - SULFUROS",
                                "L-2090 CHILCA - CANTERA",
                                "L-2091 CHILCA - DESIERTO",
                                "L-2093 SAN JUAN - CHILCA",
                                "L-2094 SAN JUAN - CHILCA",
                                "L-2095 SAN JUAN - CHILCA",
                                "L-2103 CHILCA - PLANICIE",
                                "L-2104 CHILCA - PLANICIE",
                                "L-2105 PLANICIE - CARABAYLLO",
                                "L-2106 PLANICIE - CARABAYLLO",
                                "L-2107 CARABAYLLO - ZAPALLAL",
                                "L-2108 CARABAYLLO - ZAPALLAL",
                                "L-2117 LOMERA - ZAPALLAL",
                                "L-2161 CAMPANA - PARIÑAS",
                                "L-2162 FELAM - PIURA OESTE",
                                "L-2170 CUPISNIQUE - GUADALUPE",
                                "L-2201 CAMPO ARMIÑO - POMACOCHA",
                                "L-2202 CAMPO ARMIÑO - POMACOCHA",
                                "L-2203 CAMPO ARMIÑO - INDEPENDENCIA",
                                "L-2204 CAMPO ARMIÑO - HUANCAVELICA",
                                "L-2205 POMACOCHA - SAN JUAN",
                                "L-2206 POMACOCHA - SAN JUAN",
                                "L-2207 INDEPENDENCIA - CANTERA",
                                "L-2208 INDEPENDENCIA - DESIERTO",
                                "L-2208 SAN JUAN - INDEPENDENCIA",
                                "L-2209 ICA - INDEPENDENCIA",
                                "L-2210 ICA - INDEPENDENCIA",
                                "L-2211 ICA - MARCONA",
                                "L-2212 ZAPALLAL - HUACHO",
                                "L-2213 HUACHO - PARAMONGA NUEVA",
                                "L-2214 ZAPALLAL - HUACHO",
                                "L-2215 PARAMONGA N. - CHIMBOTE 1",
                                "L-2216 PARAMONGA N. - CHIMBOTE 1",
                                "L-2218 CAMPO ARMIÑO - PACHACHACA",
                                "L-2219 CAMPO ARMIÑO - PACHACHACA",
                                "L-2220 CAMPO ARMIÑO - HUAYUCACHI",
                                "L-2221 HUAYUCACHI - HUANZA",
                                "L-2222 PACHACHACA - CALLAHUANCA (REP)",
                                "L-2223 PACHACHACA - CALLAHUANCA (REP)",
                                "L-2224 PACHACHACA - OROYA NUEVA",
                                "L-2226 PACHACHACA - POMACOCHA",
                                "L-2231 HUANCAVELICA - INDEPENDENCIA",
                                "L-2232 TRUJILLO NORTE - CHIMBOTE 1",
                                "L-2233 TRUJILLO NORTE - CHIMBOTE 1",
                                "L-2234 GUADALUPE - TRUJILLO NORTE",
                                "L-2235 GUADALUPE - TRUJILLO NORTE",
                                "L-2236 CHICLAYO OESTE - GUADALUPE",
                                "L-2237 CHICLAYO OESTE - GUADALUPE",
                                "L-2238 CHICLAYO OESTE - LA NIÑA",
                                "L-2239 CHICLAYO OESTE - FELAM",
                                "L-2240 CARHUAQUERO - CHICLAYO OESTE",
                                "L-2241 LA NIÑA - PIURA OESTE",
                                "L-2242 VENTANILLA - ZAPALLAL",
                                "L-2243 VENTANILLA - ZAPALLAL",
                                "L-2244 CHAVARRÍA - VENTANILLA",
                                "L-2245 CHAVARRÍA - VENTANILLA",
                                "L-2246 CHAVARRÍA - VENTANILLA",
                                "L-2248 PIURA OESTE - PARIÑAS",
                                "L-2249 TALARA - ZORRITOS",
                                "L-2250 PIURA - TALARA",
                                "L-2251 AGUAYTÍA - TINGO MARÍA",
                                "L-2252 TINGO MARÍA - VIZCARRA",
                                "L-2253 CONOCOCHA - VIZCARRA",
                                "L-2254 VIZCARRA - PARAGSHA 2",
                                "L-2255 VIZCARRA - ANTAMINA",
                                "L-2256 PACHACHACA - YANANGO",
                                "L-2257 YANANGO - CHIMAY",
                                "L-2258 PARAGSHA II - CARHUAMAYO",
                                "L-2259 CARHUAMAYO - OROYA NUEVA",
                                "L-2260 TRUJILLO NORTE - CAJAMARCA NORTE",
                                "L-2261 CAJAMARCA NORTE - LA QUINUA",
                                "L-2262 VIZCARRA - SANTA LUISA",
                                "L-2263 CAJAMARCA NORTE - CERRO CORONA",
                                "L-2264 PARAGSHA II - CONOCOCHA",
                                "L-2265 CARHUAMAYO - SANTA ISABEL",
                                "L-2266 CARHUAMAYO - SANTA ISABEL",
                                "L-2267 PARAGSHA II - CARHUAMAYO",
                                "L-2268 PARAGSHA II - CARHUAMAYO",
                                "L-2269 CONOCOCHA - KIMAN AYLLU",
                                "L-2270 CONOCOCHA - KIMAN AYLLU",
                                "L-2271 PARAGSHA - FRANCOISE",
                                "L-2272 KIMAN AYLLU - LA RAMADA",
                                "L-2273 LA RAMADA - CAJAMARCA NORTE",
                                "L-2274 KIMAN AYLLU - LA RAMADA",
                                "L-2275 LA RAMADA CAJAMARCA NORTE",
                                "L-2278 PARAMONGA N. - CONOCOCHA",
                                "L-2279 HUACHO - PARAMONGA NUEVA",
                                "L-2280 ZORRITOS - MACHALA",
                                "L-2292 POROMA - MARCONA",
                                "L-2293 POROMA - MARCONA",
                                "L-2294 POMACOCHA - CARHUAMAYO",
                                "L-2295 TALARA - PARIÑAS",
                                "L-5001 CHILCA - CARABAYLLO",
                                "L-5006 CARABAYLLO - CHIMBOTE1",
                                "L-5008 CHIMBOTE 500 - TRUJILLO 500",
                                "L-5010 TRUJILLO - LA NIÑA",
                                "L-5032 CHILCA - POROMA",
                                "L-5034 POROMA - OCOÑA",
                                "L-5036 OCOÑA - MONTALVO",
                                "L-6520 PARAGSHA I - EXCELSIOR",
                                "L-6620 ARICOTA 2 - TOMASIRI",
                                "L-6637 TOMASIRI - LOS HÉROES",
                                "CL 2235 GUADALUPE",
                                "CL 2235 TRUJILLO NORTE",
                                "CL 2237 CHICLAYO OESTE",
                                "CL 2237 GUADALUPE",
                                "CL1001 CACHIMAYO",
                                "CL1002 CACHIMAYO",
                                "CL1002 QUENCORO",
                                "CL1003 CACHIMAYO",
                                "CL-1003 DOLORESPATA",
                                "CL-1004 DOLORESPATA",
                                "CL1004 QUENCORO",
                                "CL1005 QUENCORO",
                                "CL1005 TINTAYA",
                                "CL1006 AZÁNGARO",
                                "CL1006 TINTAYA",
                                "CL1008 CALLALLI",
                                "CL1008 TINTAYA",
                                "CL1011 AZÁNGARO",
                                "CL1011 JULIACA",
                                "CL1011 TRUJILLO NORTE",
                                "CL1012 JULIACA",
                                "CL1012 PUNO",
                                "CL1012 TRUJILLO NORTE",
                                "CL1020 CALLALLI",
                                "CL1020 SANTUARIO",
                                "CL1021 SANTUARIO",
                                "CL1021 SOCABAYA",
                                "CL1022 SANTUARIO",
                                "CL1022 SOCABAYA",
                                "CL1025 MOQUEGUA",
                                "CL1025 TOQUEPALA",
                                "CL1026 SANTUARIO",
                                "CL1026 TOQUEPALA",
                                "CL1029 REPARTICIÓN",
                                "CL1030 MOLLENDO",
                                "CL1030 REPARTICIÓN",
                                "CL1101 PARAMONGA NUEVA",
                                "CL1103 CHIMBOTE 1",
                                "CL1103 HUALLANCA",
                                "CL1104 CHIMBOTE 1",
                                "CL1104 HUALLANCA",
                                "CL1105 CHIMBOTE 1",
                                "CL1105 HUALLANCA",
                                "CL1120 HUÁNUCO",
                                "CL1120 PARAGSHA 2",
                                "CL1121 HUÁNUCO",
                                "CL1121 TINGO MARÍA",
                                "CL1125 AGUAYTÍA",
                                "CL1125 PUCALLPA",
                                "CL-1131 KIMAN AYLLU",
                                "CL-1142 PIEDRA BLANCA",
                                "CL-1142 TINGO MARIA",
                                "CL1381 BOTIFLACA (CUAJONE)",
                                "CL1381 MOQUEGUA",
                                "CL1382 BOTIFLACA (CUAJONE)",
                                "CL1382 MOQUEGUA",
                                "CL1383 ILO 1",
                                "CL1383 MOQUEGUA",
                                "CL1384 MILL SITE (TOQUEPALA)",
                                "CL1384 MOQUEGUA",
                                "CL1385 ILO 1",
                                "CL1385 ILO-ELECTROSUR",
                                "CL1385 MILL SITE (TOQUEPALA)",
                                "CL1385 QUEBRADA HONDA",
                                "CL1386 BOTIFLACA (CUAJONE)",
                                "CL1386 MILL SITE (TOQUEPALA)",
                                "CL1386 PUSH BACK (TOQUEPALA)",
                                "CL1387 ILO 1",
                                "CL1387 REFINERÍA ILO",
                                "CL1388 MILL SITE (TOQUEPALA)",
                                "CL1388 TOQUEPALA",
                                "CL-1702 CARHUAMAYO",
                                "CL-1703 CARHUAMAYO",
                                "CL1703 PARAGSHA 2",
                                "CL-1703 SE CINCO MANANTIALES",
                                "CL-1705 OROYA NUEVA",
                                "CL-1708 SE CINCO MANANTIALES",
                                "CL-1708 SE OXIDOS CERRO",
                                "CL-1709 SE OXIDOS CERRO",
                                "CL-1709 SE PARAGSHA",
                                "CL2001 HUINCO",
                                "CL2001 SANTA ROSA N.",
                                "CL2002 HUINCO",
                                "CL2002 SANTA ROSA N.",
                                "CL2003 CHAVARRÍA",
                                "CL2003 SANTA ROSA N.",
                                "CL2004 CHAVARRÍA",
                                "CL2004 SANTA ROSA N.",
                                "CL2005 BARSI",
                                "CL2005 CHAVARRÍA",
                                "CL2006 BARSI",
                                "CL2006 CHAVARRÍA",
                                "CL2008 CAJAMARQUILLA",
                                "CL2008 CALLAHUANCA (EDG)",
                                "CL2009 CAJAMARQUILLA",
                                "CL2009 CALLAHUANCA (EDG)",
                                "CL2010 SANTA ROSA N.",
                                "CL2011 SAN JUAN",
                                "CL2011 SANTA ROSA N.",
                                "CL2012 BALNEARIOS",
                                "CL2012 SAN JUAN",
                                "CL2013 BALNEARIOS",
                                "CL2013 SAN JUAN",
                                "CL2014 CAJAMARQUILLA",
                                "CL2014 CHAVARRÍA",
                                "CL2015 CAJAMARQUILLA",
                                "CL2015 CHAVARRÍA",
                                "CL-2016 CHILLON",
                                "CL-2016 VENTANILLA",
                                "CL-2017 CHILLON",
                                "CL-2017 VENTANILLA",
                                "CL-2018 INDUSTRIALES",
                                "CL2018 SAN JUAN",
                                "CL-2018 SAN JUAN",
                                "CL-2022 SE SOCABAYA",
                                "CL-2022 SE TINTAYA",
                                "CL-2023 SE SOCABAYA",
                                "CL-2023 SE TINTAYA",
                                "CL2025 MOQUEGUA",
                                "CL2025 SOCABAYA",
                                "CL2026 MOQUEGUA",
                                "CL2026 SOCABAYA",
                                "CL2029 LOS HÉROES",
                                "CL2029 MOQUEGUA",
                                "CL2030 MOQUEGUA",
                                "CL2030 PUNO",
                                "CL-2051 CAMPO ARMIÑO",
                                "CL-2051 COTARUSE",
                                "CL-2052 CAMPO ARMIÑO",
                                "CL-2052 COTARUSE",
                                "CL-2053 COTARUSE",
                                "CL-2053 SOCABAYA",
                                "CL-2054 COTARUSE",
                                "CL-2054 SOCABAYA",
                                "CL-2057 MONTALVO",
                                "CL-2057 MOQUEGUA",
                                "CL2064 CERRO VERDE SMCV",
                                "CL2064 SULFUROS",
                                "CL2090 CANTERA",
                                "CL2090 CHILCA-REP",
                                "CL2091 CHILCA-REP",
                                "CL2091 DESIERTO",
                                "CL2093 CHILCA-REP",
                                "CL2093 SAN JUAN",
                                "CL2094 CHILCA-REP",
                                "CL2094 SAN JUAN",
                                "CL2095 CHILCA-REP",
                                "CL2095 SAN JUAN",
                                "CL-2103 CHILCA-CTM",
                                "CL-2103 PLANICIE",
                                "CL-2104 CHILCA-CTM",
                                "CL-2104 PLANICIE",
                                "CL-2105 CARABAYLLO",
                                "CL-2105 PLANICIE",
                                "CL-2106 CARABAYLLO",
                                "CL-2106 PLANICIE",
                                "CL-2107 CARABAYLLO",
                                "CL-2107 ZAPALLAL",
                                "CL-2108 CARABAYLLO",
                                "CL-2108 ZAPALLAL",
                                "CL2201 CAMPO ARMIÑO",
                                "CL2201 POMACOCHA",
                                "CL2202 CAMPO ARMIÑO",
                                "CL2202 POMACOCHA",
                                "CL2203 CAMPO ARMIÑO",
                                "CL2203 HUANCAVELICA",
                                "CL2203 INDEPENDENCIA",
                                "CL2204 CAMPO ARMIÑO",
                                "CL2204 HUANCAVELICA",
                                "CL2205 POMACOCHA",
                                "CL2205 SAN JUAN",
                                "CL2206 POMACOCHA",
                                "CL2206 SAN JUAN",
                                "CL2207 CANTERA",
                                "CL2207 INDEPENDENCIA",
                                "CL2208 DESIERTO",
                                "CL2208 INDEPENDENCIA",
                                "CL2208 SAN JUAN",
                                "CL-2209 ICA",
                                "CL2209 INDEPENDENCIA",
                                "CL-2210 ICA",
                                "CL2210 INDEPENDENCIA",
                                "CL-2211 ICA",
                                "CL2211 MARCONA",
                                "CL2212 HUACHO",
                                "CL-2212 ZAPALLAL",
                                "CL2213 HUACHO",
                                "CL2213 PARAMONGA NUEVA",
                                "CL2214 HUACHO",
                                "CL2214 PARAMONGA NUEVA",
                                "CL-2214 ZAPALLAL",
                                "CL2215 CHIMBOTE 1",
                                "CL2215 PARAMONGA NUEVA",
                                "CL2216 CHIMBOTE 1",
                                "CL2216 PARAMONGA NUEVA",
                                "CL2218 CAMPO ARMIÑO",
                                "CL2218 PACHACHACA",
                                "CL2219 CAMPO ARMIÑO",
                                "CL2219 PACHACHACA",
                                "CL2220 CAMPO ARMIÑO",
                                "CL2220 HUAYUCACHI",
                                "CL2221 HUAYUCACHI",
                                "CL2222 CALLAHUANCA (REP)",
                                "CL2222 PACHACHACA",
                                "CL2223 CALLAHUANCA (REP)",
                                "CL2223 PACHACHACA",
                                "CL2224 OROYA NUEVA",
                                "CL2224 PACHACHACA",
                                "CL2226 PACHACHACA",
                                "CL2226 POMACOCHA",
                                "CL2231 HUANCAVELICA",
                                "CL2231 INDEPENDENCIA",
                                "CL2232 CHIMBOTE 1",
                                "CL2232 TRUJILLO NORTE",
                                "CL2233 CHIMBOTE 1",
                                "CL2233 TRUJILLO NORTE",
                                "CL2234 GUADALUPE",
                                "CL2234 TRUJILLO NORTE",
                                "CL2236 CHICLAYO OESTE",
                                "CL2236 GUADALUPE",
                                "CL2238 CHICLAYO OESTE",
                                "CL-2238 LA NIÑA",
                                "CL-2238 PIURA OESTE",
                                "CL2239 CHICLAYO OESTE",
                                "CL-2239 LA NIÑA",
                                "CL2240 CHICLAYO OESTE",
                                "CL-2241 LA NIÑA",
                                "CL-2241 PIURA OESTE",
                                "CL2242 VENTANILLA",
                                "CL-2242 ZAPALLAL",
                                "CL2243 VENTANILLA",
                                "CL-2243 ZAPALLAL",
                                "CL2244 CHAVARRÍA",
                                "CL2244 VENTANILLA",
                                "CL2245 CHAVARRÍA",
                                "CL2245 VENTANILLA",
                                "CL2246 CHAVARRÍA",
                                "CL2246 VENTANILLA",
                                "CL-2248 PIURA OESTE",
                                "CL-2249 ZORRITOS",
                                "CL-2250 SE PIURA",
                                "CL-2250 SE TALARA",
                                "CL2251 AGUAYTÍA",
                                "CL2251 TINGO MARÍA",
                                "CL2252 TINGO MARÍA",
                                "CL2252 VIZCARRA",
                                "CL-2253 CONOCOCHA",
                                "CL2253 VIZCARRA",
                                "CL2254 PARAGSHA 2",
                                "CL2254 VIZCARRA",
                                "CL2258 CARHUAMAYO NUEVA",
                                "CL2258 PARAGSHA 2",
                                "CL2259 CARHUAMAYO NUEVA",
                                "CL2259 OROYA NUEVA",
                                "CL-2260 CAJAMARCA NORTE",
                                "CL-2260 TRUJILLO NORTE",
                                "CL-2264 CONOCOCHA",
                                "CL-2264 PARAGSHA 2",
                                "CL2265 CARHUAMAYO NUEVA",
                                "CL2265 SANTA ISABEL",
                                "CL-2267 CARHUAMAYO NUEVA",
                                "CL-2267 PARAGSHA 2",
                                "CL-2268 CARHUAMAYO NUEVA",
                                "CL-2268 PARAGSHA 2",
                                "CL-2269 CONOCOCHA",
                                "CL-2270 CONOCOCHA",
                                "CL-2272 CAJAMARCA NORTE",
                                "CL-2274 CAJAMARCA NORTE",
                                "CL-2278 CONOCOCHA",
                                "CL2278 PARAMONGA NUEVA",
                                "CL2279 HUACHO",
                                "CL-2280 ZORRITOS",
                                "CL-2292 MARCONA",
                                "CL-2292 POROMA",
                                "CL-2293 MARCONA",
                                "CL-2293 POROMA",
                                "CL-2294 CARHUAMAYO",
                                "CL-2294 POMACOCHA",
                                "CL-5001 CARABAYLLO",
                                "CL-5001 CHILCA-CTM",
                                "CL-5006 SE CARABAYLLO",
                                "CL-5006 SE CHIMBOTE1",
                                "CL-5008 CHIMBOTE 500",
                                "CL-5008 TRUJILLO 500",
                                "CL-5010 LA NIÑA",
                                "CL-5010 TRUJILLO",
                                "CL-5032 CHILCA CTM",
                                "CL-5032 POROMA",
                                "CL-5034 OCOÑA",
                                "CL-5034 POROMA",
                                "CL-5036 MONTALVO",
                                "CL-5036 OCOÑA",
                                "CL-6520 PARAGSHA 1",
                                "ABANCAY T 138/60/13,2kV",
                                "ACEROS AREQUIPA 4 AT-250",
                                "ACEROS AREQUIPA TR4",
                                "ACEROS AREQUIPA TR3",
                                "ACEROS AREQUIPA TR-TA",
                                "ACEROS AREQUIPA TR2",
                                "ACEROS AREQUIPA TR1",
                                "AGUAYTÍA T38-211",
                                "ALAMBRÓN 4TP-405",
                                "ALTO AGUA LIMA T34-31",
                                "ALTO CHICAMA TR-1 138/13.8kV",
                                "ALTO CHICAMA TR-2 138/13.8kV",
                                "ANDAHUAYLAS TR-MT95",
                                "ANDAYCHAGUA TR-AND",
                                "ANDAYCHAGUA ELC 4TP-410",
                                "ANIMÓN T-1",
                                "ANTAMINA T - 1",
                                "ANTAMINA T - 2",
                                "ANTAMINA T - 3",
                                "ARES TP 138/66/22.9",
                                "ARICOTA 2 T-AT2",
                                "AUCAYACU T65-11",
                                "AUCAYACU T28-162",
                                "AYACUCHO 4TP-202",
                                "AYAVIRI T49-121",
                                "AZÁNGARO T50-162",
                                "AZÁNGARO T79-121",
                                "AZULCOCHA T-3 MVA",
                                "BALNEARIOS TR5 220/60 KV",
                                "BALNEARIOS TR2 220/60",
                                "BALNEARIOS TR4 220/60 KV",
                                "BALNEARIOS TR3_220/60",
                                "BARSI T1 220/60/10",
                                "BARSI T2 220/60/10",
                                "BARSI T3 220/60/10",
                                "BELLA UNIÓN T56-621",
                                "BELLAVISTA TP-1311",
                                "BELLAVISTA TP-1314",
                                "BELLAVISTA - SGB T-T63A",
                                "BELLAVISTA - SGB T-T63B",
                                "BOTIFLACA (CUAJONE) BT1",
                                "BOTIFLACA (CUAJONE) BT2",
                                "BOTIFLACA (CUAJONE) BT3",
                                "BOTIFLACA (CUAJONE) BT4",
                                "BOTIFLACA (CUAJONE) BT5",
                                "BOTIFLACA (CUAJONE) BT7",
                                "BOTIFLACA (CUAJONE) BT8",
                                "CACHIMAYO TR-1",
                                "CACHIMAYO TR-4",
                                "CACHIMAYO TR-3",
                                "CACHIMAYO TR-2",
                                "CAJAMARCA NORTE TP-B001",
                                "CAJAMARCA NORTE T-36",
                                "CAJAMARCA NORTE T-601",
                                "CAJAMARQUILLA TR-3",
                                "CAJAMARQUILLA TR-1",
                                "CAJAMARQUILLA TR-2",
                                "CALCA TR-T49",
                                "CALLAHUANCA (EDG) T 220/60/10kV",
                                "CALLALLI T91-162",
                                "CAMANÁ T 138/60/33kV",
                                "CANGALLO 4AT-202",
                                "CARABAYLLO T73-523",
                                "CARABAYLLO T74-523",
                                "CARHUAMAYO TR 138/50/12.6",
                                "CARHUAMAYO 4TP-906",
                                "CARHUAMAYO NUEVA AUT-201",
                                "CARHUAQUERO 2TPB011",
                                "CASA DE FUERZA TR-1",
                                "CASA DE FUERZA TR-2",
                                "CASA DE FUERZA TR-3",
                                "CASERÍO TR-AT7",
                                "CASMA T-138/22.9/10",
                                "CAYALTÍ TR-2TP009",
                                "CELENDÍN TR-7MVA",
                                "CENTRAL SOLAR TACNA TR-5",
                                "CERRO CORONA TR1",
                                "CERRO CORONA TR2",
                                "CERRO CORONA TR3",
                                "CHALLAHUAYA TR-AT11",
                                "CHALLAPAMPA T7-31",
                                "CHANCHAMAYO 4TP-704",
                                "CHAPRÍN 4TP-918",
                                "CHAPRÍN TR-002",
                                "CHAPRÍN TR-001",
                                "CHARCANI 123 T10-1",
                                "CHAVARRÍA T2 220/60/10",
                                "CHAVARRÍA T1 220/60/10",
                                "CHAVARRÍA T3 220/60/10",
                                "CHAVARRÍA T4 220/60/10",
                                "CHICLAYO NORTE TR-2TP003",
                                "CHICLAYO NORTE TR-2TP004",
                                "CHICLAYO OESTE T24-61",
                                "CHICLAYO OESTE T14-260",
                                "CHICLAYO OESTE T16-260",
                                "CHICLAYO OESTE T93-261",
                                "CHICLAYO OESTE TR-2TP002",
                                "CHICLAYO OESTE TR-2TP001",
                                "CHILCA-CTM AT72-523",
                                "CHILINA T31-31",
                                "CHILINA T32-31",
                                "CHILLON TR1",
                                "CHILLON TR2",
                                "CHIMAY T 220/13.8/13.8",
                                "CHIMBOTE 1 TR1-13,8kV",
                                "CHIMBOTE 1 T30-211",
                                "CHIMBOTE 1 T11-211",
                                "CHIMBOTE 1 TR1000KVA",
                                "CHIMBOTE 1 TR500 C.P.",
                                "CHIMBOTE 2 TR1",
                                "CHIMBOTE 2 TR2",
                                "CHIMBOTE 500 AT84-523",
                                "CHIMBOTE NORTE T 138/13.8",
                                "CHUCARAPI T38-31",
                                "CHUQUIBAMBILLA TR-MT94",
                                "COBRIZA I T 220/69/10",
                                "COMBAPATA T46-162",
                                "CONCEPCIÓN 4TP-016",
                                "CONDORCOCHA AT1",
                                "CONDORCOCHA T1",
                                "CONDORCOCHA T2",
                                "CONDORCOCHA T3",
                                "CONDORCOCHA T4",
                                "CONO NORTE T8-31",
                                "CT YANAPAMPA TP-01",
                                "DESIERTO TR-01",
                                "DESIERTO TR-03",
                                "DOLORESPATA TR1-138/11.5",
                                "DOLORESPATA TR2-138/11.5",
                                "DOLORESPATA TR3-138/11.5",
                                "EL AYRO TR-AT13",
                                "EL PLATANAL TR-1",
                                "EL PLATANAL TR-2",
                                "GALLITO CIEGO TG-1",
                                "GALLITO CIEGO TG-2",
                                "GERA I TP-601",
                                "GOYLLAR 4TP-908",
                                "GUADALUPE T92-261",
                                "GUADALUPE T13-261",
                                "GUADALUPE T17-261",
                                "HIDROMETALURGICA TR 1",
                                "HUACHIPA TR-1",
                                "HUACHIPA TR-2",
                                "HUACHO T34-261",
                                "HUACHO T94-261",
                                "HUALLANCA T-11",
                                "HUALLANCA T-63",
                                "HUALLANCA NUEVA T1",
                                "HUANCAVELICA T61-261",
                                "HUANCAVELICA T9-261",
                                "HUANCAVELICA NORTE 4TP-602",
                                "HUANCHOR TR-2",
                                "HUANCHOR TR-1",
                                "HUANTA 4TP-204",
                                "HUÁNUCO T57-121",
                                "HUÁNUCO T26-11",
                                "HUÁNUCO T55-21",
                                "HUARANGAL T 220/60kV",
                                "HUARO TR-HT1",
                                "HUAYUCACHI T61-261",
                                "HUAYUCACHI T19-261",
                                "HUAYUCACHI T8-261",
                                "ICA T59-261",
                                "ICA T5-261",
                                "ILO-ELECTROSUR T-1",
                                "INDEPENDENCIA T3-261",
                                "INDEPENDENCIA T4-261",
                                "INDEPENDENCIA T-30",
                                "JESÚS T5-31",
                                "JUANJUI T 138/22.9/10",
                                "JULIACA T63-121",
                                "JULIACA T51-161",
                                "JUNÍN 4AT-404",
                                "KIMAN AYLLU AUT-501",
                                "LA CURVA T37-31",
                                "LA NIÑA T77-212",
                                "LA NIÑA T78-212",
                                "LA NIÑA AT91-523",
                                "LA PAJUELA T 60",
                                "LA YARADA T-ET6",
                                "LA YARADA T-ET7",
                                "LLACUABAMBA TR 138/22.9",
                                "LOS HÉROES TR-1",
                                "MACHAHUAY 4TP-212",
                                "MACHALA ATR",
                                "MACHALA ATQ",
                                "MACHALA TRK",
                                "MACHUPICCHU T-6",
                                "MAJES T95-161",
                                "MALACAS T20-21",
                                "MÁNCORA T60-2291",
                                "MARCONA T6-261",
                                "MARCONA T62-261",
                                "MATARANI T35-31",
                                "MATUCANA T 220/12.5/12.5",
                                "MAZUKO T-10MVA",
                                "MEJÍA T36-31",
                                "MILL SITE (TOQUEPALA) T1 138/13.8 kV",
                                "MILL SITE (TOQUEPALA) T2 138/13.8 kV",
                                "MILL SITE (TOQUEPALA) T3 138/13.8 kV",
                                "MIRADOR 220 TR-1",
                                "MOLLENDO T80-3",
                                "MOLLENDO T30-163",
                                "MONTALVO AUT-5671",
                                "MOQUEGUA MT1",
                                "MOQUEGUA MT2",
                                "MOQUEGUA_ELS ET1 138/10 kV",
                                "MOTIL T-138/34.5/7.18",
                                "MOTUPE TR-2TP005",
                                "MOYOBAMBA TP-1331",
                                "NEPEÑA T 138/13.8",
                                "NINATAMBO (TARMA) 4TP-406",
                                "NUEVA CAJAMARCA TP-607",
                                "NUEVA JAEN T-138/60/22.9kV",
                                "OROPESA TR-OT1",
                                "OROYA NUEVA T1-138/50 kV",
                                "OROYA NUEVA T-220/50 kV",
                                "OROYA NUEVA T2-138/50 kV",
                                "OXAPAMPA 4TP-702",
                                "PACHACAYO 4TP-030",
                                "PAMPAS 4TP-603",
                                "PARAGSHA 1 TR1 138/50/12",
                                "PARAGSHA 1 TR2 138/50/12",
                                "PARAGSHA 2 T37-211",
                                "PARAMONGA EXISTENTE TR1",
                                "PARAMONGA EXISTENTE TR2",
                                "PARAMONGA NUEVA T10-216",
                                "PARAMONGA NUEVA T18-261",
                                "PEDREGAL SOLAR TR",
                                "PÍAS 1 TP-A047",
                                "PIEDRA BLANCA TP-01",
                                "PIERINA T 138/10",
                                "PISAQ TR-T50",
                                "PIURA TR-1",
                                "PIURA TR-2",
                                "PIURA OESTE T83-261",
                                "PIURA OESTE T15-261",
                                "PIURA OESTE T32-261",
                                "POMALCA TR-2TP008",
                                "POROMA AUT-5371",
                                "PORONGOCHE T14-31",
                                "PORVENIR T 138/10",
                                "PQUE. INDUSTRIAL_AREQUIPA T41-31",
                                "PQUE. INDUSTRIAL_AREQUIPA T42-31",
                                "PQUE. INDUSTRIAL_HUANCAYO 4TP-002",
                                "PQUE. INDUSTRIAL_HUANCAYO 4TP-004",
                                "PQUE. INDUSTRIAL_HUANCAYO 4TP-006",
                                "PQUE. INDUSTRIAL_TACNA T-ET5",
                                "PQUE. INDUSTRIAL_TACNA PQ. TACN10.5",
                                "PQUE. INDUSTRIAL_TACNA PQ. TACN66",
                                "PTO MALDONADO T-138/22,9/10",
                                "PUCALLPA T39-161",
                                "PUNO T97-162",
                                "PUNO T53-162",
                                "PUNO AT-1",
                                "QUENCORO T80-131",
                                "QUENCORO T47-131",
                                "QUILLABAMBA TR",
                                "RACCHI TR-T47",
                                "REPARTICIÓN T26-121",
                                "RIOJA TP-602035",
                                "RIOJA TP-602045",
                                "S.E. SAN CAMILO TR",
                                "SAN JACINTO T 138/13.8",
                                "SAN JOSÉ T-2",
                                "SAN JUAN T1-261",
                                "SAN JUAN TRAFO",
                                "SAN JUAN TR2_220/60",
                                "SAN JUAN TR1_220/60",
                                "SAN RAFAEL T-1 138/10",
                                "SANTA T-138/13.8",
                                "SANTA ROSA N. TR3 220/60",
                                "SANTA ROSA N. TR4 220/60",
                                "SANTA ROSA N. T1 220/60/10",
                                "SANTA ROSA N. T2 220/60/10",
                                "SANTIAGO DE CAO T-138/34.5/13.8",
                                "SIHUAS TR 138/60/22.9",
                                "SOCABAYA T40-13",
                                "SOCABAYA T41-13",
                                "SOCABAYA ATR1",
                                "SOCABAYA ATR2",
                                "SOCABAYA T88-22",
                                "SULFUROS TR 1",
                                "SULFUROS TR 2",
                                "SULFUROS TR 3",
                                "TALARA T20-21",
                                "TARAPOTO TP-1301",
                                "TARATA TR-AT12",
                                "TAYABAMBA TR 138/23",
                                "TINGO MARÍA T69-11",
                                "TINGO MARÍA AT82-211",
                                "TINGO MARÍA AT-01",
                                "TINTAYA T67-11",
                                "TINTAYA T43-11",
                                "TINTAYA T44-11",
                                "TINTAYA AT 220/138 kV",
                                "TINTAYA T45-11",
                                "TOCACHE T66-121",
                                "TOCACHE T35-121",
                                "TORRE 8 TR1",
                                "TORRE 8 TR2",
                                "TRAPECIO TPA007",
                                "TRUJILLO NORTE T1",
                                "TRUJILLO NORTE T2",
                                "TRUJILLO NORTE CL-TN9",
                                "TRUJILLO NORTE T81-121",
                                "TRUJILLO NORTE AT12-211",
                                "TRUJILLO NORTE AT31-211",
                                "TRUJILLO NORTE T29-121",
                                "TRUJILLO NORTE AT99-212",
                                "TRUJILLO NUEVA AT85-523",
                                "TRUJILLO SUR TP-A026",
                                "TRUJILLO SUR TP-A050",
                                "TRUJILLO SUR TP-A005",
                                "TUMÁN TR-2TP010",
                                "URUBAMBA TR-T48",
                                "VIRÚ T 138/10",
                                "VIZCARRA T 220/16",
                                "YANACOCHA TR 220/60",
                                "YAUPI 4TP-912",
                                "YURA T-138/30/4.16kV",
                                "ZORRITOS T33-261",
                                "AGUAYTÍA CL-T38-211",
                                "AUCAYACU CL_T28-162",
                                "AYAVIRI CL_T49_10kV",
                                "AYAVIRI CL_T49_138kV",
                                "AYAVIRI CL_T49_22.9kV",
                                "AZÁNGARO CL_T50_138kV",
                                "AZÁNGARO CL_T50_22.9kV",
                                "AZÁNGARO CL_T50_60kV",
                                "AZÁNGARO CL_T79_22.9kV",
                                "AZÁNGARO CL_T79_60kV",
                                "CACHIMAYO CL-TR1_20MVA",
                                "CACHIMAYO CL-TR2_20MVA",
                                "CACHIMAYO CL-TR_15MVA",
                                "CACHIMAYO CL-TR_6MVA",
                                "CAJAMARCA NORTE CL-T-36",
                                "CAJAMARCA NORTE CL_T-601",
                                "CALLALLI CL-TR_15MVA",
                                "CAÑETE T-601",
                                "CARABAYLLO CL-TR73",
                                "CARABAYLLO CL-TR73",
                                "CARABAYLLO CL-TR74",
                                "CARABAYLLO CL-TR74",
                                "CARHUAMAYO CL-TRAFO 30 MVA",
                                "CARHUAMAYO CL-TRAFO 7MVA",
                                "CARHUAMAYO NUEVA CL-AUT201",
                                "CHAVARRÍA CL-TR01",
                                "CHAVARRÍA CL-TR02",
                                "CHAVARRÍA CL-TR03",
                                "CHAVARRÍA CLTR1-220/60/10",
                                "CHAVARRÍA CLTR4-220/60/10",
                                "CHAVARRÍA CLTR2-220/60/10",
                                "CHAVARRÍA CLTR3-220/60/10",
                                "CHICLAYO OESTE CL_T14-260",
                                "CHICLAYO OESTE CL_T16-260",
                                "CHILCA-CTM CL-T72_220kV",
                                "CHILCA-CTM CL-T72_500kV",
                                "CHILLON CL-TR1",
                                "CHIMBOTE 1 CL-T30_220kV",
                                "CHIMBOTE 1 CL-T11-138kV",
                                "CHIMBOTE 1 CL-T30_138kV",
                                "COMBAPATA CL_T46-162",
                                "DESIERTO CL-TR 20/20/8.3",
                                "GUADALUPE CL_T13-261",
                                "GUADALUPE CL_T17-261",
                                "HUACHO CL_T34-261",
                                "HUACHO CL-TR94",
                                "HUANCAVELICA CL_T9-261",
                                "HUÁNUCO CL_T26-11",
                                "HUARANGAL CLTR1-220/60",
                                "HUAYUCACHI CL_T19-261",
                                "HUAYUCACHI CL_T8-261",
                                "ICA CL-TR05",
                                "ICA CL-TR59",
                                "INDEPENDENCIA CL_T3-261",
                                "INDEPENDENCIA CL_T4-261",
                                "JULIACA CL_T51-161",
                                "JULIACA CL_T63_10kV",
                                "JULIACA CL_T63_138kV",
                                "JULIACA CL_T63_22.9kV",
                                "KIMAN AYLLU CL-AUT-501",
                                "MARCONA CL-TR62",
                                "MARCONA CL-TR06",
                                "MONTALVO CL-AUT-5671_220",
                                "MONTALVO CL-AUT-5671_500",
                                "OROYA NUEVA CL-TR 100MVA",
                                "PARAGSHA 2 CL-T37-211",
                                "PARAMONGA NUEVA CL_T10-216",
                                "PARAMONGA NUEVA CL_T18-261",
                                "PIURA OESTE CL_T15-261",
                                "PIURA OESTE CL_T32-261",
                                "POROMA CL-AUT-5371_500",
                                "POROMA CL-AUT-5371_220",
                                "PUCALLPA CL-T39-161",
                                "PUNO CL_T53-162",
                                "PUNO CL_T68_138kV",
                                "PUNO CL_T68_22kV",
                                "PUNO CL_T68_60kV",
                                "QUENCORO CL_T47-131",
                                "QUENCORO CL_T48-136",
                                "QUENCORO CL_T80_10kV",
                                "QUENCORO CL_T80_138kV",
                                "QUENCORO CL_T80_34kV",
                                "REPARTICIÓN CL_TR-7MVA",
                                "SAN JUAN CL-TR1",
                                "SAN JUAN CL-TR2",
                                "SAN JUAN CL_T1-261",
                                "SAN JUAN CL-TR2_60kV",
                                "SANTA ROSA N. CL-TR3",
                                "SANTA ROSA N. CL-TR4",
                                "SANTA ROSA N. CLTR1-220/60/10",
                                "SANTA ROSA N. CLTR2-220/60/10",
                                "SOCABAYA CL_T40-13",
                                "SOCABAYA CL_T41-13",
                                "SOCABAYA CL_TR-10MVA",
                                "TALARA CL-T20-21",
                                "TINTAYA CL_T43-11",
                                "TINTAYA CL_T44-11",
                                "TINTAYA CL_T67_10kV",
                                "TINTAYA CL_T67_138kV",
                                "TINTAYA CL_TZ3",
                                "TOCACHE CL_T35-121",
                                "TRUJILLO 500 CL AT85-523_500",
                                "TRUJILLO NORTE CL_AT12-211",
                                "TRUJILLO NORTE CL_AT99-212",
                                "TRUJILLO NORTE CL_AT31-211",
                                "TRUJILLO NUEVA CL AT85-523_220",
                                "ZORRITOS CT33-261",
                                "AGUAYTIA CENTRAL",
                                "ARCATA CH",
                                "ARICOTA I CENTRAL",
                                "ARICOTA II CENTRAL",
                                "BELLAVISTA CENTRAL1",
                                "CAHUA CENTRAL",
                                "CALLAHUANCA1 CENTRAL",
                                "CALLAHUANCA2 CENTRAL",
                                "CALLAHUANCA34 CENTRAL",
                                "MANTARO CENTRAL",
                                "CAÑA BRAVA CENTRAL",
                                "CAÑON DEL PATO CENTRAL",
                                "CARHUAQUERO CENTRAL",
                                "CENTRAL RESE-ILO",
                                "CHARCANI I CENTRAL",
                                "CHARCANI II CENTRAL",
                                "CHARCANI III CENTRAL",
                                "CHARCANI IV CENTRAL",
                                "CHARCANI V CENTRAL",
                                "CHARCANI VI CENTRAL",
                                "CHILCA CENTRAL",
                                "CHIMAY CENTRAL",
                                "EL PLATANAL CENTRAL",
                                "FENIX CENTRAL",
                                "GALLITO CIEGO CENTRAL",
                                "HUAMPANI CENTRAL",
                                "HUANCHOR CENTRAL",
                                "HUANZA CENTRAL",
                                "HUAYLLACHO CENTRAL",
                                "HUINCO CENTRAL",
                                "ILO 1 CENTRAL",
                                "ILO 2 CENTRAL",
                                "INDEPENDENCIA CENTRAL",
                                "KALLPA CENTRAL",
                                "LAS FLORES CENTRAL",
                                "LAS PIZARRAS CENTRAL",
                                "MACHUPICCHU CENTRAL",
                                "MALACAS CENTRAL",
                                "MALPASO CENTRAL",
                                "MANTARO CENTRAL",
                                "MATUCANA CENTRAL",
                                "MISAPUQUIO CENTRAL",
                                "MOLLENDO D CENTRAL",
                                "MOYOPAMPA CENTRAL",
                                "OLLEROS CENTRAL",
                                "OQUENDO CENTRAL",
                                "OROYA CENTRAL",
                                "PACHACHACA CENTRAL",
                                "PARIAC CENTRAL",
                                "PISCO CENTRAL",
                                "RESTITUCION CENTRAL",
                                "SAN ANTONIO CENTRAL",
                                "SAN GABAN II CENTRAL",
                                "SAN IGNACIO CENTRAL",
                                "SAN NICOLAS CENTRAL",
                                "STA ROSA  CENTRAL",
                                "TABLAZO CENTRAL",
                                "TAPARACHI CENTRAL",
                                "TUMBES CENTRAL",
                                "VENTANILLA CENTRAL",
                                "YANANGO CENTRAL",
                                "YAUPI CENTRAL",
                                "YUNCAN CENTRAL",
                                "AGUAYTIA TG1",
                                "AGUAYTIA TG2",
                                "ARICOTA I G1",
                                "ARICOTA I G2",
                                "ARICOTA II G1",
                                "BELLAVISTA ALCO",
                                "CAHUA G1",
                                "CAHUA G2",
                                "CALLAHUANCA1 G1",
                                "CALLAHUANCA2 G2",
                                "CALLAHUANCA34 G3",
                                "CALLAHUANCA34 G4",
                                "CAÑA BRAVA G1",
                                "CAÑON DEL PATO G1",
                                "CAÑON DEL PATO G2",
                                "CAÑON DEL PATO G3",
                                "CAÑON DEL PATO G4",
                                "CAÑON DEL PATO G5",
                                "CAÑON DEL PATO G6",
                                "CARHUAQUERO G1",
                                "CARHUAQUERO G2",
                                "CARHUAQUERO G3",
                                "CARHUAQUERO G4",
                                "CENTRAL RESE-ILO-TG1",
                                "CENTRAL RESE-ILO-TG2",
                                "CENTRAL RESE-ILO-TG3",
                                "CHARCANI I G1",
                                "CHARCANI I G2",
                                "CHARCANI II G1",
                                "CHARCANI II G2",
                                "CHARCANI II G3",
                                "CHARCANI III G1",
                                "CHARCANI III G2",
                                "CHARCANI IV G1",
                                "CHARCANI IV G2",
                                "CHARCANI IV G3",
                                "CHARCANI V G1",
                                "CHARCANI V G2",
                                "CHARCANI V G3",
                                "CHARCANI VI G1",
                                "CHILCA TG1",
                                "CHILCA TG2",
                                "CHILCA TG3",
                                "CHILCA TV",
                                "CHILINA D SLZ1",
                                "CHILINA D SLZ2",
                                "CHILINA TG",
                                "CHILINA TV1",
                                "CHILINA TV2",
                                "CHILINA TV3",
                                "CHIMAY G1",
                                "CHIMAY G2",
                                "EL PLATANAL G1",
                                "EL PLATANAL G2",
                                "FENIX  TG11",
                                "FENIX  TG12",
                                "FENIX  TV10",
                                "GALLITO CIEGO G1",
                                "GALLITO CIEGO G2",
                                "HUAMPANI G1",
                                "HUAMPANI G2",
                                "HUANCHOR G1",
                                "HUANCHOR G2",
                                "HUANZA G1",
                                "HUANZA G2",
                                "HUAYLLACHO G1",
                                "HUINCO1 G1",
                                "HUINCO2 G2",
                                "HUINCO3 G3",
                                "HUINCO4 G4",
                                "ILO 1 CAT",
                                "ILO 1 TG1",
                                "ILO 1 TG2",
                                "ILO 1 TV3",
                                "ILO 1 TV4",
                                "ILO 2 TG1",
                                "ILO 2 TG2",
                                "ILO 2 TG3",
                                "ILO 2 TV21",
                                "INDEPENDENCIA G1",
                                "INDEPENDENCIA G2",
                                "INDEPENDENCIA G3",
                                "INDEPENDENCIA G4",
                                "KALLPA TG1",
                                "KALLPA TG2",
                                "KALLPA TG3",
                                "KALLPA TV",
                                "LAS FLORES TG1",
                                "LAS PIZARRAS G1",
                                "LAS PIZARRAS G2",
                                "MACHUPICCHU G1",
                                "MACHUPICCHU G2",
                                "MACHUPICCHU G3",
                                "MALACAS TG4",
                                "MALACAS TG5",
                                "MALPASO G1",
                                "MALPASO G2",
                                "MALPASO G3",
                                "MALPASO G4",
                                "MANTARO G1",
                                "MANTARO G2",
                                "MANTARO G3",
                                "MANTARO G4",
                                "MANTARO G5",
                                "MANTARO G6",
                                "MANTARO G7",
                                "MATUCANA G1",
                                "MATUCANA G2",
                                "MISAPUQUIO G1",
                                "MISAPUQUIO G2",
                                "MOLLENDO D GD1",
                                "MOLLENDO D GD2",
                                "MOLLENDO D GD3",
                                "MOYOPAMPA G1",
                                "MOYOPAMPA G2",
                                "MOYOPAMPA G3",
                                "OLLEROS TG1",
                                "OQUENDO TG1",
                                "OROYA G1",
                                "OROYA G2",
                                "OROYA G3",
                                "PACHACHACA G1",
                                "PACHACHACA G2",
                                "PACHACHACA G3",
                                "PARIAC CH-1",
                                "PARIAC CH-2",
                                "PARIAC CH-3A",
                                "PARIAC CH-3N",
                                "PARIAC CH-4 I",
                                "PARIAC CH-4 II",
                                "PISCO TG1",
                                "PISCO TG2",
                                "RESTITUCION G1",
                                "RESTITUCION G2",
                                "RESTITUCION G3",
                                "SAN ANTONIO G1",
                                "SAN GABAN II G1",
                                "SAN GABAN II G2",
                                "SAN IGNACIO G1",
                                "SAN NICOLAS CAL1",
                                "SAN NICOLAS CAL2",
                                "SAN NICOLAS CAL3",
                                "SAN NICOLAS CUMMINS",
                                "SAN NICOLAS TV1",
                                "SAN NICOLAS TV2",
                                "SAN NICOLAS TV3",
                                "STA ROSA UTI UTI5",
                                "STA ROSA UTI UTI6",
                                "STA ROSA TG7",
                                "STA ROSA TG8",
                                "TABLAZO TG1",
                                "TAPARACHI MAN1",
                                "TAPARACHI MAN3",
                                "TAPARACHI MAN4",
                                "TAPARACHI SKD1",
                                "TUMBES MAK1",
                                "TUMBES MAK2",
                                "VENTANILLA TG3",
                                "VENTANILLA TG4",
                                "YANANGO G1",
                                "YAUPI G1",
                                "YAUPI G2",
                                "YAUPI G3",
                                "YAUPI G4",
                                "YAUPI G5",
                                "YUNCAN G-1",
                                "YUNCAN G-2",
                                "YUNCAN G-3"
                            };

            return list.ToList();
        }

        /// <summary>
        /// Lista validacion para celda
        /// </summary>
        /// <returns></returns>
        public static List<string> ListarCondicion()
        {
            string[] list = { "X" };
            return list.ToList();
        }

        /// <summary>
        /// Permite obtener lista de SI y NO
        /// </summary>
        /// <returns></returns>
        public static List<string> ListaSiNo()
        {
            string[] list = { "SI", "NO" };
            return list.ToList();
        }

        public static List<string> ListaSorteo()
        {
            string[] list = { "No se inicia el proceso", "Se cargó la situación operativa a Extranet Osinerg", "Se realizó el sorteo", "Se cargó el resultado a Extranet Osinerg", "Se envió el resultado a los Integrantes" };
            return list.ToList();
        }

        public static List<string> ListaResultadoSorteo()
        {
            string[] list = { "Blanca", "Negra" };
            return list.ToList();
        }

        public static List<string> ListaPruebaSorteo()
        {
            string[] list = { "Orden de arranque", "Inicio de pruebas", "Finalización de pruebas (incluido rearranque)", "Se cargó el reporte de generación a Extranet Osinerg" };
            return list.ToList();
        }


        /// <summary>
        /// Permite generar el documento excel con los datos de los usuarios
        /// </summary>
        /// <param name="list"></param>
        /// <param name="path"></param>
        /// <param name="file"></param>
        public static void GenerarReporteSupervisionDemandaExcel(string[][] list, string path, string filename)
        {
            try
            {
                string file = path + filename;
                FileInfo newFile = new FileInfo(file);

                if (newFile.Exists)
                {
                    newFile.Delete();
                    newFile = new FileInfo(file);
                }

                using (ExcelPackage xlPackage = new ExcelPackage(newFile))
                {
                    ExcelWorksheet ws = xlPackage.Workbook.Worksheets.Add("DATOS");

                    if (ws != null)
                    {
                        ws.Cells[2, 3].Value = "SUPERVSION DE LA DEMANDA";

                        ExcelRange rg = ws.Cells[2, 3, 3, 3];
                        rg.Style.Font.Size = 13;
                        rg.Style.Font.Bold = true;

                        int index = 5;
                        int column = 2;

                        foreach (string[] elemento in list)
                        {
                            column = 2;
                            foreach (string item in elemento)
                            {
                                if (column > 2 && index > 7)
                                {
                                    ws.Cells[index, column].Value = (!string.IsNullOrEmpty(item)) ? (decimal?)decimal.Parse(item) : null;
                                }
                                else
                                {
                                    ws.Cells[index, column].Value = item;
                                }

                                column++;
                            }
                            index++;
                        }

                        rg = ws.Cells[5, 2, 7, column];
                        rg.Style.HorizontalAlignment = ExcelHorizontalAlignment.Center;
                        rg.Style.Fill.PatternType = ExcelFillStyle.Solid;
                        rg.Style.Fill.BackgroundColor.SetColor(ColorTranslator.FromHtml("#2980B9"));
                        rg.Style.Font.Color.SetColor(Color.White);
                        rg.Style.Font.Size = 10;
                        rg.Style.Font.Bold = true;                                              

                        rg = ws.Cells[8, 2, index - 1, column];
                        rg.Style.Border.Left.Style = ExcelBorderStyle.Thin;
                        rg.Style.Border.Left.Color.SetColor(ColorTranslator.FromHtml("#9F9F9F"));
                        rg.Style.Border.Right.Style = ExcelBorderStyle.Thin;
                        rg.Style.Border.Right.Color.SetColor(ColorTranslator.FromHtml("#9F9F9F"));
                        rg.Style.Border.Top.Style = ExcelBorderStyle.Thin;
                        rg.Style.Border.Top.Color.SetColor(ColorTranslator.FromHtml("#9F9F9F"));
                        rg.Style.Border.Bottom.Style = ExcelBorderStyle.Thin;
                        rg.Style.Border.Bottom.Color.SetColor(ColorTranslator.FromHtml("#9F9F9F"));

                        ws.Column(2).Width = 30;
                        rg = ws.Cells[5, 3, index, column];
                        rg.AutoFitColumns();

                        HttpWebRequest request = (HttpWebRequest)System.Net.HttpWebRequest.Create(ConfigurationManager.AppSettings["LogoCoes"].ToString());
                        HttpWebResponse response = (HttpWebResponse)request.GetResponse();
                        System.Drawing.Image img = System.Drawing.Image.FromStream(response.GetResponseStream());
                        ExcelPicture picture = ws.Drawings.AddPicture("Logo", img);
                        picture.From.Column = 1;
                        picture.From.Row = 1;
                        picture.To.Column = 2;
                        picture.To.Row = 2;
                        picture.SetSize(120, 60);
                    }

                    xlPackage.Save();
                }
            }
            catch (Exception ex)
            {
                throw new Exception(ex.Message, ex);
            }
        }
    }

    public class ConstantesCoordinacion
    {      
        public const string FileCambioTurnoXLS = "CambioTurno.xlsx";
        public const string FileCambioTurnoDPF = "CambioTurno.pdf";
        public const string RutaReporte = "/Areas/Coordinacion/Reporte/";
        //-Constantes registro observaciones
        public const string FileExportacionObservacion = "Observacion.xlsx";
        public const string ReporteSupervisionDemanda = "SupervisionDemanda.xlsx";

    }
}