//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COES.Framework.Base {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Consultas {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Consultas() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("COES.Framework.Base.Consultas", typeof(Consultas).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;Sqls&gt;
        ///
        ///  &lt;Sql&gt;
        ///    &lt;key&gt;GetMaxId&lt;/key&gt;
        ///    &lt;query&gt;
        ///      select nvl(max(auditcodi), 0) + 1 as id from si_auditoria
        ///    &lt;/query&gt;
        ///  &lt;/Sql&gt;
        ///&lt;/Sqls&gt;
        ///.
        /// </summary>
        internal static string SiAuditoriaSql {
            get {
                return ResourceManager.GetString("SiAuditoriaSql", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;Sqls&gt;
        ///
        ///  &lt;Sql&gt;
        ///    &lt;key&gt;ListarPorEstadoYTabla&lt;/key&gt;
        ///    &lt;query&gt;
        ///      select tauditconfcolumn, tauditconfindpk from si_tabla_auditable_conf where tauditcodi = {0} and tauditconfindestado = &apos;A&apos;
        ///    &lt;/query&gt;
        ///  &lt;/Sql&gt;
        ///&lt;/Sqls&gt;
        ///.
        /// </summary>
        internal static string SiTablaAuditableConfSql {
            get {
                return ResourceManager.GetString("SiTablaAuditableConfSql", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;Sqls&gt;
        ///
        ///  &lt;Sql&gt;
        ///    &lt;key&gt;GetByCriteria&lt;/key&gt;
        ///    &lt;query&gt;
        ///      select tauditcodi as contador from si_tabla_auditable where lower(tauditnomb) = &apos;{0}&apos;
        ///    &lt;/query&gt;
        ///  &lt;/Sql&gt;
        ///&lt;/Sqls&gt;
        ///.
        /// </summary>
        internal static string SiTablaAuditableSql {
            get {
                return ResourceManager.GetString("SiTablaAuditableSql", resourceCulture);
            }
        }
    }
}
