//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COES.Infraestructura.Datos.Repositorio.Busqueda.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class BCD_Resultados_recomendados
    {
        public int Id_document { get; set; }
        public int Id_search_rr { get; set; }
        public string Index_rowkey { get; set; }
        public string Document_path { get; set; }
        public string Document_name { get; set; }
        public Nullable<decimal> Confidence { get; set; }
        public string Recommend_by { get; set; }
    
        public virtual BCD_Busquedas BCD_Busquedas { get; set; }
    }
}
