//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COES.Infraestructura.Datos.Repositorio.Busqueda.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class BCD_Busquedas
    {
        public BCD_Busquedas()
        {
            this.BCD_Calificacion_busqueda = new HashSet<BCD_Calificacion_busqueda>();
            this.BCD_Conceptos_clave = new HashSet<BCD_Conceptos_clave>();
            this.Documentos_abiertos = new HashSet<Documentos_abiertos>();
            this.BCD_Palabras_clave = new HashSet<BCD_Palabras_clave>();
            this.Resultados_busquedas = new HashSet<Resultados_busquedas>();
            this.BCD_Resultados_recomendados = new HashSet<BCD_Resultados_recomendados>();
            this.Resultados_relacionados = new HashSet<Resultados_relacionados>();
        }
    
        public int Id_search { get; set; }
        public System.DateTime Search_date { get; set; }
        public string Search_user { get; set; }
        public string Search_text { get; set; }
        public string Key_words { get; set; }
        public string Key_concepts { get; set; }
        public int Result_number { get; set; }
        public System.DateTime Search_start_date { get; set; }
        public System.DateTime Search_end_date { get; set; }
        public Nullable<bool> Search_type { get; set; }
        public Nullable<bool> Search_relation { get; set; }
        public string Exclude_words { get; set; }
    
        public virtual ICollection<BCD_Calificacion_busqueda> BCD_Calificacion_busqueda { get; set; }
        public virtual ICollection<BCD_Conceptos_clave> BCD_Conceptos_clave { get; set; }
        public virtual ICollection<Documentos_abiertos> Documentos_abiertos { get; set; }
        public virtual ICollection<BCD_Palabras_clave> BCD_Palabras_clave { get; set; }
        public virtual ICollection<Resultados_busquedas> Resultados_busquedas { get; set; }
        public virtual ICollection<BCD_Resultados_recomendados> BCD_Resultados_recomendados { get; set; }
        public virtual ICollection<Resultados_relacionados> Resultados_relacionados { get; set; }
    }
}
