//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COES.Infraestructura.Datos.Repositorio.Busqueda.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class BCD_Conceptos_clave
    {
        public int Id_kc_suggestion { get; set; }
        public int Id_search_kcs { get; set; }
        public string Key_concept_search { get; set; }
    
        public virtual BCD_Busquedas BCD_Busquedas { get; set; }
    }
}
