//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COES.Infraestructura.Datos.Repositorio.Busqueda.BD
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CSDocDJR : DbContext
    {
        public CSDocDJR()
            : base("name=CSDocDJR")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<BCD_Busquedas> BCD_Busquedas { get; set; }
        public DbSet<BCD_Calificacion_busqueda> BCD_Calificacion_busqueda { get; set; }
        public DbSet<BCD_Conceptos_clave> BCD_Conceptos_clave { get; set; }
        public DbSet<BCD_Palabras_clave> BCD_Palabras_clave { get; set; }
        public DbSet<BCD_Rangos> BCD_Rangos { get; set; }
        public DbSet<BCD_Resultados_recomendados> BCD_Resultados_recomendados { get; set; }
        public DbSet<Documentos_abiertos> Documentos_abiertos { get; set; }
        public DbSet<Resultados_busquedas> Resultados_busquedas { get; set; }
        public DbSet<Resultados_relacionados> Resultados_relacionados { get; set; }
    }
}
