//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COES.Infraestructura.Datos.Repositorio.Busqueda.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Documentos_abiertos
    {
        public int Id_open_document { get; set; }
        public int Id_search_open { get; set; }
        public string Index_rowkey_open { get; set; }
        public string Document_path_open { get; set; }
        public string Document_name_open { get; set; }
        public Nullable<decimal> Confidence_open { get; set; }
        public string Open_by { get; set; }
    
        public virtual BCD_Busquedas BCD_Busquedas { get; set; }
    }
}
