//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COES.Infraestructura.Datos.Repositorio.Busqueda.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Resultados_relacionados
    {
        public int Id_recommend { get; set; }
        public int Id_search_recommend { get; set; }
        public string Index_rowkey_recommend { get; set; }
        public string Document_path_recommend { get; set; }
        public string Document_name_recommend { get; set; }
        public Nullable<decimal> Confidence_recommend { get; set; }
        public string Recommend_for { get; set; }
    
        public virtual BCD_Busquedas BCD_Busquedas { get; set; }
    }
}
