//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COES.MVC.Extranet.ServicioCloud {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResultadoVerificacion", Namespace="http://schemas.datacontract.org/2004/07/Extranet.Cloud.Dominio")]
    [System.SerializableAttribute()]
    public partial class ResultadoVerificacion : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EstadoInformacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EstadoOperativoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaCargaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IndicadorConsistenciaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IndicadorEnvioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PtoMediCodiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal ValorConsistenciaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EstadoInformacion {
            get {
                return this.EstadoInformacionField;
            }
            set {
                if ((object.ReferenceEquals(this.EstadoInformacionField, value) != true)) {
                    this.EstadoInformacionField = value;
                    this.RaisePropertyChanged("EstadoInformacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EstadoOperativo {
            get {
                return this.EstadoOperativoField;
            }
            set {
                if ((object.ReferenceEquals(this.EstadoOperativoField, value) != true)) {
                    this.EstadoOperativoField = value;
                    this.RaisePropertyChanged("EstadoOperativo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaCarga {
            get {
                return this.FechaCargaField;
            }
            set {
                if ((this.FechaCargaField.Equals(value) != true)) {
                    this.FechaCargaField = value;
                    this.RaisePropertyChanged("FechaCarga");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IndicadorConsistencia {
            get {
                return this.IndicadorConsistenciaField;
            }
            set {
                if ((object.ReferenceEquals(this.IndicadorConsistenciaField, value) != true)) {
                    this.IndicadorConsistenciaField = value;
                    this.RaisePropertyChanged("IndicadorConsistencia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IndicadorEnvio {
            get {
                return this.IndicadorEnvioField;
            }
            set {
                if ((object.ReferenceEquals(this.IndicadorEnvioField, value) != true)) {
                    this.IndicadorEnvioField = value;
                    this.RaisePropertyChanged("IndicadorEnvio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PtoMediCodi {
            get {
                return this.PtoMediCodiField;
            }
            set {
                if ((this.PtoMediCodiField.Equals(value) != true)) {
                    this.PtoMediCodiField = value;
                    this.RaisePropertyChanged("PtoMediCodi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal ValorConsistencia {
            get {
                return this.ValorConsistenciaField;
            }
            set {
                if ((this.ValorConsistenciaField.Equals(value) != true)) {
                    this.ValorConsistenciaField = value;
                    this.RaisePropertyChanged("ValorConsistencia");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Medicion", Namespace="http://schemas.datacontract.org/2004/07/Extranet.Cloud.Dominio")]
    [System.SerializableAttribute()]
    public partial class Medicion : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FECHAHORAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal H0Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal H1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal H10Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal H11Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal H12Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal H13Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal H14Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal H15Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal H16Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal H17Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal H18Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal H19Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal H2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal H20Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal H21Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal H22Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal H23Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal H24Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal H25Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal H26Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal H27Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal H28Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal H29Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal H3Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal H30Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal H31Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal H32Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal H33Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal H34Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal H35Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal H36Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal H37Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal H38Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal H39Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal H4Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal H40Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal H41Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal H42Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal H43Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal H44Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal H45Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal H46Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal H47Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal H48Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal H49Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal H5Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal H50Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal H51Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal H52Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal H53Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal H54Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal H55Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal H56Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal H57Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal H58Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal H59Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal H6Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal H7Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal H8Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal H9Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PTOMEDICODIField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TIPOINFOCODIField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FECHAHORA {
            get {
                return this.FECHAHORAField;
            }
            set {
                if ((this.FECHAHORAField.Equals(value) != true)) {
                    this.FECHAHORAField = value;
                    this.RaisePropertyChanged("FECHAHORA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal H0 {
            get {
                return this.H0Field;
            }
            set {
                if ((this.H0Field.Equals(value) != true)) {
                    this.H0Field = value;
                    this.RaisePropertyChanged("H0");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal H1 {
            get {
                return this.H1Field;
            }
            set {
                if ((this.H1Field.Equals(value) != true)) {
                    this.H1Field = value;
                    this.RaisePropertyChanged("H1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal H10 {
            get {
                return this.H10Field;
            }
            set {
                if ((this.H10Field.Equals(value) != true)) {
                    this.H10Field = value;
                    this.RaisePropertyChanged("H10");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal H11 {
            get {
                return this.H11Field;
            }
            set {
                if ((this.H11Field.Equals(value) != true)) {
                    this.H11Field = value;
                    this.RaisePropertyChanged("H11");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal H12 {
            get {
                return this.H12Field;
            }
            set {
                if ((this.H12Field.Equals(value) != true)) {
                    this.H12Field = value;
                    this.RaisePropertyChanged("H12");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal H13 {
            get {
                return this.H13Field;
            }
            set {
                if ((this.H13Field.Equals(value) != true)) {
                    this.H13Field = value;
                    this.RaisePropertyChanged("H13");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal H14 {
            get {
                return this.H14Field;
            }
            set {
                if ((this.H14Field.Equals(value) != true)) {
                    this.H14Field = value;
                    this.RaisePropertyChanged("H14");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal H15 {
            get {
                return this.H15Field;
            }
            set {
                if ((this.H15Field.Equals(value) != true)) {
                    this.H15Field = value;
                    this.RaisePropertyChanged("H15");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal H16 {
            get {
                return this.H16Field;
            }
            set {
                if ((this.H16Field.Equals(value) != true)) {
                    this.H16Field = value;
                    this.RaisePropertyChanged("H16");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal H17 {
            get {
                return this.H17Field;
            }
            set {
                if ((this.H17Field.Equals(value) != true)) {
                    this.H17Field = value;
                    this.RaisePropertyChanged("H17");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal H18 {
            get {
                return this.H18Field;
            }
            set {
                if ((this.H18Field.Equals(value) != true)) {
                    this.H18Field = value;
                    this.RaisePropertyChanged("H18");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal H19 {
            get {
                return this.H19Field;
            }
            set {
                if ((this.H19Field.Equals(value) != true)) {
                    this.H19Field = value;
                    this.RaisePropertyChanged("H19");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal H2 {
            get {
                return this.H2Field;
            }
            set {
                if ((this.H2Field.Equals(value) != true)) {
                    this.H2Field = value;
                    this.RaisePropertyChanged("H2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal H20 {
            get {
                return this.H20Field;
            }
            set {
                if ((this.H20Field.Equals(value) != true)) {
                    this.H20Field = value;
                    this.RaisePropertyChanged("H20");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal H21 {
            get {
                return this.H21Field;
            }
            set {
                if ((this.H21Field.Equals(value) != true)) {
                    this.H21Field = value;
                    this.RaisePropertyChanged("H21");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal H22 {
            get {
                return this.H22Field;
            }
            set {
                if ((this.H22Field.Equals(value) != true)) {
                    this.H22Field = value;
                    this.RaisePropertyChanged("H22");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal H23 {
            get {
                return this.H23Field;
            }
            set {
                if ((this.H23Field.Equals(value) != true)) {
                    this.H23Field = value;
                    this.RaisePropertyChanged("H23");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal H24 {
            get {
                return this.H24Field;
            }
            set {
                if ((this.H24Field.Equals(value) != true)) {
                    this.H24Field = value;
                    this.RaisePropertyChanged("H24");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal H25 {
            get {
                return this.H25Field;
            }
            set {
                if ((this.H25Field.Equals(value) != true)) {
                    this.H25Field = value;
                    this.RaisePropertyChanged("H25");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal H26 {
            get {
                return this.H26Field;
            }
            set {
                if ((this.H26Field.Equals(value) != true)) {
                    this.H26Field = value;
                    this.RaisePropertyChanged("H26");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal H27 {
            get {
                return this.H27Field;
            }
            set {
                if ((this.H27Field.Equals(value) != true)) {
                    this.H27Field = value;
                    this.RaisePropertyChanged("H27");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal H28 {
            get {
                return this.H28Field;
            }
            set {
                if ((this.H28Field.Equals(value) != true)) {
                    this.H28Field = value;
                    this.RaisePropertyChanged("H28");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal H29 {
            get {
                return this.H29Field;
            }
            set {
                if ((this.H29Field.Equals(value) != true)) {
                    this.H29Field = value;
                    this.RaisePropertyChanged("H29");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal H3 {
            get {
                return this.H3Field;
            }
            set {
                if ((this.H3Field.Equals(value) != true)) {
                    this.H3Field = value;
                    this.RaisePropertyChanged("H3");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal H30 {
            get {
                return this.H30Field;
            }
            set {
                if ((this.H30Field.Equals(value) != true)) {
                    this.H30Field = value;
                    this.RaisePropertyChanged("H30");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal H31 {
            get {
                return this.H31Field;
            }
            set {
                if ((this.H31Field.Equals(value) != true)) {
                    this.H31Field = value;
                    this.RaisePropertyChanged("H31");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal H32 {
            get {
                return this.H32Field;
            }
            set {
                if ((this.H32Field.Equals(value) != true)) {
                    this.H32Field = value;
                    this.RaisePropertyChanged("H32");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal H33 {
            get {
                return this.H33Field;
            }
            set {
                if ((this.H33Field.Equals(value) != true)) {
                    this.H33Field = value;
                    this.RaisePropertyChanged("H33");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal H34 {
            get {
                return this.H34Field;
            }
            set {
                if ((this.H34Field.Equals(value) != true)) {
                    this.H34Field = value;
                    this.RaisePropertyChanged("H34");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal H35 {
            get {
                return this.H35Field;
            }
            set {
                if ((this.H35Field.Equals(value) != true)) {
                    this.H35Field = value;
                    this.RaisePropertyChanged("H35");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal H36 {
            get {
                return this.H36Field;
            }
            set {
                if ((this.H36Field.Equals(value) != true)) {
                    this.H36Field = value;
                    this.RaisePropertyChanged("H36");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal H37 {
            get {
                return this.H37Field;
            }
            set {
                if ((this.H37Field.Equals(value) != true)) {
                    this.H37Field = value;
                    this.RaisePropertyChanged("H37");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal H38 {
            get {
                return this.H38Field;
            }
            set {
                if ((this.H38Field.Equals(value) != true)) {
                    this.H38Field = value;
                    this.RaisePropertyChanged("H38");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal H39 {
            get {
                return this.H39Field;
            }
            set {
                if ((this.H39Field.Equals(value) != true)) {
                    this.H39Field = value;
                    this.RaisePropertyChanged("H39");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal H4 {
            get {
                return this.H4Field;
            }
            set {
                if ((this.H4Field.Equals(value) != true)) {
                    this.H4Field = value;
                    this.RaisePropertyChanged("H4");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal H40 {
            get {
                return this.H40Field;
            }
            set {
                if ((this.H40Field.Equals(value) != true)) {
                    this.H40Field = value;
                    this.RaisePropertyChanged("H40");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal H41 {
            get {
                return this.H41Field;
            }
            set {
                if ((this.H41Field.Equals(value) != true)) {
                    this.H41Field = value;
                    this.RaisePropertyChanged("H41");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal H42 {
            get {
                return this.H42Field;
            }
            set {
                if ((this.H42Field.Equals(value) != true)) {
                    this.H42Field = value;
                    this.RaisePropertyChanged("H42");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal H43 {
            get {
                return this.H43Field;
            }
            set {
                if ((this.H43Field.Equals(value) != true)) {
                    this.H43Field = value;
                    this.RaisePropertyChanged("H43");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal H44 {
            get {
                return this.H44Field;
            }
            set {
                if ((this.H44Field.Equals(value) != true)) {
                    this.H44Field = value;
                    this.RaisePropertyChanged("H44");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal H45 {
            get {
                return this.H45Field;
            }
            set {
                if ((this.H45Field.Equals(value) != true)) {
                    this.H45Field = value;
                    this.RaisePropertyChanged("H45");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal H46 {
            get {
                return this.H46Field;
            }
            set {
                if ((this.H46Field.Equals(value) != true)) {
                    this.H46Field = value;
                    this.RaisePropertyChanged("H46");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal H47 {
            get {
                return this.H47Field;
            }
            set {
                if ((this.H47Field.Equals(value) != true)) {
                    this.H47Field = value;
                    this.RaisePropertyChanged("H47");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal H48 {
            get {
                return this.H48Field;
            }
            set {
                if ((this.H48Field.Equals(value) != true)) {
                    this.H48Field = value;
                    this.RaisePropertyChanged("H48");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal H49 {
            get {
                return this.H49Field;
            }
            set {
                if ((this.H49Field.Equals(value) != true)) {
                    this.H49Field = value;
                    this.RaisePropertyChanged("H49");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal H5 {
            get {
                return this.H5Field;
            }
            set {
                if ((this.H5Field.Equals(value) != true)) {
                    this.H5Field = value;
                    this.RaisePropertyChanged("H5");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal H50 {
            get {
                return this.H50Field;
            }
            set {
                if ((this.H50Field.Equals(value) != true)) {
                    this.H50Field = value;
                    this.RaisePropertyChanged("H50");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal H51 {
            get {
                return this.H51Field;
            }
            set {
                if ((this.H51Field.Equals(value) != true)) {
                    this.H51Field = value;
                    this.RaisePropertyChanged("H51");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal H52 {
            get {
                return this.H52Field;
            }
            set {
                if ((this.H52Field.Equals(value) != true)) {
                    this.H52Field = value;
                    this.RaisePropertyChanged("H52");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal H53 {
            get {
                return this.H53Field;
            }
            set {
                if ((this.H53Field.Equals(value) != true)) {
                    this.H53Field = value;
                    this.RaisePropertyChanged("H53");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal H54 {
            get {
                return this.H54Field;
            }
            set {
                if ((this.H54Field.Equals(value) != true)) {
                    this.H54Field = value;
                    this.RaisePropertyChanged("H54");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal H55 {
            get {
                return this.H55Field;
            }
            set {
                if ((this.H55Field.Equals(value) != true)) {
                    this.H55Field = value;
                    this.RaisePropertyChanged("H55");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal H56 {
            get {
                return this.H56Field;
            }
            set {
                if ((this.H56Field.Equals(value) != true)) {
                    this.H56Field = value;
                    this.RaisePropertyChanged("H56");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal H57 {
            get {
                return this.H57Field;
            }
            set {
                if ((this.H57Field.Equals(value) != true)) {
                    this.H57Field = value;
                    this.RaisePropertyChanged("H57");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal H58 {
            get {
                return this.H58Field;
            }
            set {
                if ((this.H58Field.Equals(value) != true)) {
                    this.H58Field = value;
                    this.RaisePropertyChanged("H58");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal H59 {
            get {
                return this.H59Field;
            }
            set {
                if ((this.H59Field.Equals(value) != true)) {
                    this.H59Field = value;
                    this.RaisePropertyChanged("H59");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal H6 {
            get {
                return this.H6Field;
            }
            set {
                if ((this.H6Field.Equals(value) != true)) {
                    this.H6Field = value;
                    this.RaisePropertyChanged("H6");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal H7 {
            get {
                return this.H7Field;
            }
            set {
                if ((this.H7Field.Equals(value) != true)) {
                    this.H7Field = value;
                    this.RaisePropertyChanged("H7");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal H8 {
            get {
                return this.H8Field;
            }
            set {
                if ((this.H8Field.Equals(value) != true)) {
                    this.H8Field = value;
                    this.RaisePropertyChanged("H8");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal H9 {
            get {
                return this.H9Field;
            }
            set {
                if ((this.H9Field.Equals(value) != true)) {
                    this.H9Field = value;
                    this.RaisePropertyChanged("H9");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PTOMEDICODI {
            get {
                return this.PTOMEDICODIField;
            }
            set {
                if ((this.PTOMEDICODIField.Equals(value) != true)) {
                    this.PTOMEDICODIField = value;
                    this.RaisePropertyChanged("PTOMEDICODI");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TIPOINFOCODI {
            get {
                return this.TIPOINFOCODIField;
            }
            set {
                if ((this.TIPOINFOCODIField.Equals(value) != true)) {
                    this.TIPOINFOCODIField = value;
                    this.RaisePropertyChanged("TIPOINFOCODI");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RegistroRPF", Namespace="http://schemas.datacontract.org/2004/07/Extranet.Cloud.Dominio")]
    [System.SerializableAttribute()]
    public partial class RegistroRPF : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal BALANCEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool CUMPLEFRECUENCIAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool CUMPLEPOTENCIAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal DIFERENCIAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FECHAHORAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal FRECUENCIAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime HORAFINField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime HORAINICIOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string INDICADORPOTField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal NRODATOSField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal POTENCIAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PTOMEDICODIField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SEGUNDOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TIPOINFOCODIField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal VALORField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal BALANCE {
            get {
                return this.BALANCEField;
            }
            set {
                if ((this.BALANCEField.Equals(value) != true)) {
                    this.BALANCEField = value;
                    this.RaisePropertyChanged("BALANCE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool CUMPLEFRECUENCIA {
            get {
                return this.CUMPLEFRECUENCIAField;
            }
            set {
                if ((this.CUMPLEFRECUENCIAField.Equals(value) != true)) {
                    this.CUMPLEFRECUENCIAField = value;
                    this.RaisePropertyChanged("CUMPLEFRECUENCIA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool CUMPLEPOTENCIA {
            get {
                return this.CUMPLEPOTENCIAField;
            }
            set {
                if ((this.CUMPLEPOTENCIAField.Equals(value) != true)) {
                    this.CUMPLEPOTENCIAField = value;
                    this.RaisePropertyChanged("CUMPLEPOTENCIA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal DIFERENCIA {
            get {
                return this.DIFERENCIAField;
            }
            set {
                if ((this.DIFERENCIAField.Equals(value) != true)) {
                    this.DIFERENCIAField = value;
                    this.RaisePropertyChanged("DIFERENCIA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FECHAHORA {
            get {
                return this.FECHAHORAField;
            }
            set {
                if ((this.FECHAHORAField.Equals(value) != true)) {
                    this.FECHAHORAField = value;
                    this.RaisePropertyChanged("FECHAHORA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal FRECUENCIA {
            get {
                return this.FRECUENCIAField;
            }
            set {
                if ((this.FRECUENCIAField.Equals(value) != true)) {
                    this.FRECUENCIAField = value;
                    this.RaisePropertyChanged("FRECUENCIA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime HORAFIN {
            get {
                return this.HORAFINField;
            }
            set {
                if ((this.HORAFINField.Equals(value) != true)) {
                    this.HORAFINField = value;
                    this.RaisePropertyChanged("HORAFIN");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime HORAINICIO {
            get {
                return this.HORAINICIOField;
            }
            set {
                if ((this.HORAINICIOField.Equals(value) != true)) {
                    this.HORAINICIOField = value;
                    this.RaisePropertyChanged("HORAINICIO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string INDICADORPOT {
            get {
                return this.INDICADORPOTField;
            }
            set {
                if ((object.ReferenceEquals(this.INDICADORPOTField, value) != true)) {
                    this.INDICADORPOTField = value;
                    this.RaisePropertyChanged("INDICADORPOT");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal NRODATOS {
            get {
                return this.NRODATOSField;
            }
            set {
                if ((this.NRODATOSField.Equals(value) != true)) {
                    this.NRODATOSField = value;
                    this.RaisePropertyChanged("NRODATOS");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal POTENCIA {
            get {
                return this.POTENCIAField;
            }
            set {
                if ((this.POTENCIAField.Equals(value) != true)) {
                    this.POTENCIAField = value;
                    this.RaisePropertyChanged("POTENCIA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PTOMEDICODI {
            get {
                return this.PTOMEDICODIField;
            }
            set {
                if ((this.PTOMEDICODIField.Equals(value) != true)) {
                    this.PTOMEDICODIField = value;
                    this.RaisePropertyChanged("PTOMEDICODI");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SEGUNDO {
            get {
                return this.SEGUNDOField;
            }
            set {
                if ((this.SEGUNDOField.Equals(value) != true)) {
                    this.SEGUNDOField = value;
                    this.RaisePropertyChanged("SEGUNDO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TIPOINFOCODI {
            get {
                return this.TIPOINFOCODIField;
            }
            set {
                if ((this.TIPOINFOCODIField.Equals(value) != true)) {
                    this.TIPOINFOCODIField = value;
                    this.RaisePropertyChanged("TIPOINFOCODI");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal VALOR {
            get {
                return this.VALORField;
            }
            set {
                if ((this.VALORField.Equals(value) != true)) {
                    this.VALORField = value;
                    this.RaisePropertyChanged("VALOR");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReporteEnvio", Namespace="http://schemas.datacontract.org/2004/07/Extranet.Cloud.Dominio")]
    [System.SerializableAttribute()]
    public partial class ReporteEnvio : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EstadoInformacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EstadoOperativoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> FechaCargaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IndConsistenciaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PtoMediCodiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal ValConsistenciaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EstadoInformacion {
            get {
                return this.EstadoInformacionField;
            }
            set {
                if ((object.ReferenceEquals(this.EstadoInformacionField, value) != true)) {
                    this.EstadoInformacionField = value;
                    this.RaisePropertyChanged("EstadoInformacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EstadoOperativo {
            get {
                return this.EstadoOperativoField;
            }
            set {
                if ((object.ReferenceEquals(this.EstadoOperativoField, value) != true)) {
                    this.EstadoOperativoField = value;
                    this.RaisePropertyChanged("EstadoOperativo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Fecha {
            get {
                return this.FechaField;
            }
            set {
                if ((this.FechaField.Equals(value) != true)) {
                    this.FechaField = value;
                    this.RaisePropertyChanged("Fecha");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> FechaCarga {
            get {
                return this.FechaCargaField;
            }
            set {
                if ((this.FechaCargaField.Equals(value) != true)) {
                    this.FechaCargaField = value;
                    this.RaisePropertyChanged("FechaCarga");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IndConsistencia {
            get {
                return this.IndConsistenciaField;
            }
            set {
                if ((object.ReferenceEquals(this.IndConsistenciaField, value) != true)) {
                    this.IndConsistenciaField = value;
                    this.RaisePropertyChanged("IndConsistencia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PtoMediCodi {
            get {
                return this.PtoMediCodiField;
            }
            set {
                if ((this.PtoMediCodiField.Equals(value) != true)) {
                    this.PtoMediCodiField = value;
                    this.RaisePropertyChanged("PtoMediCodi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal ValConsistencia {
            get {
                return this.ValConsistenciaField;
            }
            set {
                if ((this.ValConsistenciaField.Equals(value) != true)) {
                    this.ValConsistenciaField = value;
                    this.RaisePropertyChanged("ValConsistencia");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="www.coes.com.pe", ConfigurationName="ServicioCloud.IServicioCloud")]
    public interface IServicioCloud {
        
        [System.ServiceModel.OperationContractAttribute(Action="www.coes.com.pe/IServicioCloud/VerificarEnvio", ReplyAction="www.coes.com.pe/IServicioCloud/VerificarEnvioResponse")]
        COES.MVC.Extranet.ServicioCloud.ResultadoVerificacion[] VerificarEnvio(int[] ptosMedicion, System.DateTime fecha);
        
        [System.ServiceModel.OperationContractAttribute(Action="www.coes.com.pe/IServicioCloud/VerificarEnvio", ReplyAction="www.coes.com.pe/IServicioCloud/VerificarEnvioResponse")]
        System.Threading.Tasks.Task<COES.MVC.Extranet.ServicioCloud.ResultadoVerificacion[]> VerificarEnvioAsync(int[] ptosMedicion, System.DateTime fecha);
        
        [System.ServiceModel.OperationContractAttribute(Action="www.coes.com.pe/IServicioCloud/DescargarEnvio", ReplyAction="www.coes.com.pe/IServicioCloud/DescargarEnvioResponse")]
        COES.MVC.Extranet.ServicioCloud.Medicion[] DescargarEnvio(int[] ptosMedicion, System.DateTime fecha);
        
        [System.ServiceModel.OperationContractAttribute(Action="www.coes.com.pe/IServicioCloud/DescargarEnvio", ReplyAction="www.coes.com.pe/IServicioCloud/DescargarEnvioResponse")]
        System.Threading.Tasks.Task<COES.MVC.Extranet.ServicioCloud.Medicion[]> DescargarEnvioAsync(int[] ptosMedicion, System.DateTime fecha);
        
        [System.ServiceModel.OperationContractAttribute(Action="www.coes.com.pe/IServicioCloud/ObtenerDatosAnalisis", ReplyAction="www.coes.com.pe/IServicioCloud/ObtenerDatosAnalisisResponse")]
        COES.MVC.Extranet.ServicioCloud.ObtenerDatosAnalisisResponse ObtenerDatosAnalisis(COES.MVC.Extranet.ServicioCloud.ObtenerDatosAnalisisRequest request);
        
        // CODEGEN: Generando contrato de mensaje, ya que la operación tiene múltiples valores de devolución.
        [System.ServiceModel.OperationContractAttribute(Action="www.coes.com.pe/IServicioCloud/ObtenerDatosAnalisis", ReplyAction="www.coes.com.pe/IServicioCloud/ObtenerDatosAnalisisResponse")]
        System.Threading.Tasks.Task<COES.MVC.Extranet.ServicioCloud.ObtenerDatosAnalisisResponse> ObtenerDatosAnalisisAsync(COES.MVC.Extranet.ServicioCloud.ObtenerDatosAnalisisRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="www.coes.com.pe/IServicioCloud/ObtenerRangoSegundos", ReplyAction="www.coes.com.pe/IServicioCloud/ObtenerRangoSegundosResponse")]
        COES.MVC.Extranet.ServicioCloud.ObtenerRangoSegundosResponse ObtenerRangoSegundos(COES.MVC.Extranet.ServicioCloud.ObtenerRangoSegundosRequest request);
        
        // CODEGEN: Generando contrato de mensaje, ya que la operación tiene múltiples valores de devolución.
        [System.ServiceModel.OperationContractAttribute(Action="www.coes.com.pe/IServicioCloud/ObtenerRangoSegundos", ReplyAction="www.coes.com.pe/IServicioCloud/ObtenerRangoSegundosResponse")]
        System.Threading.Tasks.Task<COES.MVC.Extranet.ServicioCloud.ObtenerRangoSegundosResponse> ObtenerRangoSegundosAsync(COES.MVC.Extranet.ServicioCloud.ObtenerRangoSegundosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="www.coes.com.pe/IServicioCloud/ObtenerDatosFallas", ReplyAction="www.coes.com.pe/IServicioCloud/ObtenerDatosFallasResponse")]
        COES.MVC.Extranet.ServicioCloud.RegistroRPF[] ObtenerDatosFallas(System.DateTime fecha);
        
        [System.ServiceModel.OperationContractAttribute(Action="www.coes.com.pe/IServicioCloud/ObtenerDatosFallas", ReplyAction="www.coes.com.pe/IServicioCloud/ObtenerDatosFallasResponse")]
        System.Threading.Tasks.Task<COES.MVC.Extranet.ServicioCloud.RegistroRPF[]> ObtenerDatosFallasAsync(System.DateTime fecha);
        
        [System.ServiceModel.OperationContractAttribute(Action="www.coes.com.pe/IServicioCloud/ObtenerPotenciasMaximas", ReplyAction="www.coes.com.pe/IServicioCloud/ObtenerPotenciasMaximasResponse")]
        COES.MVC.Extranet.ServicioCloud.RegistroRPF[] ObtenerPotenciasMaximas(System.DateTime fecha);
        
        [System.ServiceModel.OperationContractAttribute(Action="www.coes.com.pe/IServicioCloud/ObtenerPotenciasMaximas", ReplyAction="www.coes.com.pe/IServicioCloud/ObtenerPotenciasMaximasResponse")]
        System.Threading.Tasks.Task<COES.MVC.Extranet.ServicioCloud.RegistroRPF[]> ObtenerPotenciasMaximasAsync(System.DateTime fecha);
        
        [System.ServiceModel.OperationContractAttribute(Action="www.coes.com.pe/IServicioCloud/ConsultaEnvioDatos", ReplyAction="www.coes.com.pe/IServicioCloud/ConsultaEnvioDatosResponse")]
        int ConsultaEnvioDatos(System.DateTime fecha, decimal[] frecuencias, decimal porcentaje, decimal potencia, decimal valorPercentil);
        
        [System.ServiceModel.OperationContractAttribute(Action="www.coes.com.pe/IServicioCloud/ConsultaEnvioDatos", ReplyAction="www.coes.com.pe/IServicioCloud/ConsultaEnvioDatosResponse")]
        System.Threading.Tasks.Task<int> ConsultaEnvioDatosAsync(System.DateTime fecha, decimal[] frecuencias, decimal porcentaje, decimal potencia, decimal valorPercentil);
        
        [System.ServiceModel.OperationContractAttribute(Action="www.coes.com.pe/IServicioCloud/ObtenerReporteEndio", ReplyAction="www.coes.com.pe/IServicioCloud/ObtenerReporteEndioResponse")]
        COES.MVC.Extranet.ServicioCloud.ReporteEnvio[] ObtenerReporteEndio(System.DateTime fecha);
        
        [System.ServiceModel.OperationContractAttribute(Action="www.coes.com.pe/IServicioCloud/ObtenerReporteEndio", ReplyAction="www.coes.com.pe/IServicioCloud/ObtenerReporteEndioResponse")]
        System.Threading.Tasks.Task<COES.MVC.Extranet.ServicioCloud.ReporteEnvio[]> ObtenerReporteEndioAsync(System.DateTime fecha);
        
        [System.ServiceModel.OperationContractAttribute(Action="www.coes.com.pe/IServicioCloud/ObtenerPuntosCargaron", ReplyAction="www.coes.com.pe/IServicioCloud/ObtenerPuntosCargaronResponse")]
        int[] ObtenerPuntosCargaron(System.DateTime fecha);
        
        [System.ServiceModel.OperationContractAttribute(Action="www.coes.com.pe/IServicioCloud/ObtenerPuntosCargaron", ReplyAction="www.coes.com.pe/IServicioCloud/ObtenerPuntosCargaronResponse")]
        System.Threading.Tasks.Task<int[]> ObtenerPuntosCargaronAsync(System.DateTime fecha);
        
        [System.ServiceModel.OperationContractAttribute(Action="www.coes.com.pe/IServicioCloud/DescargarDatos", ReplyAction="www.coes.com.pe/IServicioCloud/DescargarDatosResponse")]
        string[] DescargarDatos(System.DateTime fechaInicio, System.DateTime fechaFin, int tipo, int ptomedicodi);
        
        [System.ServiceModel.OperationContractAttribute(Action="www.coes.com.pe/IServicioCloud/DescargarDatos", ReplyAction="www.coes.com.pe/IServicioCloud/DescargarDatosResponse")]
        System.Threading.Tasks.Task<string[]> DescargarDatosAsync(System.DateTime fechaInicio, System.DateTime fechaFin, int tipo, int ptomedicodi);
        
        [System.ServiceModel.OperationContractAttribute(Action="www.coes.com.pe/IServicioCloud/ObtenerDatosComparacion", ReplyAction="www.coes.com.pe/IServicioCloud/ObtenerDatosComparacionResponse")]
        COES.MVC.Extranet.ServicioCloud.Medicion[] ObtenerDatosComparacion(System.DateTime fechaConsulta, string ptomedicodi);
        
        [System.ServiceModel.OperationContractAttribute(Action="www.coes.com.pe/IServicioCloud/ObtenerDatosComparacion", ReplyAction="www.coes.com.pe/IServicioCloud/ObtenerDatosComparacionResponse")]
        System.Threading.Tasks.Task<COES.MVC.Extranet.ServicioCloud.Medicion[]> ObtenerDatosComparacionAsync(System.DateTime fechaConsulta, string ptomedicodi);
        
        [System.ServiceModel.OperationContractAttribute(Action="www.coes.com.pe/IServicioCloud/ObtenerDatosComparacionRango", ReplyAction="www.coes.com.pe/IServicioCloud/ObtenerDatosComparacionRangoResponse")]
        COES.MVC.Extranet.ServicioCloud.Medicion[] ObtenerDatosComparacionRango(System.DateTime fechaConsulta, string ptomedicodi);
        
        [System.ServiceModel.OperationContractAttribute(Action="www.coes.com.pe/IServicioCloud/ObtenerDatosComparacionRango", ReplyAction="www.coes.com.pe/IServicioCloud/ObtenerDatosComparacionRangoResponse")]
        System.Threading.Tasks.Task<COES.MVC.Extranet.ServicioCloud.Medicion[]> ObtenerDatosComparacionRangoAsync(System.DateTime fechaConsulta, string ptomedicodi);
        
        [System.ServiceModel.OperationContractAttribute(Action="www.coes.com.pe/IServicioCloud/ObtenerDatosComparacionRangoResolucion", ReplyAction="www.coes.com.pe/IServicioCloud/ObtenerDatosComparacionRangoResolucionResponse")]
        COES.MVC.Extranet.ServicioCloud.Medicion[] ObtenerDatosComparacionRangoResolucion(System.DateTime fechaConsulta, string ptomedicodi, int resolucion);
        
        [System.ServiceModel.OperationContractAttribute(Action="www.coes.com.pe/IServicioCloud/ObtenerDatosComparacionRangoResolucion", ReplyAction="www.coes.com.pe/IServicioCloud/ObtenerDatosComparacionRangoResolucionResponse")]
        System.Threading.Tasks.Task<COES.MVC.Extranet.ServicioCloud.Medicion[]> ObtenerDatosComparacionRangoResolucionAsync(System.DateTime fechaConsulta, string ptomedicodi, int resolucion);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ObtenerDatosAnalisis", WrapperNamespace="www.coes.com.pe", IsWrapped=true)]
    public partial class ObtenerDatosAnalisisRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="www.coes.com.pe", Order=0)]
        public System.DateTime fecha;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="www.coes.com.pe", Order=1)]
        public decimal ajuste;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="www.coes.com.pe", Order=2)]
        public int intentos;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="www.coes.com.pe", Order=3)]
        public int cantidad;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="www.coes.com.pe", Order=4)]
        public int nroDatos;
        
        public ObtenerDatosAnalisisRequest() {
        }
        
        public ObtenerDatosAnalisisRequest(System.DateTime fecha, decimal ajuste, int intentos, int cantidad, int nroDatos) {
            this.fecha = fecha;
            this.ajuste = ajuste;
            this.intentos = intentos;
            this.cantidad = cantidad;
            this.nroDatos = nroDatos;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ObtenerDatosAnalisisResponse", WrapperNamespace="www.coes.com.pe", IsWrapped=true)]
    public partial class ObtenerDatosAnalisisResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="www.coes.com.pe", Order=0)]
        public COES.MVC.Extranet.ServicioCloud.RegistroRPF[] ObtenerDatosAnalisisResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="www.coes.com.pe", Order=1)]
        public int[] idsCargaron;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="www.coes.com.pe", Order=2)]
        public int[] noEncontrados;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="www.coes.com.pe", Order=3)]
        public int[] potenciaCero;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="www.coes.com.pe", Order=4)]
        public int[] frecuenciaCero;
        
        public ObtenerDatosAnalisisResponse() {
        }
        
        public ObtenerDatosAnalisisResponse(COES.MVC.Extranet.ServicioCloud.RegistroRPF[] ObtenerDatosAnalisisResult, int[] idsCargaron, int[] noEncontrados, int[] potenciaCero, int[] frecuenciaCero) {
            this.ObtenerDatosAnalisisResult = ObtenerDatosAnalisisResult;
            this.idsCargaron = idsCargaron;
            this.noEncontrados = noEncontrados;
            this.potenciaCero = potenciaCero;
            this.frecuenciaCero = frecuenciaCero;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ObtenerRangoSegundos", WrapperNamespace="www.coes.com.pe", IsWrapped=true)]
    public partial class ObtenerRangoSegundosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="www.coes.com.pe", Order=0)]
        public System.DateTime fecha;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="www.coes.com.pe", Order=1)]
        public decimal ajuste;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="www.coes.com.pe", Order=2)]
        public int intentos;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="www.coes.com.pe", Order=3)]
        public int cantidad;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="www.coes.com.pe", Order=4)]
        public int nroDatos;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="www.coes.com.pe", Order=5)]
        public decimal fmaxgen;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="www.coes.com.pe", Order=6)]
        public decimal fmingen;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="www.coes.com.pe", Order=7)]
        public decimal flimmax;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="www.coes.com.pe", Order=8)]
        public decimal flimmin;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="www.coes.com.pe", Order=9)]
        public decimal balance;
        
        public ObtenerRangoSegundosRequest() {
        }
        
        public ObtenerRangoSegundosRequest(System.DateTime fecha, decimal ajuste, int intentos, int cantidad, int nroDatos, decimal fmaxgen, decimal fmingen, decimal flimmax, decimal flimmin, decimal balance) {
            this.fecha = fecha;
            this.ajuste = ajuste;
            this.intentos = intentos;
            this.cantidad = cantidad;
            this.nroDatos = nroDatos;
            this.fmaxgen = fmaxgen;
            this.fmingen = fmingen;
            this.flimmax = flimmax;
            this.flimmin = flimmin;
            this.balance = balance;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ObtenerRangoSegundosResponse", WrapperNamespace="www.coes.com.pe", IsWrapped=true)]
    public partial class ObtenerRangoSegundosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="www.coes.com.pe", Order=0)]
        public COES.MVC.Extranet.ServicioCloud.RegistroRPF[] ObtenerRangoSegundosResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="www.coes.com.pe", Order=1)]
        public int[] idsCargaron;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="www.coes.com.pe", Order=2)]
        public int[] noEncontrados;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="www.coes.com.pe", Order=3)]
        public int[] potenciaCero;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="www.coes.com.pe", Order=4)]
        public int[] frecuenciaCero;
        
        public ObtenerRangoSegundosResponse() {
        }
        
        public ObtenerRangoSegundosResponse(COES.MVC.Extranet.ServicioCloud.RegistroRPF[] ObtenerRangoSegundosResult, int[] idsCargaron, int[] noEncontrados, int[] potenciaCero, int[] frecuenciaCero) {
            this.ObtenerRangoSegundosResult = ObtenerRangoSegundosResult;
            this.idsCargaron = idsCargaron;
            this.noEncontrados = noEncontrados;
            this.potenciaCero = potenciaCero;
            this.frecuenciaCero = frecuenciaCero;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicioCloudChannel : COES.MVC.Extranet.ServicioCloud.IServicioCloud, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioCloudClient : System.ServiceModel.ClientBase<COES.MVC.Extranet.ServicioCloud.IServicioCloud>, COES.MVC.Extranet.ServicioCloud.IServicioCloud {
        
        public ServicioCloudClient() {
        }
        
        public ServicioCloudClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioCloudClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioCloudClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioCloudClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public COES.MVC.Extranet.ServicioCloud.ResultadoVerificacion[] VerificarEnvio(int[] ptosMedicion, System.DateTime fecha) {
            return base.Channel.VerificarEnvio(ptosMedicion, fecha);
        }
        
        public System.Threading.Tasks.Task<COES.MVC.Extranet.ServicioCloud.ResultadoVerificacion[]> VerificarEnvioAsync(int[] ptosMedicion, System.DateTime fecha) {
            return base.Channel.VerificarEnvioAsync(ptosMedicion, fecha);
        }
        
        public COES.MVC.Extranet.ServicioCloud.Medicion[] DescargarEnvio(int[] ptosMedicion, System.DateTime fecha) {
            return base.Channel.DescargarEnvio(ptosMedicion, fecha);
        }
        
        public System.Threading.Tasks.Task<COES.MVC.Extranet.ServicioCloud.Medicion[]> DescargarEnvioAsync(int[] ptosMedicion, System.DateTime fecha) {
            return base.Channel.DescargarEnvioAsync(ptosMedicion, fecha);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        COES.MVC.Extranet.ServicioCloud.ObtenerDatosAnalisisResponse COES.MVC.Extranet.ServicioCloud.IServicioCloud.ObtenerDatosAnalisis(COES.MVC.Extranet.ServicioCloud.ObtenerDatosAnalisisRequest request) {
            return base.Channel.ObtenerDatosAnalisis(request);
        }
        
        public COES.MVC.Extranet.ServicioCloud.RegistroRPF[] ObtenerDatosAnalisis(System.DateTime fecha, decimal ajuste, int intentos, int cantidad, int nroDatos, out int[] idsCargaron, out int[] noEncontrados, out int[] potenciaCero, out int[] frecuenciaCero) {
            COES.MVC.Extranet.ServicioCloud.ObtenerDatosAnalisisRequest inValue = new COES.MVC.Extranet.ServicioCloud.ObtenerDatosAnalisisRequest();
            inValue.fecha = fecha;
            inValue.ajuste = ajuste;
            inValue.intentos = intentos;
            inValue.cantidad = cantidad;
            inValue.nroDatos = nroDatos;
            COES.MVC.Extranet.ServicioCloud.ObtenerDatosAnalisisResponse retVal = ((COES.MVC.Extranet.ServicioCloud.IServicioCloud)(this)).ObtenerDatosAnalisis(inValue);
            idsCargaron = retVal.idsCargaron;
            noEncontrados = retVal.noEncontrados;
            potenciaCero = retVal.potenciaCero;
            frecuenciaCero = retVal.frecuenciaCero;
            return retVal.ObtenerDatosAnalisisResult;
        }
        
        public System.Threading.Tasks.Task<COES.MVC.Extranet.ServicioCloud.ObtenerDatosAnalisisResponse> ObtenerDatosAnalisisAsync(COES.MVC.Extranet.ServicioCloud.ObtenerDatosAnalisisRequest request) {
            return base.Channel.ObtenerDatosAnalisisAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        COES.MVC.Extranet.ServicioCloud.ObtenerRangoSegundosResponse COES.MVC.Extranet.ServicioCloud.IServicioCloud.ObtenerRangoSegundos(COES.MVC.Extranet.ServicioCloud.ObtenerRangoSegundosRequest request) {
            return base.Channel.ObtenerRangoSegundos(request);
        }
        
        public COES.MVC.Extranet.ServicioCloud.RegistroRPF[] ObtenerRangoSegundos(System.DateTime fecha, decimal ajuste, int intentos, int cantidad, int nroDatos, decimal fmaxgen, decimal fmingen, decimal flimmax, decimal flimmin, decimal balance, out int[] idsCargaron, out int[] noEncontrados, out int[] potenciaCero, out int[] frecuenciaCero) {
            COES.MVC.Extranet.ServicioCloud.ObtenerRangoSegundosRequest inValue = new COES.MVC.Extranet.ServicioCloud.ObtenerRangoSegundosRequest();
            inValue.fecha = fecha;
            inValue.ajuste = ajuste;
            inValue.intentos = intentos;
            inValue.cantidad = cantidad;
            inValue.nroDatos = nroDatos;
            inValue.fmaxgen = fmaxgen;
            inValue.fmingen = fmingen;
            inValue.flimmax = flimmax;
            inValue.flimmin = flimmin;
            inValue.balance = balance;
            COES.MVC.Extranet.ServicioCloud.ObtenerRangoSegundosResponse retVal = ((COES.MVC.Extranet.ServicioCloud.IServicioCloud)(this)).ObtenerRangoSegundos(inValue);
            idsCargaron = retVal.idsCargaron;
            noEncontrados = retVal.noEncontrados;
            potenciaCero = retVal.potenciaCero;
            frecuenciaCero = retVal.frecuenciaCero;
            return retVal.ObtenerRangoSegundosResult;
        }
        
        public System.Threading.Tasks.Task<COES.MVC.Extranet.ServicioCloud.ObtenerRangoSegundosResponse> ObtenerRangoSegundosAsync(COES.MVC.Extranet.ServicioCloud.ObtenerRangoSegundosRequest request) {
            return base.Channel.ObtenerRangoSegundosAsync(request);
        }
        
        public COES.MVC.Extranet.ServicioCloud.RegistroRPF[] ObtenerDatosFallas(System.DateTime fecha) {
            return base.Channel.ObtenerDatosFallas(fecha);
        }
        
        public System.Threading.Tasks.Task<COES.MVC.Extranet.ServicioCloud.RegistroRPF[]> ObtenerDatosFallasAsync(System.DateTime fecha) {
            return base.Channel.ObtenerDatosFallasAsync(fecha);
        }
        
        public COES.MVC.Extranet.ServicioCloud.RegistroRPF[] ObtenerPotenciasMaximas(System.DateTime fecha) {
            return base.Channel.ObtenerPotenciasMaximas(fecha);
        }
        
        public System.Threading.Tasks.Task<COES.MVC.Extranet.ServicioCloud.RegistroRPF[]> ObtenerPotenciasMaximasAsync(System.DateTime fecha) {
            return base.Channel.ObtenerPotenciasMaximasAsync(fecha);
        }
        
        public int ConsultaEnvioDatos(System.DateTime fecha, decimal[] frecuencias, decimal porcentaje, decimal potencia, decimal valorPercentil) {
            return base.Channel.ConsultaEnvioDatos(fecha, frecuencias, porcentaje, potencia, valorPercentil);
        }
        
        public System.Threading.Tasks.Task<int> ConsultaEnvioDatosAsync(System.DateTime fecha, decimal[] frecuencias, decimal porcentaje, decimal potencia, decimal valorPercentil) {
            return base.Channel.ConsultaEnvioDatosAsync(fecha, frecuencias, porcentaje, potencia, valorPercentil);
        }
        
        public COES.MVC.Extranet.ServicioCloud.ReporteEnvio[] ObtenerReporteEndio(System.DateTime fecha) {
            return base.Channel.ObtenerReporteEndio(fecha);
        }
        
        public System.Threading.Tasks.Task<COES.MVC.Extranet.ServicioCloud.ReporteEnvio[]> ObtenerReporteEndioAsync(System.DateTime fecha) {
            return base.Channel.ObtenerReporteEndioAsync(fecha);
        }
        
        public int[] ObtenerPuntosCargaron(System.DateTime fecha) {
            return base.Channel.ObtenerPuntosCargaron(fecha);
        }
        
        public System.Threading.Tasks.Task<int[]> ObtenerPuntosCargaronAsync(System.DateTime fecha) {
            return base.Channel.ObtenerPuntosCargaronAsync(fecha);
        }
        
        public string[] DescargarDatos(System.DateTime fechaInicio, System.DateTime fechaFin, int tipo, int ptomedicodi) {
            return base.Channel.DescargarDatos(fechaInicio, fechaFin, tipo, ptomedicodi);
        }
        
        public System.Threading.Tasks.Task<string[]> DescargarDatosAsync(System.DateTime fechaInicio, System.DateTime fechaFin, int tipo, int ptomedicodi) {
            return base.Channel.DescargarDatosAsync(fechaInicio, fechaFin, tipo, ptomedicodi);
        }
        
        public COES.MVC.Extranet.ServicioCloud.Medicion[] ObtenerDatosComparacion(System.DateTime fechaConsulta, string ptomedicodi) {
            return base.Channel.ObtenerDatosComparacion(fechaConsulta, ptomedicodi);
        }
        
        public System.Threading.Tasks.Task<COES.MVC.Extranet.ServicioCloud.Medicion[]> ObtenerDatosComparacionAsync(System.DateTime fechaConsulta, string ptomedicodi) {
            return base.Channel.ObtenerDatosComparacionAsync(fechaConsulta, ptomedicodi);
        }
        
        public COES.MVC.Extranet.ServicioCloud.Medicion[] ObtenerDatosComparacionRango(System.DateTime fechaConsulta, string ptomedicodi) {
            return base.Channel.ObtenerDatosComparacionRango(fechaConsulta, ptomedicodi);
        }
        
        public System.Threading.Tasks.Task<COES.MVC.Extranet.ServicioCloud.Medicion[]> ObtenerDatosComparacionRangoAsync(System.DateTime fechaConsulta, string ptomedicodi) {
            return base.Channel.ObtenerDatosComparacionRangoAsync(fechaConsulta, ptomedicodi);
        }
        
        public COES.MVC.Extranet.ServicioCloud.Medicion[] ObtenerDatosComparacionRangoResolucion(System.DateTime fechaConsulta, string ptomedicodi, int resolucion) {
            return base.Channel.ObtenerDatosComparacionRangoResolucion(fechaConsulta, ptomedicodi, resolucion);
        }
        
        public System.Threading.Tasks.Task<COES.MVC.Extranet.ServicioCloud.Medicion[]> ObtenerDatosComparacionRangoResolucionAsync(System.DateTime fechaConsulta, string ptomedicodi, int resolucion) {
            return base.Channel.ObtenerDatosComparacionRangoResolucionAsync(fechaConsulta, ptomedicodi, resolucion);
        }
    }
}
