//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.Xml.Serialization;

// 
// This source code was auto-generated by wsdl, Version=4.0.30319.33440.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Web.Services.WebServiceBindingAttribute(Name="ServicioSunatSoap", Namespace="http://tempuri.org/")]
public partial class ServicioSunat : System.Web.Services.Protocols.SoapHttpClientProtocol {
    
    private System.Threading.SendOrPostCallback ObtenerDatosSunatOperationCompleted;
    
    /// <remarks/>
    public ServicioSunat() {
        this.Url = "https://www.coes.org.pe/ServicioConsultaRUC/ServicioSunat.asmx";
    }
    
    /// <remarks/>
    public event ObtenerDatosSunatCompletedEventHandler ObtenerDatosSunatCompleted;
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ObtenerDatosSunat", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public BeanEmpresa ObtenerDatosSunat(string ruc) {
        object[] results = this.Invoke("ObtenerDatosSunat", new object[] {
                    ruc});
        return ((BeanEmpresa)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginObtenerDatosSunat(string ruc, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("ObtenerDatosSunat", new object[] {
                    ruc}, callback, asyncState);
    }
    
    /// <remarks/>
    public BeanEmpresa EndObtenerDatosSunat(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((BeanEmpresa)(results[0]));
    }
    
    /// <remarks/>
    public void ObtenerDatosSunatAsync(string ruc) {
        this.ObtenerDatosSunatAsync(ruc, null);
    }
    
    /// <remarks/>
    public void ObtenerDatosSunatAsync(string ruc, object userState) {
        if ((this.ObtenerDatosSunatOperationCompleted == null)) {
            this.ObtenerDatosSunatOperationCompleted = new System.Threading.SendOrPostCallback(this.OnObtenerDatosSunatOperationCompleted);
        }
        this.InvokeAsync("ObtenerDatosSunat", new object[] {
                    ruc}, this.ObtenerDatosSunatOperationCompleted, userState);
    }
    
    private void OnObtenerDatosSunatOperationCompleted(object arg) {
        if ((this.ObtenerDatosSunatCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.ObtenerDatosSunatCompleted(this, new ObtenerDatosSunatCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    public new void CancelAsync(object userState) {
        base.CancelAsync(userState);
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
public partial class BeanEmpresa {
    
    private string rUCField;
    
    private string razonSocialField;
    
    private string nombreComercialField;
    
    private string estadoField;
    
    private string tipoViaField;
    
    private string nombreViaField;
    
    private string distritoField;
    
    private string provinciaField;
    
    private string departamentoField;
    
    private string referenciasField;
    
    private string domicilioLegalField;
    
    private string telefonoField;
    
    private string faxField;
    
    private string numeroField;
    
    /// <remarks/>
    public string RUC {
        get {
            return this.rUCField;
        }
        set {
            this.rUCField = value;
        }
    }
    
    /// <remarks/>
    public string RazonSocial {
        get {
            return this.razonSocialField;
        }
        set {
            this.razonSocialField = value;
        }
    }
    
    /// <remarks/>
    public string NombreComercial {
        get {
            return this.nombreComercialField;
        }
        set {
            this.nombreComercialField = value;
        }
    }
    
    /// <remarks/>
    public string Estado {
        get {
            return this.estadoField;
        }
        set {
            this.estadoField = value;
        }
    }
    
    /// <remarks/>
    public string TipoVia {
        get {
            return this.tipoViaField;
        }
        set {
            this.tipoViaField = value;
        }
    }
    
    /// <remarks/>
    public string NombreVia {
        get {
            return this.nombreViaField;
        }
        set {
            this.nombreViaField = value;
        }
    }
    
    /// <remarks/>
    public string Distrito {
        get {
            return this.distritoField;
        }
        set {
            this.distritoField = value;
        }
    }
    
    /// <remarks/>
    public string Provincia {
        get {
            return this.provinciaField;
        }
        set {
            this.provinciaField = value;
        }
    }
    
    /// <remarks/>
    public string Departamento {
        get {
            return this.departamentoField;
        }
        set {
            this.departamentoField = value;
        }
    }
    
    /// <remarks/>
    public string Referencias {
        get {
            return this.referenciasField;
        }
        set {
            this.referenciasField = value;
        }
    }
    
    /// <remarks/>
    public string DomicilioLegal {
        get {
            return this.domicilioLegalField;
        }
        set {
            this.domicilioLegalField = value;
        }
    }
    
    /// <remarks/>
    public string Telefono {
        get {
            return this.telefonoField;
        }
        set {
            this.telefonoField = value;
        }
    }
    
    /// <remarks/>
    public string Fax {
        get {
            return this.faxField;
        }
        set {
            this.faxField = value;
        }
    }
    
    /// <remarks/>
    public string Numero {
        get {
            return this.numeroField;
        }
        set {
            this.numeroField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
public delegate void ObtenerDatosSunatCompletedEventHandler(object sender, ObtenerDatosSunatCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class ObtenerDatosSunatCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal ObtenerDatosSunatCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public BeanEmpresa Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((BeanEmpresa)(this.results[0]));
        }
    }
}
