using System;
using System.Collections.Generic;
using COES.Base.Core;

namespace COES.Dominio.DTO.Transferencias
{
    /// <summary>
    /// Clase que mapea la tabla CAI_GENERDEMAN
    /// </summary>
    public class CaiGenerdemanDTO : EntityBase
    {
        public Int32 Cagdcmcodi { get; set; } 
        public int Caiajcodi { get; set; } 
        public string Cagdcmfuentedat { get; set; } 
        public int Ptomedicodi { get; set; } 
        public int Emprcodi { get; set; } 
        public int Equicodicen { get; set; } 
        public int Equicodiuni { get; set; } 
        public string Cagdcmcalidadinfo { get; set; }
        public DateTime? Cagdcmdia { get; set; }
        public decimal Cagdcmtotaldia { get; set; }
        public decimal H1 { get; set; }
        public decimal H2 { get; set; }
        public decimal H3 { get; set; }
        public decimal H4 { get; set; }
        public decimal H5 { get; set; }
        public decimal H6 { get; set; }
        public decimal H7 { get; set; }
        public decimal H8 { get; set; }
        public decimal H9 { get; set; }
        public decimal H10 { get; set; }
        public decimal H11 { get; set; }
        public decimal H12 { get; set; }
        public decimal H13 { get; set; }
        public decimal H14 { get; set; }
        public decimal H15 { get; set; }
        public decimal H16 { get; set; }
        public decimal H17 { get; set; }
        public decimal H18 { get; set; }
        public decimal H19 { get; set; }
        public decimal H20 { get; set; }
        public decimal H21 { get; set; }
        public decimal H22 { get; set; }
        public decimal H23 { get; set; }
        public decimal H24 { get; set; }
        public decimal H25 { get; set; }
        public decimal H26 { get; set; }
        public decimal H27 { get; set; }
        public decimal H28 { get; set; }
        public decimal H29 { get; set; }
        public decimal H30 { get; set; }
        public decimal H31 { get; set; }
        public decimal H32 { get; set; }
        public decimal H33 { get; set; }
        public decimal H34 { get; set; }
        public decimal H35 { get; set; }
        public decimal H36 { get; set; }
        public decimal H37 { get; set; }
        public decimal H38 { get; set; }
        public decimal H39 { get; set; }
        public decimal H40 { get; set; }
        public decimal H41 { get; set; }
        public decimal H42 { get; set; }
        public decimal H43 { get; set; }
        public decimal H44 { get; set; }
        public decimal H45 { get; set; }
        public decimal H46 { get; set; }
        public decimal H47 { get; set; }
        public decimal H48 { get; set; }
        public decimal H49 { get; set; }
        public decimal H50 { get; set; }
        public decimal H51 { get; set; }
        public decimal H52 { get; set; }
        public decimal H53 { get; set; }
        public decimal H54 { get; set; }
        public decimal H55 { get; set; }
        public decimal H56 { get; set; }
        public decimal H57 { get; set; }
        public decimal H58 { get; set; }
        public decimal H59 { get; set; }
        public decimal H60 { get; set; }
        public decimal H61 { get; set; }
        public decimal H62 { get; set; }
        public decimal H63 { get; set; }
        public decimal H64 { get; set; }
        public decimal H65 { get; set; }
        public decimal H66 { get; set; }
        public decimal H67 { get; set; }
        public decimal H68 { get; set; }
        public decimal H69 { get; set; }
        public decimal H70 { get; set; }
        public decimal H71 { get; set; }
        public decimal H72 { get; set; }
        public decimal H73 { get; set; }
        public decimal H74 { get; set; }
        public decimal H75 { get; set; }
        public decimal H76 { get; set; }
        public decimal H77 { get; set; }
        public decimal H78 { get; set; }
        public decimal H79 { get; set; }
        public decimal H80 { get; set; }
        public decimal H81 { get; set; }
        public decimal H82 { get; set; }
        public decimal H83 { get; set; }
        public decimal H84 { get; set; }
        public decimal H85 { get; set; }
        public decimal H86 { get; set; }
        public decimal H87 { get; set; }
        public decimal H88 { get; set; }
        public decimal H89 { get; set; }
        public decimal H90 { get; set; }
        public decimal H91 { get; set; }
        public decimal H92 { get; set; }
        public decimal H93 { get; set; }
        public decimal H94 { get; set; }
        public decimal H95 { get; set; }
        public decimal H96 { get; set; }
        public string T1 { get; set; }
        public string T2 { get; set; }
        public string T3 { get; set; }
        public string T4 { get; set; }
        public string T5 { get; set; }
        public string T6 { get; set; }
        public string T7 { get; set; }
        public string T8 { get; set; }
        public string T9 { get; set; }
        public string T10 { get; set; }
        public string T11 { get; set; }
        public string T12 { get; set; }
        public string T13 { get; set; }
        public string T14 { get; set; }
        public string T15 { get; set; }
        public string T16 { get; set; }
        public string T17 { get; set; }
        public string T18 { get; set; }
        public string T19 { get; set; }
        public string T20 { get; set; }
        public string T21 { get; set; }
        public string T22 { get; set; }
        public string T23 { get; set; }
        public string T24 { get; set; }
        public string T25 { get; set; }
        public string T26 { get; set; }
        public string T27 { get; set; }
        public string T28 { get; set; }
        public string T29 { get; set; }
        public string T30 { get; set; }
        public string T31 { get; set; }
        public string T32 { get; set; }
        public string T33 { get; set; }
        public string T34 { get; set; }
        public string T35 { get; set; }
        public string T36 { get; set; }
        public string T37 { get; set; }
        public string T38 { get; set; }
        public string T39 { get; set; }
        public string T40 { get; set; }
        public string T41 { get; set; }
        public string T42 { get; set; }
        public string T43 { get; set; }
        public string T44 { get; set; }
        public string T45 { get; set; }
        public string T46 { get; set; }
        public string T47 { get; set; }
        public string T48 { get; set; }
        public string T49 { get; set; }
        public string T50 { get; set; }
        public string T51 { get; set; }
        public string T52 { get; set; }
        public string T53 { get; set; }
        public string T54 { get; set; }
        public string T55 { get; set; }
        public string T56 { get; set; }
        public string T57 { get; set; }
        public string T58 { get; set; }
        public string T59 { get; set; }
        public string T60 { get; set; }
        public string T61 { get; set; }
        public string T62 { get; set; }
        public string T63 { get; set; }
        public string T64 { get; set; }
        public string T65 { get; set; }
        public string T66 { get; set; }
        public string T67 { get; set; }
        public string T68 { get; set; }
        public string T69 { get; set; }
        public string T70 { get; set; }
        public string T71 { get; set; }
        public string T72 { get; set; }
        public string T73 { get; set; }
        public string T74 { get; set; }
        public string T75 { get; set; }
        public string T76 { get; set; }
        public string T77 { get; set; }
        public string T78 { get; set; }
        public string T79 { get; set; }
        public string T80 { get; set; }
        public string T81 { get; set; }
        public string T82 { get; set; }
        public string T83 { get; set; }
        public string T84 { get; set; }
        public string T85 { get; set; }
        public string T86 { get; set; }
        public string T87 { get; set; }
        public string T88 { get; set; }
        public string T89 { get; set; }
        public string T90 { get; set; }
        public string T91 { get; set; }
        public string T92 { get; set; }
        public string T93 { get; set; }
        public string T94 { get; set; }
        public string T95 { get; set; }
        public string T96 { get; set; } 
        public string Cagdcmusucreacion { get; set; } 
        public DateTime Cagdcmfeccreacion { get; set; } 

        //Atributos empleados en la consulta
        public decimal CM1 { get; set; }
        public decimal CM2 { get; set; }
        public decimal CM3 { get; set; }
        public decimal CM4 { get; set; }
        public decimal CM5 { get; set; }
        public decimal CM6 { get; set; }
        public decimal CM7 { get; set; }
        public decimal CM8 { get; set; }
        public decimal CM9 { get; set; }
        public decimal CM10 { get; set; }
        public decimal CM11 { get; set; }
        public decimal CM12 { get; set; }
        public decimal CM13 { get; set; }
        public decimal CM14 { get; set; }
        public decimal CM15 { get; set; }
        public decimal CM16 { get; set; }
        public decimal CM17 { get; set; }
        public decimal CM18 { get; set; }
        public decimal CM19 { get; set; }
        public decimal CM20 { get; set; }
        public decimal CM21 { get; set; }
        public decimal CM22 { get; set; }
        public decimal CM23 { get; set; }
        public decimal CM24 { get; set; }
        public decimal CM25 { get; set; }
        public decimal CM26 { get; set; }
        public decimal CM27 { get; set; }
        public decimal CM28 { get; set; }
        public decimal CM29 { get; set; }
        public decimal CM30 { get; set; }
        public decimal CM31 { get; set; }
        public decimal CM32 { get; set; }
        public decimal CM33 { get; set; }
        public decimal CM34 { get; set; }
        public decimal CM35 { get; set; }
        public decimal CM36 { get; set; }
        public decimal CM37 { get; set; }
        public decimal CM38 { get; set; }
        public decimal CM39 { get; set; }
        public decimal CM40 { get; set; }
        public decimal CM41 { get; set; }
        public decimal CM42 { get; set; }
        public decimal CM43 { get; set; }
        public decimal CM44 { get; set; }
        public decimal CM45 { get; set; }
        public decimal CM46 { get; set; }
        public decimal CM47 { get; set; }
        public decimal CM48 { get; set; }
        public decimal CM49 { get; set; }
        public decimal CM50 { get; set; }
        public decimal CM51 { get; set; }
        public decimal CM52 { get; set; }
        public decimal CM53 { get; set; }
        public decimal CM54 { get; set; }
        public decimal CM55 { get; set; }
        public decimal CM56 { get; set; }
        public decimal CM57 { get; set; }
        public decimal CM58 { get; set; }
        public decimal CM59 { get; set; }
        public decimal CM60 { get; set; }
        public decimal CM61 { get; set; }
        public decimal CM62 { get; set; }
        public decimal CM63 { get; set; }
        public decimal CM64 { get; set; }
        public decimal CM65 { get; set; }
        public decimal CM66 { get; set; }
        public decimal CM67 { get; set; }
        public decimal CM68 { get; set; }
        public decimal CM69 { get; set; }
        public decimal CM70 { get; set; }
        public decimal CM71 { get; set; }
        public decimal CM72 { get; set; }
        public decimal CM73 { get; set; }
        public decimal CM74 { get; set; }
        public decimal CM75 { get; set; }
        public decimal CM76 { get; set; }
        public decimal CM77 { get; set; }
        public decimal CM78 { get; set; }
        public decimal CM79 { get; set; }
        public decimal CM80 { get; set; }
        public decimal CM81 { get; set; }
        public decimal CM82 { get; set; }
        public decimal CM83 { get; set; }
        public decimal CM84 { get; set; }
        public decimal CM85 { get; set; }
        public decimal CM86 { get; set; }
        public decimal CM87 { get; set; }
        public decimal CM88 { get; set; }
        public decimal CM89 { get; set; }
        public decimal CM90 { get; set; }
        public decimal CM91 { get; set; }
        public decimal CM92 { get; set; }
        public decimal CM93 { get; set; }
        public decimal CM94 { get; set; }
        public decimal CM95 { get; set; }
        public decimal CM96 { get; set; }

    }
}
