//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COES.MVC.Intranet.DirectorioServicio {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Directorio", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Directorio : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdDirectorioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DesApellidoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DesNombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DesEmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DesAnexoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DesAnexoAltField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IndAnexoAltField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DesTelefonoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DesCumpleanoField;
        
        private System.Nullable<int> IdAreaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DesFotoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DesFuncionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DesAreaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MaquinaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IndExtranetField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int IdDirectorio {
            get {
                return this.IdDirectorioField;
            }
            set {
                if ((this.IdDirectorioField.Equals(value) != true)) {
                    this.IdDirectorioField = value;
                    this.RaisePropertyChanged("IdDirectorio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string DesApellido {
            get {
                return this.DesApellidoField;
            }
            set {
                if ((object.ReferenceEquals(this.DesApellidoField, value) != true)) {
                    this.DesApellidoField = value;
                    this.RaisePropertyChanged("DesApellido");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string DesNombre {
            get {
                return this.DesNombreField;
            }
            set {
                if ((object.ReferenceEquals(this.DesNombreField, value) != true)) {
                    this.DesNombreField = value;
                    this.RaisePropertyChanged("DesNombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string DesEmail {
            get {
                return this.DesEmailField;
            }
            set {
                if ((object.ReferenceEquals(this.DesEmailField, value) != true)) {
                    this.DesEmailField = value;
                    this.RaisePropertyChanged("DesEmail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string DesAnexo {
            get {
                return this.DesAnexoField;
            }
            set {
                if ((object.ReferenceEquals(this.DesAnexoField, value) != true)) {
                    this.DesAnexoField = value;
                    this.RaisePropertyChanged("DesAnexo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string DesAnexoAlt {
            get {
                return this.DesAnexoAltField;
            }
            set {
                if ((object.ReferenceEquals(this.DesAnexoAltField, value) != true)) {
                    this.DesAnexoAltField = value;
                    this.RaisePropertyChanged("DesAnexoAlt");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string IndAnexoAlt {
            get {
                return this.IndAnexoAltField;
            }
            set {
                if ((object.ReferenceEquals(this.IndAnexoAltField, value) != true)) {
                    this.IndAnexoAltField = value;
                    this.RaisePropertyChanged("IndAnexoAlt");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string DesTelefono {
            get {
                return this.DesTelefonoField;
            }
            set {
                if ((object.ReferenceEquals(this.DesTelefonoField, value) != true)) {
                    this.DesTelefonoField = value;
                    this.RaisePropertyChanged("DesTelefono");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string DesCumpleano {
            get {
                return this.DesCumpleanoField;
            }
            set {
                if ((object.ReferenceEquals(this.DesCumpleanoField, value) != true)) {
                    this.DesCumpleanoField = value;
                    this.RaisePropertyChanged("DesCumpleano");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=9)]
        public System.Nullable<int> IdArea {
            get {
                return this.IdAreaField;
            }
            set {
                if ((this.IdAreaField.Equals(value) != true)) {
                    this.IdAreaField = value;
                    this.RaisePropertyChanged("IdArea");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string DesFoto {
            get {
                return this.DesFotoField;
            }
            set {
                if ((object.ReferenceEquals(this.DesFotoField, value) != true)) {
                    this.DesFotoField = value;
                    this.RaisePropertyChanged("DesFoto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public string DesFuncion {
            get {
                return this.DesFuncionField;
            }
            set {
                if ((object.ReferenceEquals(this.DesFuncionField, value) != true)) {
                    this.DesFuncionField = value;
                    this.RaisePropertyChanged("DesFuncion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public string DesArea {
            get {
                return this.DesAreaField;
            }
            set {
                if ((object.ReferenceEquals(this.DesAreaField, value) != true)) {
                    this.DesAreaField = value;
                    this.RaisePropertyChanged("DesArea");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=13)]
        public string Maquina {
            get {
                return this.MaquinaField;
            }
            set {
                if ((object.ReferenceEquals(this.MaquinaField, value) != true)) {
                    this.MaquinaField = value;
                    this.RaisePropertyChanged("Maquina");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=14)]
        public string IndExtranet {
            get {
                return this.IndExtranetField;
            }
            set {
                if ((object.ReferenceEquals(this.IndExtranetField, value) != true)) {
                    this.IndExtranetField = value;
                    this.RaisePropertyChanged("IndExtranet");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Area", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Area : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdAreaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DesAreaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DesJefeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DesCorreoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DesNombreField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int IdArea {
            get {
                return this.IdAreaField;
            }
            set {
                if ((this.IdAreaField.Equals(value) != true)) {
                    this.IdAreaField = value;
                    this.RaisePropertyChanged("IdArea");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string DesArea {
            get {
                return this.DesAreaField;
            }
            set {
                if ((object.ReferenceEquals(this.DesAreaField, value) != true)) {
                    this.DesAreaField = value;
                    this.RaisePropertyChanged("DesArea");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string DesJefe {
            get {
                return this.DesJefeField;
            }
            set {
                if ((object.ReferenceEquals(this.DesJefeField, value) != true)) {
                    this.DesJefeField = value;
                    this.RaisePropertyChanged("DesJefe");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string DesCorreo {
            get {
                return this.DesCorreoField;
            }
            set {
                if ((object.ReferenceEquals(this.DesCorreoField, value) != true)) {
                    this.DesCorreoField = value;
                    this.RaisePropertyChanged("DesCorreo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string DesNombre {
            get {
                return this.DesNombreField;
            }
            set {
                if ((object.ReferenceEquals(this.DesNombreField, value) != true)) {
                    this.DesNombreField = value;
                    this.RaisePropertyChanged("DesNombre");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="DirectorioServicio.ServicioSoap")]
    public interface ServicioSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento ListarDirectorioResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListarDirectorio", ReplyAction="*")]
        COES.MVC.Intranet.DirectorioServicio.ListarDirectorioResponse ListarDirectorio(COES.MVC.Intranet.DirectorioServicio.ListarDirectorioRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListarDirectorio", ReplyAction="*")]
        System.Threading.Tasks.Task<COES.MVC.Intranet.DirectorioServicio.ListarDirectorioResponse> ListarDirectorioAsync(COES.MVC.Intranet.DirectorioServicio.ListarDirectorioRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento ListarAreasResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListarAreas", ReplyAction="*")]
        COES.MVC.Intranet.DirectorioServicio.ListarAreasResponse ListarAreas(COES.MVC.Intranet.DirectorioServicio.ListarAreasRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListarAreas", ReplyAction="*")]
        System.Threading.Tasks.Task<COES.MVC.Intranet.DirectorioServicio.ListarAreasResponse> ListarAreasAsync(COES.MVC.Intranet.DirectorioServicio.ListarAreasRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento ObtenerDirectorioPorAreaResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtenerDirectorioPorArea", ReplyAction="*")]
        COES.MVC.Intranet.DirectorioServicio.ObtenerDirectorioPorAreaResponse ObtenerDirectorioPorArea(COES.MVC.Intranet.DirectorioServicio.ObtenerDirectorioPorAreaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtenerDirectorioPorArea", ReplyAction="*")]
        System.Threading.Tasks.Task<COES.MVC.Intranet.DirectorioServicio.ObtenerDirectorioPorAreaResponse> ObtenerDirectorioPorAreaAsync(COES.MVC.Intranet.DirectorioServicio.ObtenerDirectorioPorAreaRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento anexo del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ActualizarAnexoDirectorio", ReplyAction="*")]
        COES.MVC.Intranet.DirectorioServicio.ActualizarAnexoDirectorioResponse ActualizarAnexoDirectorio(COES.MVC.Intranet.DirectorioServicio.ActualizarAnexoDirectorioRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ActualizarAnexoDirectorio", ReplyAction="*")]
        System.Threading.Tasks.Task<COES.MVC.Intranet.DirectorioServicio.ActualizarAnexoDirectorioResponse> ActualizarAnexoDirectorioAsync(COES.MVC.Intranet.DirectorioServicio.ActualizarAnexoDirectorioRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListarDirectorioRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ListarDirectorio", Namespace="http://tempuri.org/", Order=0)]
        public COES.MVC.Intranet.DirectorioServicio.ListarDirectorioRequestBody Body;
        
        public ListarDirectorioRequest() {
        }
        
        public ListarDirectorioRequest(COES.MVC.Intranet.DirectorioServicio.ListarDirectorioRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ListarDirectorioRequestBody {
        
        public ListarDirectorioRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListarDirectorioResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ListarDirectorioResponse", Namespace="http://tempuri.org/", Order=0)]
        public COES.MVC.Intranet.DirectorioServicio.ListarDirectorioResponseBody Body;
        
        public ListarDirectorioResponse() {
        }
        
        public ListarDirectorioResponse(COES.MVC.Intranet.DirectorioServicio.ListarDirectorioResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ListarDirectorioResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public COES.MVC.Intranet.DirectorioServicio.Directorio[] ListarDirectorioResult;
        
        public ListarDirectorioResponseBody() {
        }
        
        public ListarDirectorioResponseBody(COES.MVC.Intranet.DirectorioServicio.Directorio[] ListarDirectorioResult) {
            this.ListarDirectorioResult = ListarDirectorioResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListarAreasRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ListarAreas", Namespace="http://tempuri.org/", Order=0)]
        public COES.MVC.Intranet.DirectorioServicio.ListarAreasRequestBody Body;
        
        public ListarAreasRequest() {
        }
        
        public ListarAreasRequest(COES.MVC.Intranet.DirectorioServicio.ListarAreasRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ListarAreasRequestBody {
        
        public ListarAreasRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListarAreasResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ListarAreasResponse", Namespace="http://tempuri.org/", Order=0)]
        public COES.MVC.Intranet.DirectorioServicio.ListarAreasResponseBody Body;
        
        public ListarAreasResponse() {
        }
        
        public ListarAreasResponse(COES.MVC.Intranet.DirectorioServicio.ListarAreasResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ListarAreasResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public COES.MVC.Intranet.DirectorioServicio.Area[] ListarAreasResult;
        
        public ListarAreasResponseBody() {
        }
        
        public ListarAreasResponseBody(COES.MVC.Intranet.DirectorioServicio.Area[] ListarAreasResult) {
            this.ListarAreasResult = ListarAreasResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerDirectorioPorAreaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerDirectorioPorArea", Namespace="http://tempuri.org/", Order=0)]
        public COES.MVC.Intranet.DirectorioServicio.ObtenerDirectorioPorAreaRequestBody Body;
        
        public ObtenerDirectorioPorAreaRequest() {
        }
        
        public ObtenerDirectorioPorAreaRequest(COES.MVC.Intranet.DirectorioServicio.ObtenerDirectorioPorAreaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ObtenerDirectorioPorAreaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int idArea;
        
        public ObtenerDirectorioPorAreaRequestBody() {
        }
        
        public ObtenerDirectorioPorAreaRequestBody(int idArea) {
            this.idArea = idArea;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerDirectorioPorAreaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerDirectorioPorAreaResponse", Namespace="http://tempuri.org/", Order=0)]
        public COES.MVC.Intranet.DirectorioServicio.ObtenerDirectorioPorAreaResponseBody Body;
        
        public ObtenerDirectorioPorAreaResponse() {
        }
        
        public ObtenerDirectorioPorAreaResponse(COES.MVC.Intranet.DirectorioServicio.ObtenerDirectorioPorAreaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ObtenerDirectorioPorAreaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public COES.MVC.Intranet.DirectorioServicio.Directorio[] ObtenerDirectorioPorAreaResult;
        
        public ObtenerDirectorioPorAreaResponseBody() {
        }
        
        public ObtenerDirectorioPorAreaResponseBody(COES.MVC.Intranet.DirectorioServicio.Directorio[] ObtenerDirectorioPorAreaResult) {
            this.ObtenerDirectorioPorAreaResult = ObtenerDirectorioPorAreaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ActualizarAnexoDirectorioRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ActualizarAnexoDirectorio", Namespace="http://tempuri.org/", Order=0)]
        public COES.MVC.Intranet.DirectorioServicio.ActualizarAnexoDirectorioRequestBody Body;
        
        public ActualizarAnexoDirectorioRequest() {
        }
        
        public ActualizarAnexoDirectorioRequest(COES.MVC.Intranet.DirectorioServicio.ActualizarAnexoDirectorioRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ActualizarAnexoDirectorioRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int idDirectorio;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string anexo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string indicador;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string indExtranet;
        
        public ActualizarAnexoDirectorioRequestBody() {
        }
        
        public ActualizarAnexoDirectorioRequestBody(int idDirectorio, string anexo, string indicador, string indExtranet) {
            this.idDirectorio = idDirectorio;
            this.anexo = anexo;
            this.indicador = indicador;
            this.indExtranet = indExtranet;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ActualizarAnexoDirectorioResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ActualizarAnexoDirectorioResponse", Namespace="http://tempuri.org/", Order=0)]
        public COES.MVC.Intranet.DirectorioServicio.ActualizarAnexoDirectorioResponseBody Body;
        
        public ActualizarAnexoDirectorioResponse() {
        }
        
        public ActualizarAnexoDirectorioResponse(COES.MVC.Intranet.DirectorioServicio.ActualizarAnexoDirectorioResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ActualizarAnexoDirectorioResponseBody {
        
        public ActualizarAnexoDirectorioResponseBody() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServicioSoapChannel : COES.MVC.Intranet.DirectorioServicio.ServicioSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioSoapClient : System.ServiceModel.ClientBase<COES.MVC.Intranet.DirectorioServicio.ServicioSoap>, COES.MVC.Intranet.DirectorioServicio.ServicioSoap {
        
        public ServicioSoapClient() {
        }
        
        public ServicioSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        COES.MVC.Intranet.DirectorioServicio.ListarDirectorioResponse COES.MVC.Intranet.DirectorioServicio.ServicioSoap.ListarDirectorio(COES.MVC.Intranet.DirectorioServicio.ListarDirectorioRequest request) {
            return base.Channel.ListarDirectorio(request);
        }
        
        public COES.MVC.Intranet.DirectorioServicio.Directorio[] ListarDirectorio() {
            COES.MVC.Intranet.DirectorioServicio.ListarDirectorioRequest inValue = new COES.MVC.Intranet.DirectorioServicio.ListarDirectorioRequest();
            inValue.Body = new COES.MVC.Intranet.DirectorioServicio.ListarDirectorioRequestBody();
            COES.MVC.Intranet.DirectorioServicio.ListarDirectorioResponse retVal = ((COES.MVC.Intranet.DirectorioServicio.ServicioSoap)(this)).ListarDirectorio(inValue);
            return retVal.Body.ListarDirectorioResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<COES.MVC.Intranet.DirectorioServicio.ListarDirectorioResponse> COES.MVC.Intranet.DirectorioServicio.ServicioSoap.ListarDirectorioAsync(COES.MVC.Intranet.DirectorioServicio.ListarDirectorioRequest request) {
            return base.Channel.ListarDirectorioAsync(request);
        }
        
        public System.Threading.Tasks.Task<COES.MVC.Intranet.DirectorioServicio.ListarDirectorioResponse> ListarDirectorioAsync() {
            COES.MVC.Intranet.DirectorioServicio.ListarDirectorioRequest inValue = new COES.MVC.Intranet.DirectorioServicio.ListarDirectorioRequest();
            inValue.Body = new COES.MVC.Intranet.DirectorioServicio.ListarDirectorioRequestBody();
            return ((COES.MVC.Intranet.DirectorioServicio.ServicioSoap)(this)).ListarDirectorioAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        COES.MVC.Intranet.DirectorioServicio.ListarAreasResponse COES.MVC.Intranet.DirectorioServicio.ServicioSoap.ListarAreas(COES.MVC.Intranet.DirectorioServicio.ListarAreasRequest request) {
            return base.Channel.ListarAreas(request);
        }
        
        public COES.MVC.Intranet.DirectorioServicio.Area[] ListarAreas() {
            COES.MVC.Intranet.DirectorioServicio.ListarAreasRequest inValue = new COES.MVC.Intranet.DirectorioServicio.ListarAreasRequest();
            inValue.Body = new COES.MVC.Intranet.DirectorioServicio.ListarAreasRequestBody();
            COES.MVC.Intranet.DirectorioServicio.ListarAreasResponse retVal = ((COES.MVC.Intranet.DirectorioServicio.ServicioSoap)(this)).ListarAreas(inValue);
            return retVal.Body.ListarAreasResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<COES.MVC.Intranet.DirectorioServicio.ListarAreasResponse> COES.MVC.Intranet.DirectorioServicio.ServicioSoap.ListarAreasAsync(COES.MVC.Intranet.DirectorioServicio.ListarAreasRequest request) {
            return base.Channel.ListarAreasAsync(request);
        }
        
        public System.Threading.Tasks.Task<COES.MVC.Intranet.DirectorioServicio.ListarAreasResponse> ListarAreasAsync() {
            COES.MVC.Intranet.DirectorioServicio.ListarAreasRequest inValue = new COES.MVC.Intranet.DirectorioServicio.ListarAreasRequest();
            inValue.Body = new COES.MVC.Intranet.DirectorioServicio.ListarAreasRequestBody();
            return ((COES.MVC.Intranet.DirectorioServicio.ServicioSoap)(this)).ListarAreasAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        COES.MVC.Intranet.DirectorioServicio.ObtenerDirectorioPorAreaResponse COES.MVC.Intranet.DirectorioServicio.ServicioSoap.ObtenerDirectorioPorArea(COES.MVC.Intranet.DirectorioServicio.ObtenerDirectorioPorAreaRequest request) {
            return base.Channel.ObtenerDirectorioPorArea(request);
        }
        
        public COES.MVC.Intranet.DirectorioServicio.Directorio[] ObtenerDirectorioPorArea(int idArea) {
            COES.MVC.Intranet.DirectorioServicio.ObtenerDirectorioPorAreaRequest inValue = new COES.MVC.Intranet.DirectorioServicio.ObtenerDirectorioPorAreaRequest();
            inValue.Body = new COES.MVC.Intranet.DirectorioServicio.ObtenerDirectorioPorAreaRequestBody();
            inValue.Body.idArea = idArea;
            COES.MVC.Intranet.DirectorioServicio.ObtenerDirectorioPorAreaResponse retVal = ((COES.MVC.Intranet.DirectorioServicio.ServicioSoap)(this)).ObtenerDirectorioPorArea(inValue);
            return retVal.Body.ObtenerDirectorioPorAreaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<COES.MVC.Intranet.DirectorioServicio.ObtenerDirectorioPorAreaResponse> COES.MVC.Intranet.DirectorioServicio.ServicioSoap.ObtenerDirectorioPorAreaAsync(COES.MVC.Intranet.DirectorioServicio.ObtenerDirectorioPorAreaRequest request) {
            return base.Channel.ObtenerDirectorioPorAreaAsync(request);
        }
        
        public System.Threading.Tasks.Task<COES.MVC.Intranet.DirectorioServicio.ObtenerDirectorioPorAreaResponse> ObtenerDirectorioPorAreaAsync(int idArea) {
            COES.MVC.Intranet.DirectorioServicio.ObtenerDirectorioPorAreaRequest inValue = new COES.MVC.Intranet.DirectorioServicio.ObtenerDirectorioPorAreaRequest();
            inValue.Body = new COES.MVC.Intranet.DirectorioServicio.ObtenerDirectorioPorAreaRequestBody();
            inValue.Body.idArea = idArea;
            return ((COES.MVC.Intranet.DirectorioServicio.ServicioSoap)(this)).ObtenerDirectorioPorAreaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        COES.MVC.Intranet.DirectorioServicio.ActualizarAnexoDirectorioResponse COES.MVC.Intranet.DirectorioServicio.ServicioSoap.ActualizarAnexoDirectorio(COES.MVC.Intranet.DirectorioServicio.ActualizarAnexoDirectorioRequest request) {
            return base.Channel.ActualizarAnexoDirectorio(request);
        }
        
        public void ActualizarAnexoDirectorio(int idDirectorio, string anexo, string indicador, string indExtranet) {
            COES.MVC.Intranet.DirectorioServicio.ActualizarAnexoDirectorioRequest inValue = new COES.MVC.Intranet.DirectorioServicio.ActualizarAnexoDirectorioRequest();
            inValue.Body = new COES.MVC.Intranet.DirectorioServicio.ActualizarAnexoDirectorioRequestBody();
            inValue.Body.idDirectorio = idDirectorio;
            inValue.Body.anexo = anexo;
            inValue.Body.indicador = indicador;
            inValue.Body.indExtranet = indExtranet;
            COES.MVC.Intranet.DirectorioServicio.ActualizarAnexoDirectorioResponse retVal = ((COES.MVC.Intranet.DirectorioServicio.ServicioSoap)(this)).ActualizarAnexoDirectorio(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<COES.MVC.Intranet.DirectorioServicio.ActualizarAnexoDirectorioResponse> COES.MVC.Intranet.DirectorioServicio.ServicioSoap.ActualizarAnexoDirectorioAsync(COES.MVC.Intranet.DirectorioServicio.ActualizarAnexoDirectorioRequest request) {
            return base.Channel.ActualizarAnexoDirectorioAsync(request);
        }
        
        public System.Threading.Tasks.Task<COES.MVC.Intranet.DirectorioServicio.ActualizarAnexoDirectorioResponse> ActualizarAnexoDirectorioAsync(int idDirectorio, string anexo, string indicador, string indExtranet) {
            COES.MVC.Intranet.DirectorioServicio.ActualizarAnexoDirectorioRequest inValue = new COES.MVC.Intranet.DirectorioServicio.ActualizarAnexoDirectorioRequest();
            inValue.Body = new COES.MVC.Intranet.DirectorioServicio.ActualizarAnexoDirectorioRequestBody();
            inValue.Body.idDirectorio = idDirectorio;
            inValue.Body.anexo = anexo;
            inValue.Body.indicador = indicador;
            inValue.Body.indExtranet = indExtranet;
            return ((COES.MVC.Intranet.DirectorioServicio.ServicioSoap)(this)).ActualizarAnexoDirectorioAsync(inValue);
        }
    }
}
