//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.Xml.Serialization;

// 
// Este código fuente fue generado automáticamente por wsdl, Versión=4.0.30319.33440.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Web.Services.WebServiceBindingAttribute(Name="ImportacionSicliEndpointServiceSoapBinding", Namespace="http://impl.remote.interosicoesws.osinergmin.gob/")]
public partial class ImportacionSicliEndpointService : System.Web.Services.Protocols.SoapHttpClientProtocol {
    
    private System.Threading.SendOrPostCallback consultarEmpresasParaRemisionOperationCompleted;
    
    private System.Threading.SendOrPostCallback descargarInformacionRemitidaOperationCompleted;
    
    private System.Threading.SendOrPostCallback consultarUltFecActualizacionOperationCompleted;
    
    private System.Threading.SendOrPostCallback consultarEmpresasRemitentesOperationCompleted;

    //- alpha.HDT - Inicio 09/07/2017: : Cambio para atender el requerimiento.
    //- Remover en proxima revision: SI
    /// <remarks/>
    //public ImportacionSicliEndpointService() {
    //    this.Url = "http://srvcertgart.osinergmin.gob.pe:80/interosi-coes-ws/remote/importacionSicliWS";
    //}
    //- HDT Fin
    
    //- alpha.HDT - 09/07/2017: Cambio para atender el requerimiento. 
    public ImportacionSicliEndpointService(String url)
    {
        this.Url = url;
    }
    
    /// <remarks/>
    public event consultarEmpresasParaRemisionCompletedEventHandler consultarEmpresasParaRemisionCompleted;
    
    /// <remarks/>
    public event descargarInformacionRemitidaCompletedEventHandler descargarInformacionRemitidaCompleted;
    
    /// <remarks/>
    public event consultarUltFecActualizacionCompletedEventHandler consultarUltFecActualizacionCompleted;
    
    /// <remarks/>
    public event consultarEmpresasRemitentesCompletedEventHandler consultarEmpresasRemitentesCompleted;
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://remote.interosicoesint.osinergmin.gob/", ResponseNamespace="http://remote.interosicoesint.osinergmin.gob/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public roConsultarEmpresasParaRemision consultarEmpresasParaRemision([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] riConsultarEmpresasParaRemision arg0) {
        object[] results = this.Invoke("consultarEmpresasParaRemision", new object[] {
                    arg0});
        return ((roConsultarEmpresasParaRemision)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginconsultarEmpresasParaRemision(riConsultarEmpresasParaRemision arg0, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("consultarEmpresasParaRemision", new object[] {
                    arg0}, callback, asyncState);
    }
    
    /// <remarks/>
    public roConsultarEmpresasParaRemision EndconsultarEmpresasParaRemision(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((roConsultarEmpresasParaRemision)(results[0]));
    }
    
    /// <remarks/>
    public void consultarEmpresasParaRemisionAsync(riConsultarEmpresasParaRemision arg0) {
        this.consultarEmpresasParaRemisionAsync(arg0, null);
    }
    
    /// <remarks/>
    public void consultarEmpresasParaRemisionAsync(riConsultarEmpresasParaRemision arg0, object userState) {
        if ((this.consultarEmpresasParaRemisionOperationCompleted == null)) {
            this.consultarEmpresasParaRemisionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnconsultarEmpresasParaRemisionOperationCompleted);
        }
        this.InvokeAsync("consultarEmpresasParaRemision", new object[] {
                    arg0}, this.consultarEmpresasParaRemisionOperationCompleted, userState);
    }
    
    private void OnconsultarEmpresasParaRemisionOperationCompleted(object arg) {
        if ((this.consultarEmpresasParaRemisionCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.consultarEmpresasParaRemisionCompleted(this, new consultarEmpresasParaRemisionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://remote.interosicoesint.osinergmin.gob/", ResponseNamespace="http://remote.interosicoesint.osinergmin.gob/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public roDescargarInformacionRemitida descargarInformacionRemitida([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] riDescargarInformacionRemitida arg0) {
        object[] results = this.Invoke("descargarInformacionRemitida", new object[] {
                    arg0});
        return ((roDescargarInformacionRemitida)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BegindescargarInformacionRemitida(riDescargarInformacionRemitida arg0, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("descargarInformacionRemitida", new object[] {
                    arg0}, callback, asyncState);
    }
    
    /// <remarks/>
    public roDescargarInformacionRemitida EnddescargarInformacionRemitida(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((roDescargarInformacionRemitida)(results[0]));
    }
    
    /// <remarks/>
    public void descargarInformacionRemitidaAsync(riDescargarInformacionRemitida arg0) {
        this.descargarInformacionRemitidaAsync(arg0, null);
    }
    
    /// <remarks/>
    public void descargarInformacionRemitidaAsync(riDescargarInformacionRemitida arg0, object userState) {
        if ((this.descargarInformacionRemitidaOperationCompleted == null)) {
            this.descargarInformacionRemitidaOperationCompleted = new System.Threading.SendOrPostCallback(this.OndescargarInformacionRemitidaOperationCompleted);
        }
        this.InvokeAsync("descargarInformacionRemitida", new object[] {
                    arg0}, this.descargarInformacionRemitidaOperationCompleted, userState);
    }
    
    private void OndescargarInformacionRemitidaOperationCompleted(object arg) {
        if ((this.descargarInformacionRemitidaCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.descargarInformacionRemitidaCompleted(this, new descargarInformacionRemitidaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://remote.interosicoesint.osinergmin.gob/", ResponseNamespace="http://remote.interosicoesint.osinergmin.gob/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public roConsultarUltFecActualizacion consultarUltFecActualizacion([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] riConsultarUltFecActualizacion arg0) {
        object[] results = this.Invoke("consultarUltFecActualizacion", new object[] {
                    arg0});
        return ((roConsultarUltFecActualizacion)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginconsultarUltFecActualizacion(riConsultarUltFecActualizacion arg0, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("consultarUltFecActualizacion", new object[] {
                    arg0}, callback, asyncState);
    }
    
    /// <remarks/>
    public roConsultarUltFecActualizacion EndconsultarUltFecActualizacion(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((roConsultarUltFecActualizacion)(results[0]));
    }
    
    /// <remarks/>
    public void consultarUltFecActualizacionAsync(riConsultarUltFecActualizacion arg0) {
        this.consultarUltFecActualizacionAsync(arg0, null);
    }
    
    /// <remarks/>
    public void consultarUltFecActualizacionAsync(riConsultarUltFecActualizacion arg0, object userState) {
        if ((this.consultarUltFecActualizacionOperationCompleted == null)) {
            this.consultarUltFecActualizacionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnconsultarUltFecActualizacionOperationCompleted);
        }
        this.InvokeAsync("consultarUltFecActualizacion", new object[] {
                    arg0}, this.consultarUltFecActualizacionOperationCompleted, userState);
    }
    
    private void OnconsultarUltFecActualizacionOperationCompleted(object arg) {
        if ((this.consultarUltFecActualizacionCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.consultarUltFecActualizacionCompleted(this, new consultarUltFecActualizacionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://remote.interosicoesint.osinergmin.gob/", ResponseNamespace="http://remote.interosicoesint.osinergmin.gob/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public roConsultarEmpresasRemitentes consultarEmpresasRemitentes([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] riConsultarEmpresasRemitentes arg0) {
        object[] results = this.Invoke("consultarEmpresasRemitentes", new object[] {
                    arg0});
        return ((roConsultarEmpresasRemitentes)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginconsultarEmpresasRemitentes(riConsultarEmpresasRemitentes arg0, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("consultarEmpresasRemitentes", new object[] {
                    arg0}, callback, asyncState);
    }
    
    /// <remarks/>
    public roConsultarEmpresasRemitentes EndconsultarEmpresasRemitentes(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((roConsultarEmpresasRemitentes)(results[0]));
    }
    
    /// <remarks/>
    public void consultarEmpresasRemitentesAsync(riConsultarEmpresasRemitentes arg0) {
        this.consultarEmpresasRemitentesAsync(arg0, null);
    }
    
    /// <remarks/>
    public void consultarEmpresasRemitentesAsync(riConsultarEmpresasRemitentes arg0, object userState) {
        if ((this.consultarEmpresasRemitentesOperationCompleted == null)) {
            this.consultarEmpresasRemitentesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnconsultarEmpresasRemitentesOperationCompleted);
        }
        this.InvokeAsync("consultarEmpresasRemitentes", new object[] {
                    arg0}, this.consultarEmpresasRemitentesOperationCompleted, userState);
    }
    
    private void OnconsultarEmpresasRemitentesOperationCompleted(object arg) {
        if ((this.consultarEmpresasRemitentesCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.consultarEmpresasRemitentesCompleted(this, new consultarEmpresasRemitentesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    public new void CancelAsync(object userState) {
        base.CancelAsync(userState);
    }
}

/// <comentarios/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://remote.interosicoesint.osinergmin.gob/")]
public partial class riConsultarEmpresasParaRemision {
    
    private string codigoPeriodoRemisionField;
    
    private string codigoProcedimientoRemisionField;
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string codigoPeriodoRemision {
        get {
            return this.codigoPeriodoRemisionField;
        }
        set {
            this.codigoPeriodoRemisionField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string codigoProcedimientoRemision {
        get {
            return this.codigoProcedimientoRemisionField;
        }
        set {
            this.codigoProcedimientoRemisionField = value;
        }
    }
}

/// <comentarios/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://remote.interosicoesint.osinergmin.gob/")]
public partial class nuevaRemisionDTO {
    
    private string codigoEmpresaField;
    
    private string codigoTablaField;
    
    private System.DateTime fechaRemisionField;
    
    private bool fechaRemisionFieldSpecified;
    
    private string nombreEmpresaField;
    
    private string nombreTablaField;
    
    private int nroRegistrosField;
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string codigoEmpresa {
        get {
            return this.codigoEmpresaField;
        }
        set {
            this.codigoEmpresaField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string codigoTabla {
        get {
            return this.codigoTablaField;
        }
        set {
            this.codigoTablaField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public System.DateTime fechaRemision {
        get {
            return this.fechaRemisionField;
        }
        set {
            this.fechaRemisionField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool fechaRemisionSpecified {
        get {
            return this.fechaRemisionFieldSpecified;
        }
        set {
            this.fechaRemisionFieldSpecified = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string nombreEmpresa {
        get {
            return this.nombreEmpresaField;
        }
        set {
            this.nombreEmpresaField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string nombreTabla {
        get {
            return this.nombreTablaField;
        }
        set {
            this.nombreTablaField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public int nroRegistros {
        get {
            return this.nroRegistrosField;
        }
        set {
            this.nroRegistrosField = value;
        }
    }
}

/// <comentarios/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://remote.interosicoesint.osinergmin.gob/")]
public partial class roConsultarEmpresasRemitentes {
    
    private string codigoMensajeField;
    
    private nuevaRemisionDTO[] listaNuevasRemisionesField;
    
    private string mensajeResultanteField;
    
    private int valorResultanteField;
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string codigoMensaje {
        get {
            return this.codigoMensajeField;
        }
        set {
            this.codigoMensajeField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute("listaNuevasRemisiones", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
    public nuevaRemisionDTO[] listaNuevasRemisiones {
        get {
            return this.listaNuevasRemisionesField;
        }
        set {
            this.listaNuevasRemisionesField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string mensajeResultante {
        get {
            return this.mensajeResultanteField;
        }
        set {
            this.mensajeResultanteField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public int valorResultante {
        get {
            return this.valorResultanteField;
        }
        set {
            this.valorResultanteField = value;
        }
    }
}

/// <comentarios/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://remote.interosicoesint.osinergmin.gob/")]
public partial class riConsultarEmpresasRemitentes {
    
    private string codigoPeriodoRemisionField;
    
    private string codigoProcedimientoRemisionField;
    
    private System.DateTime fechaReferenteField;
    
    private bool fechaReferenteFieldSpecified;
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string codigoPeriodoRemision {
        get {
            return this.codigoPeriodoRemisionField;
        }
        set {
            this.codigoPeriodoRemisionField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string codigoProcedimientoRemision {
        get {
            return this.codigoProcedimientoRemisionField;
        }
        set {
            this.codigoProcedimientoRemisionField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public System.DateTime fechaReferente {
        get {
            return this.fechaReferenteField;
        }
        set {
            this.fechaReferenteField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool fechaReferenteSpecified {
        get {
            return this.fechaReferenteFieldSpecified;
        }
        set {
            this.fechaReferenteFieldSpecified = value;
        }
    }
}

/// <comentarios/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://remote.interosicoesint.osinergmin.gob/")]
public partial class roConsultarUltFecActualizacion {
    
    private string codigoMensajeField;
    
    private System.DateTime fechaUltimaActualizacionField;
    
    private bool fechaUltimaActualizacionFieldSpecified;
    
    private string mensajeResultanteField;
    
    private int valorResultanteField;
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string codigoMensaje {
        get {
            return this.codigoMensajeField;
        }
        set {
            this.codigoMensajeField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public System.DateTime fechaUltimaActualizacion {
        get {
            return this.fechaUltimaActualizacionField;
        }
        set {
            this.fechaUltimaActualizacionField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool fechaUltimaActualizacionSpecified {
        get {
            return this.fechaUltimaActualizacionFieldSpecified;
        }
        set {
            this.fechaUltimaActualizacionFieldSpecified = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string mensajeResultante {
        get {
            return this.mensajeResultanteField;
        }
        set {
            this.mensajeResultanteField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public int valorResultante {
        get {
            return this.valorResultanteField;
        }
        set {
            this.valorResultanteField = value;
        }
    }
}

/// <comentarios/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://remote.interosicoesint.osinergmin.gob/")]
public partial class riConsultarUltFecActualizacion {
    
    private string codigoPeriodoRemisionField;
    
    private string codigoProcedimientoRemisionField;
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string codigoPeriodoRemision {
        get {
            return this.codigoPeriodoRemisionField;
        }
        set {
            this.codigoPeriodoRemisionField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string codigoProcedimientoRemision {
        get {
            return this.codigoProcedimientoRemisionField;
        }
        set {
            this.codigoProcedimientoRemisionField = value;
        }
    }
}

/// <comentarios/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://remote.interosicoesint.osinergmin.gob/")]
public partial class roDescargarInformacionRemitida {
    
    private byte[] archivoInformacionRemitidaField;
    
    private string codigoMensajeField;
    
    private string mensajeResultanteField;
    
    private int valorResultanteField;
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary")]
    public byte[] archivoInformacionRemitida {
        get {
            return this.archivoInformacionRemitidaField;
        }
        set {
            this.archivoInformacionRemitidaField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string codigoMensaje {
        get {
            return this.codigoMensajeField;
        }
        set {
            this.codigoMensajeField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string mensajeResultante {
        get {
            return this.mensajeResultanteField;
        }
        set {
            this.mensajeResultanteField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public int valorResultante {
        get {
            return this.valorResultanteField;
        }
        set {
            this.valorResultanteField = value;
        }
    }
}

/// <comentarios/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://remote.interosicoesint.osinergmin.gob/")]
public partial class riDescargarInformacionRemitida {
    
    private string codigoPeriodoRemisionField;
    
    private string codigoProcedimientoRemisionField;
    
    private string codigoTablaField;
    
    private string codigosEmpresasField;
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string codigoPeriodoRemision {
        get {
            return this.codigoPeriodoRemisionField;
        }
        set {
            this.codigoPeriodoRemisionField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string codigoProcedimientoRemision {
        get {
            return this.codigoProcedimientoRemisionField;
        }
        set {
            this.codigoProcedimientoRemisionField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string codigoTabla {
        get {
            return this.codigoTablaField;
        }
        set {
            this.codigoTablaField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string codigosEmpresas {
        get {
            return this.codigosEmpresasField;
        }
        set {
            this.codigosEmpresasField = value;
        }
    }
}

/// <comentarios/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://remote.interosicoesint.osinergmin.gob/")]
public partial class empresaRemisionDTO {
    
    private string codigoEmpresaField;
    
    private string nombreEmpresaField;
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string codigoEmpresa {
        get {
            return this.codigoEmpresaField;
        }
        set {
            this.codigoEmpresaField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string nombreEmpresa {
        get {
            return this.nombreEmpresaField;
        }
        set {
            this.nombreEmpresaField = value;
        }
    }
}

/// <comentarios/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://remote.interosicoesint.osinergmin.gob/")]
public partial class roConsultarEmpresasParaRemision {
    
    private string codigoMensajeField;
    
    private empresaRemisionDTO[] listaEmpresasField;
    
    private string mensajeResultanteField;
    
    private int valorResultanteField;
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string codigoMensaje {
        get {
            return this.codigoMensajeField;
        }
        set {
            this.codigoMensajeField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute("listaEmpresas", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
    public empresaRemisionDTO[] listaEmpresas {
        get {
            return this.listaEmpresasField;
        }
        set {
            this.listaEmpresasField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string mensajeResultante {
        get {
            return this.mensajeResultanteField;
        }
        set {
            this.mensajeResultanteField = value;
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public int valorResultante {
        get {
            return this.valorResultanteField;
        }
        set {
            this.valorResultanteField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
public delegate void consultarEmpresasParaRemisionCompletedEventHandler(object sender, consultarEmpresasParaRemisionCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class consultarEmpresasParaRemisionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal consultarEmpresasParaRemisionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public roConsultarEmpresasParaRemision Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((roConsultarEmpresasParaRemision)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
public delegate void descargarInformacionRemitidaCompletedEventHandler(object sender, descargarInformacionRemitidaCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class descargarInformacionRemitidaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal descargarInformacionRemitidaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public roDescargarInformacionRemitida Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((roDescargarInformacionRemitida)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
public delegate void consultarUltFecActualizacionCompletedEventHandler(object sender, consultarUltFecActualizacionCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class consultarUltFecActualizacionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal consultarUltFecActualizacionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public roConsultarUltFecActualizacion Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((roConsultarUltFecActualizacion)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
public delegate void consultarEmpresasRemitentesCompletedEventHandler(object sender, consultarEmpresasRemitentesCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class consultarEmpresasRemitentesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal consultarEmpresasRemitentesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public roConsultarEmpresasRemitentes Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((roConsultarEmpresasRemitentes)(this.results[0]));
        }
    }
}
