//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.Xml.Serialization;

// 
// This source code was auto-generated by wsdl, Version=4.0.30319.1.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Web.Services.WebServiceBindingAttribute(Name="RemisionCoesEndpointServiceSoapBinding", Namespace="http://impl.remote.interosicoesws.osinergmin.gob/")]
public partial class RemisionCoesEndpointService : System.Web.Services.Protocols.SoapHttpClientProtocol {
    
    private System.Threading.SendOrPostCallback procesarRemisionDatosOperationCompleted;
    
    private System.Threading.SendOrPostCallback obtenerTablasRemisionOperationCompleted;
    
    private System.Threading.SendOrPostCallback obtenerCamposTablaRemisionOperationCompleted;
    
    private System.Threading.SendOrPostCallback confirmarEnvioOperationCompleted;

    //- alpha.HDT - Inicio 02/11/2017: : Cambio para atender el requerimiento.
    //- Remover en proxima revision: SI
    /// <remarks/>
    //public RemisionCoesEndpointService() {
    //    this.Url = "http://ws.osinergmin.gob.pe:80/interosi-coes-ws/remote/remisionCoesWS";
    //}
    //- HDT Fin

    //- alpha.HDT - 02/11/2017: Cambio para atender el requerimiento. 
    public RemisionCoesEndpointService(String url)
    {
        this.Url = url;
    }

    /// <remarks/>
    public event procesarRemisionDatosCompletedEventHandler procesarRemisionDatosCompleted;
    
    /// <remarks/>
    public event obtenerTablasRemisionCompletedEventHandler obtenerTablasRemisionCompleted;
    
    /// <remarks/>
    public event obtenerCamposTablaRemisionCompletedEventHandler obtenerCamposTablaRemisionCompleted;
    
    /// <remarks/>
    public event confirmarEnvioCompletedEventHandler confirmarEnvioCompleted;
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://remote.interosicoesint.osinergmin.gob/", ResponseNamespace="http://remote.interosicoesint.osinergmin.gob/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public roProcesarRemisionDatos procesarRemisionDatos([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] riProcesarRemisionDatos arg0) {
        object[] results = this.Invoke("procesarRemisionDatos", new object[] {
                    arg0});
        return ((roProcesarRemisionDatos)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginprocesarRemisionDatos(riProcesarRemisionDatos arg0, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("procesarRemisionDatos", new object[] {
                    arg0}, callback, asyncState);
    }
    
    /// <remarks/>
    public roProcesarRemisionDatos EndprocesarRemisionDatos(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((roProcesarRemisionDatos)(results[0]));
    }
    
    /// <remarks/>
    public void procesarRemisionDatosAsync(riProcesarRemisionDatos arg0) {
        this.procesarRemisionDatosAsync(arg0, null);
    }
    
    /// <remarks/>
    public void procesarRemisionDatosAsync(riProcesarRemisionDatos arg0, object userState) {
        if ((this.procesarRemisionDatosOperationCompleted == null)) {
            this.procesarRemisionDatosOperationCompleted = new System.Threading.SendOrPostCallback(this.OnprocesarRemisionDatosOperationCompleted);
        }
        this.InvokeAsync("procesarRemisionDatos", new object[] {
                    arg0}, this.procesarRemisionDatosOperationCompleted, userState);
    }
    
    private void OnprocesarRemisionDatosOperationCompleted(object arg) {
        if ((this.procesarRemisionDatosCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.procesarRemisionDatosCompleted(this, new procesarRemisionDatosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://remote.interosicoesint.osinergmin.gob/", ResponseNamespace="http://remote.interosicoesint.osinergmin.gob/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public roObtenerTablasRemision obtenerTablasRemision() {
        object[] results = this.Invoke("obtenerTablasRemision", new object[0]);
        return ((roObtenerTablasRemision)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginobtenerTablasRemision(System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("obtenerTablasRemision", new object[0], callback, asyncState);
    }
    
    /// <remarks/>
    public roObtenerTablasRemision EndobtenerTablasRemision(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((roObtenerTablasRemision)(results[0]));
    }
    
    /// <remarks/>
    public void obtenerTablasRemisionAsync() {
        this.obtenerTablasRemisionAsync(null);
    }
    
    /// <remarks/>
    public void obtenerTablasRemisionAsync(object userState) {
        if ((this.obtenerTablasRemisionOperationCompleted == null)) {
            this.obtenerTablasRemisionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnobtenerTablasRemisionOperationCompleted);
        }
        this.InvokeAsync("obtenerTablasRemision", new object[0], this.obtenerTablasRemisionOperationCompleted, userState);
    }
    
    private void OnobtenerTablasRemisionOperationCompleted(object arg) {
        if ((this.obtenerTablasRemisionCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.obtenerTablasRemisionCompleted(this, new obtenerTablasRemisionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://remote.interosicoesint.osinergmin.gob/", ResponseNamespace="http://remote.interosicoesint.osinergmin.gob/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public roObtenerCamposTablaRemision obtenerCamposTablaRemision([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] riObtenerCamposTablaRemision arg0) {
        object[] results = this.Invoke("obtenerCamposTablaRemision", new object[] {
                    arg0});
        return ((roObtenerCamposTablaRemision)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginobtenerCamposTablaRemision(riObtenerCamposTablaRemision arg0, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("obtenerCamposTablaRemision", new object[] {
                    arg0}, callback, asyncState);
    }
    
    /// <remarks/>
    public roObtenerCamposTablaRemision EndobtenerCamposTablaRemision(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((roObtenerCamposTablaRemision)(results[0]));
    }
    
    /// <remarks/>
    public void obtenerCamposTablaRemisionAsync(riObtenerCamposTablaRemision arg0) {
        this.obtenerCamposTablaRemisionAsync(arg0, null);
    }
    
    /// <remarks/>
    public void obtenerCamposTablaRemisionAsync(riObtenerCamposTablaRemision arg0, object userState) {
        if ((this.obtenerCamposTablaRemisionOperationCompleted == null)) {
            this.obtenerCamposTablaRemisionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnobtenerCamposTablaRemisionOperationCompleted);
        }
        this.InvokeAsync("obtenerCamposTablaRemision", new object[] {
                    arg0}, this.obtenerCamposTablaRemisionOperationCompleted, userState);
    }
    
    private void OnobtenerCamposTablaRemisionOperationCompleted(object arg) {
        if ((this.obtenerCamposTablaRemisionCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.obtenerCamposTablaRemisionCompleted(this, new obtenerCamposTablaRemisionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://remote.interosicoesint.osinergmin.gob/", ResponseNamespace="http://remote.interosicoesint.osinergmin.gob/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public roConfirmarEnvio confirmarEnvio([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] riConfirmarEnvio arg0) {
        object[] results = this.Invoke("confirmarEnvio", new object[] {
                    arg0});
        return ((roConfirmarEnvio)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginconfirmarEnvio(riConfirmarEnvio arg0, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("confirmarEnvio", new object[] {
                    arg0}, callback, asyncState);
    }
    
    /// <remarks/>
    public roConfirmarEnvio EndconfirmarEnvio(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((roConfirmarEnvio)(results[0]));
    }
    
    /// <remarks/>
    public void confirmarEnvioAsync(riConfirmarEnvio arg0) {
        this.confirmarEnvioAsync(arg0, null);
    }
    
    /// <remarks/>
    public void confirmarEnvioAsync(riConfirmarEnvio arg0, object userState) {
        if ((this.confirmarEnvioOperationCompleted == null)) {
            this.confirmarEnvioOperationCompleted = new System.Threading.SendOrPostCallback(this.OnconfirmarEnvioOperationCompleted);
        }
        this.InvokeAsync("confirmarEnvio", new object[] {
                    arg0}, this.confirmarEnvioOperationCompleted, userState);
    }
    
    private void OnconfirmarEnvioOperationCompleted(object arg) {
        if ((this.confirmarEnvioCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.confirmarEnvioCompleted(this, new confirmarEnvioCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    public new void CancelAsync(object userState) {
        base.CancelAsync(userState);
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://remote.interosicoesint.osinergmin.gob/")]
public partial class riProcesarRemisionDatos {
    
    private string codigoEmpresaField;
    
    private string codigoPeriodoRemisionField;
    
    private string codigoTablaField;
    
    private string delimitadorField;
    
    private byte[] informacionARemitirField;
    
    private string terminalField;
    
    private string usuarioField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string codigoEmpresa {
        get {
            return this.codigoEmpresaField;
        }
        set {
            this.codigoEmpresaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string codigoPeriodoRemision {
        get {
            return this.codigoPeriodoRemisionField;
        }
        set {
            this.codigoPeriodoRemisionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string codigoTabla {
        get {
            return this.codigoTablaField;
        }
        set {
            this.codigoTablaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string delimitador {
        get {
            return this.delimitadorField;
        }
        set {
            this.delimitadorField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary")]
    public byte[] informacionARemitir {
        get {
            return this.informacionARemitirField;
        }
        set {
            this.informacionARemitirField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string terminal {
        get {
            return this.terminalField;
        }
        set {
            this.terminalField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string usuario {
        get {
            return this.usuarioField;
        }
        set {
            this.usuarioField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://remote.interosicoesint.osinergmin.gob/")]
public partial class roConfirmarEnvio {
    
    private string codigoMensajeField;
    
    private string mensajeResultanteField;
    
    private int valorResultanteField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string codigoMensaje {
        get {
            return this.codigoMensajeField;
        }
        set {
            this.codigoMensajeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string mensajeResultante {
        get {
            return this.mensajeResultanteField;
        }
        set {
            this.mensajeResultanteField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public int valorResultante {
        get {
            return this.valorResultanteField;
        }
        set {
            this.valorResultanteField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://remote.interosicoesint.osinergmin.gob/")]
public partial class riConfirmarEnvio {
    
    private string codigoPeriodoRemisionField;
    
    private string terminalField;
    
    private string usuarioField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string codigoPeriodoRemision {
        get {
            return this.codigoPeriodoRemisionField;
        }
        set {
            this.codigoPeriodoRemisionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string terminal {
        get {
            return this.terminalField;
        }
        set {
            this.terminalField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string usuario {
        get {
            return this.usuarioField;
        }
        set {
            this.usuarioField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://remote.interosicoesint.osinergmin.gob/")]
public partial class campoDTO {
    
    private string codigoCampoField;
    
    private string descripcionCampoField;
    
    private string esObligatorioField;
    
    private string nroCampoField;
    
    private string tipoDatoField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string codigoCampo {
        get {
            return this.codigoCampoField;
        }
        set {
            this.codigoCampoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string descripcionCampo {
        get {
            return this.descripcionCampoField;
        }
        set {
            this.descripcionCampoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string esObligatorio {
        get {
            return this.esObligatorioField;
        }
        set {
            this.esObligatorioField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string nroCampo {
        get {
            return this.nroCampoField;
        }
        set {
            this.nroCampoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string tipoDato {
        get {
            return this.tipoDatoField;
        }
        set {
            this.tipoDatoField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://remote.interosicoesint.osinergmin.gob/")]
public partial class roObtenerCamposTablaRemision {
    
    private string codigoMensajeField;
    
    private campoDTO[] listaCamposField;
    
    private string mensajeResultanteField;
    
    private int valorResultanteField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string codigoMensaje {
        get {
            return this.codigoMensajeField;
        }
        set {
            this.codigoMensajeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("listaCampos", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
    public campoDTO[] listaCampos {
        get {
            return this.listaCamposField;
        }
        set {
            this.listaCamposField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string mensajeResultante {
        get {
            return this.mensajeResultanteField;
        }
        set {
            this.mensajeResultanteField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public int valorResultante {
        get {
            return this.valorResultanteField;
        }
        set {
            this.valorResultanteField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://remote.interosicoesint.osinergmin.gob/")]
public partial class riObtenerCamposTablaRemision {
    
    private string codigoTablaField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string codigoTabla {
        get {
            return this.codigoTablaField;
        }
        set {
            this.codigoTablaField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://remote.interosicoesint.osinergmin.gob/")]
public partial class tablahoraDTO {
    
    private string codigoTablaField;
    
    private string descripcionTablaField;
    
    private string nombreCortoField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string codigoTabla {
        get {
            return this.codigoTablaField;
        }
        set {
            this.codigoTablaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string descripcionTabla {
        get {
            return this.descripcionTablaField;
        }
        set {
            this.descripcionTablaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string nombreCorto {
        get {
            return this.nombreCortoField;
        }
        set {
            this.nombreCortoField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://remote.interosicoesint.osinergmin.gob/")]
public partial class roObtenerTablasRemision {
    
    private string codigoMensajeField;
    
    private tablahoraDTO[] listaTablasField;
    
    private string mensajeResultanteField;
    
    private int valorResultanteField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string codigoMensaje {
        get {
            return this.codigoMensajeField;
        }
        set {
            this.codigoMensajeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("listaTablas", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
    public tablahoraDTO[] listaTablas {
        get {
            return this.listaTablasField;
        }
        set {
            this.listaTablasField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string mensajeResultante {
        get {
            return this.mensajeResultanteField;
        }
        set {
            this.mensajeResultanteField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public int valorResultante {
        get {
            return this.valorResultanteField;
        }
        set {
            this.valorResultanteField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://remote.interosicoesint.osinergmin.gob/")]
public partial class errorDTO {
    
    private string mensajeErrorField;
    
    private int nroErrorField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string mensajeError {
        get {
            return this.mensajeErrorField;
        }
        set {
            this.mensajeErrorField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public int nroError {
        get {
            return this.nroErrorField;
        }
        set {
            this.nroErrorField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://remote.interosicoesint.osinergmin.gob/")]
public partial class roProcesarRemisionDatos {
    
    private string codigoMensajeField;
    
    private errorDTO[] listaErroresField;
    
    private string mensajeResultanteField;
    
    private int valorResultanteField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string codigoMensaje {
        get {
            return this.codigoMensajeField;
        }
        set {
            this.codigoMensajeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("listaErrores", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
    public errorDTO[] listaErrores {
        get {
            return this.listaErroresField;
        }
        set {
            this.listaErroresField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string mensajeResultante {
        get {
            return this.mensajeResultanteField;
        }
        set {
            this.mensajeResultanteField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public int valorResultante {
        get {
            return this.valorResultanteField;
        }
        set {
            this.valorResultanteField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
public delegate void procesarRemisionDatosCompletedEventHandler(object sender, procesarRemisionDatosCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class procesarRemisionDatosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal procesarRemisionDatosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public roProcesarRemisionDatos Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((roProcesarRemisionDatos)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
public delegate void obtenerTablasRemisionCompletedEventHandler(object sender, obtenerTablasRemisionCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class obtenerTablasRemisionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal obtenerTablasRemisionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public roObtenerTablasRemision Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((roObtenerTablasRemision)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
public delegate void obtenerCamposTablaRemisionCompletedEventHandler(object sender, obtenerCamposTablaRemisionCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class obtenerCamposTablaRemisionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal obtenerCamposTablaRemisionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public roObtenerCamposTablaRemision Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((roObtenerCamposTablaRemision)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
public delegate void confirmarEnvioCompletedEventHandler(object sender, confirmarEnvioCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class confirmarEnvioCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal confirmarEnvioCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public roConfirmarEnvio Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((roConfirmarEnvio)(this.results[0]));
        }
    }
}
