//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COES.MVC.Extranet.DirectorioServicio {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="IntAreaDTO", Namespace="http://schemas.datacontract.org/2004/07/COES.Intranet.Dominio")]
    [System.SerializableAttribute()]
    public partial class IntAreaDTO : COES.MVC.Extranet.DirectorioServicio.EntityBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AreaabrevField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AreacodiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AreacolorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AreacorreoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AreadescripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AreaestadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> AreafeccreacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> AreafecmodificacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AreanombField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AreaorganigramaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> AreapadreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ArearesponsableField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AreausucreacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AreausumodificacionField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Areaabrev {
            get {
                return this.AreaabrevField;
            }
            set {
                if ((object.ReferenceEquals(this.AreaabrevField, value) != true)) {
                    this.AreaabrevField = value;
                    this.RaisePropertyChanged("Areaabrev");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Areacodi {
            get {
                return this.AreacodiField;
            }
            set {
                if ((this.AreacodiField.Equals(value) != true)) {
                    this.AreacodiField = value;
                    this.RaisePropertyChanged("Areacodi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Areacolor {
            get {
                return this.AreacolorField;
            }
            set {
                if ((object.ReferenceEquals(this.AreacolorField, value) != true)) {
                    this.AreacolorField = value;
                    this.RaisePropertyChanged("Areacolor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Areacorreo {
            get {
                return this.AreacorreoField;
            }
            set {
                if ((object.ReferenceEquals(this.AreacorreoField, value) != true)) {
                    this.AreacorreoField = value;
                    this.RaisePropertyChanged("Areacorreo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Areadescripcion {
            get {
                return this.AreadescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.AreadescripcionField, value) != true)) {
                    this.AreadescripcionField = value;
                    this.RaisePropertyChanged("Areadescripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Areaestado {
            get {
                return this.AreaestadoField;
            }
            set {
                if ((object.ReferenceEquals(this.AreaestadoField, value) != true)) {
                    this.AreaestadoField = value;
                    this.RaisePropertyChanged("Areaestado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> Areafeccreacion {
            get {
                return this.AreafeccreacionField;
            }
            set {
                if ((this.AreafeccreacionField.Equals(value) != true)) {
                    this.AreafeccreacionField = value;
                    this.RaisePropertyChanged("Areafeccreacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> Areafecmodificacion {
            get {
                return this.AreafecmodificacionField;
            }
            set {
                if ((this.AreafecmodificacionField.Equals(value) != true)) {
                    this.AreafecmodificacionField = value;
                    this.RaisePropertyChanged("Areafecmodificacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Areanomb {
            get {
                return this.AreanombField;
            }
            set {
                if ((object.ReferenceEquals(this.AreanombField, value) != true)) {
                    this.AreanombField = value;
                    this.RaisePropertyChanged("Areanomb");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Areaorganigrama {
            get {
                return this.AreaorganigramaField;
            }
            set {
                if ((object.ReferenceEquals(this.AreaorganigramaField, value) != true)) {
                    this.AreaorganigramaField = value;
                    this.RaisePropertyChanged("Areaorganigrama");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Areapadre {
            get {
                return this.AreapadreField;
            }
            set {
                if ((this.AreapadreField.Equals(value) != true)) {
                    this.AreapadreField = value;
                    this.RaisePropertyChanged("Areapadre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Arearesponsable {
            get {
                return this.ArearesponsableField;
            }
            set {
                if ((object.ReferenceEquals(this.ArearesponsableField, value) != true)) {
                    this.ArearesponsableField = value;
                    this.RaisePropertyChanged("Arearesponsable");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Areausucreacion {
            get {
                return this.AreausucreacionField;
            }
            set {
                if ((object.ReferenceEquals(this.AreausucreacionField, value) != true)) {
                    this.AreausucreacionField = value;
                    this.RaisePropertyChanged("Areausucreacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Areausumodificacion {
            get {
                return this.AreausumodificacionField;
            }
            set {
                if ((object.ReferenceEquals(this.AreausumodificacionField, value) != true)) {
                    this.AreausumodificacionField = value;
                    this.RaisePropertyChanged("Areausumodificacion");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntityBase", Namespace="http://schemas.datacontract.org/2004/07/COES.Intranet.Base.Core")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(COES.MVC.Extranet.DirectorioServicio.IntDirectorioDTO))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(COES.MVC.Extranet.DirectorioServicio.IntAreaDTO))]
    public partial class EntityBase : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="IntDirectorioDTO", Namespace="http://schemas.datacontract.org/2004/07/COES.Intranet.Dominio")]
    [System.SerializableAttribute()]
    public partial class IntDirectorioDTO : COES.MVC.Extranet.DirectorioServicio.EntityBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AreaabrevField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> AreacodiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AreanombField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DiaCumpleaniosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DiranexoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DirapellidoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DirapoyoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DircargoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DircodiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DircorreoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> DircumpleaniosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DirestadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> DirfeccreacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> DirfecmodificacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DirfotoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DirfuncionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DirindsuperiorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> DirnivelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DirnombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DirorganigramaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> DirpadreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DirsecretariaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DirsuperioresField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DirtelefonoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DirusucreacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DirusumodificacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ExtensionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FechaCumpleaniosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] ImagenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IndSeleccionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MesCumpleaniosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombrearchivoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PatharchivoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> UsercodeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Areaabrev {
            get {
                return this.AreaabrevField;
            }
            set {
                if ((object.ReferenceEquals(this.AreaabrevField, value) != true)) {
                    this.AreaabrevField = value;
                    this.RaisePropertyChanged("Areaabrev");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Areacodi {
            get {
                return this.AreacodiField;
            }
            set {
                if ((this.AreacodiField.Equals(value) != true)) {
                    this.AreacodiField = value;
                    this.RaisePropertyChanged("Areacodi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Areanomb {
            get {
                return this.AreanombField;
            }
            set {
                if ((object.ReferenceEquals(this.AreanombField, value) != true)) {
                    this.AreanombField = value;
                    this.RaisePropertyChanged("Areanomb");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DiaCumpleanios {
            get {
                return this.DiaCumpleaniosField;
            }
            set {
                if ((this.DiaCumpleaniosField.Equals(value) != true)) {
                    this.DiaCumpleaniosField = value;
                    this.RaisePropertyChanged("DiaCumpleanios");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Diranexo {
            get {
                return this.DiranexoField;
            }
            set {
                if ((object.ReferenceEquals(this.DiranexoField, value) != true)) {
                    this.DiranexoField = value;
                    this.RaisePropertyChanged("Diranexo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Dirapellido {
            get {
                return this.DirapellidoField;
            }
            set {
                if ((object.ReferenceEquals(this.DirapellidoField, value) != true)) {
                    this.DirapellidoField = value;
                    this.RaisePropertyChanged("Dirapellido");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Dirapoyo {
            get {
                return this.DirapoyoField;
            }
            set {
                if ((object.ReferenceEquals(this.DirapoyoField, value) != true)) {
                    this.DirapoyoField = value;
                    this.RaisePropertyChanged("Dirapoyo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Dircargo {
            get {
                return this.DircargoField;
            }
            set {
                if ((object.ReferenceEquals(this.DircargoField, value) != true)) {
                    this.DircargoField = value;
                    this.RaisePropertyChanged("Dircargo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Dircodi {
            get {
                return this.DircodiField;
            }
            set {
                if ((this.DircodiField.Equals(value) != true)) {
                    this.DircodiField = value;
                    this.RaisePropertyChanged("Dircodi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Dircorreo {
            get {
                return this.DircorreoField;
            }
            set {
                if ((object.ReferenceEquals(this.DircorreoField, value) != true)) {
                    this.DircorreoField = value;
                    this.RaisePropertyChanged("Dircorreo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> Dircumpleanios {
            get {
                return this.DircumpleaniosField;
            }
            set {
                if ((this.DircumpleaniosField.Equals(value) != true)) {
                    this.DircumpleaniosField = value;
                    this.RaisePropertyChanged("Dircumpleanios");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Direstado {
            get {
                return this.DirestadoField;
            }
            set {
                if ((object.ReferenceEquals(this.DirestadoField, value) != true)) {
                    this.DirestadoField = value;
                    this.RaisePropertyChanged("Direstado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> Dirfeccreacion {
            get {
                return this.DirfeccreacionField;
            }
            set {
                if ((this.DirfeccreacionField.Equals(value) != true)) {
                    this.DirfeccreacionField = value;
                    this.RaisePropertyChanged("Dirfeccreacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> Dirfecmodificacion {
            get {
                return this.DirfecmodificacionField;
            }
            set {
                if ((this.DirfecmodificacionField.Equals(value) != true)) {
                    this.DirfecmodificacionField = value;
                    this.RaisePropertyChanged("Dirfecmodificacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Dirfoto {
            get {
                return this.DirfotoField;
            }
            set {
                if ((object.ReferenceEquals(this.DirfotoField, value) != true)) {
                    this.DirfotoField = value;
                    this.RaisePropertyChanged("Dirfoto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Dirfuncion {
            get {
                return this.DirfuncionField;
            }
            set {
                if ((object.ReferenceEquals(this.DirfuncionField, value) != true)) {
                    this.DirfuncionField = value;
                    this.RaisePropertyChanged("Dirfuncion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Dirindsuperior {
            get {
                return this.DirindsuperiorField;
            }
            set {
                if ((object.ReferenceEquals(this.DirindsuperiorField, value) != true)) {
                    this.DirindsuperiorField = value;
                    this.RaisePropertyChanged("Dirindsuperior");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Dirnivel {
            get {
                return this.DirnivelField;
            }
            set {
                if ((this.DirnivelField.Equals(value) != true)) {
                    this.DirnivelField = value;
                    this.RaisePropertyChanged("Dirnivel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Dirnombre {
            get {
                return this.DirnombreField;
            }
            set {
                if ((object.ReferenceEquals(this.DirnombreField, value) != true)) {
                    this.DirnombreField = value;
                    this.RaisePropertyChanged("Dirnombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Dirorganigrama {
            get {
                return this.DirorganigramaField;
            }
            set {
                if ((object.ReferenceEquals(this.DirorganigramaField, value) != true)) {
                    this.DirorganigramaField = value;
                    this.RaisePropertyChanged("Dirorganigrama");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Dirpadre {
            get {
                return this.DirpadreField;
            }
            set {
                if ((this.DirpadreField.Equals(value) != true)) {
                    this.DirpadreField = value;
                    this.RaisePropertyChanged("Dirpadre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Dirsecretaria {
            get {
                return this.DirsecretariaField;
            }
            set {
                if ((object.ReferenceEquals(this.DirsecretariaField, value) != true)) {
                    this.DirsecretariaField = value;
                    this.RaisePropertyChanged("Dirsecretaria");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Dirsuperiores {
            get {
                return this.DirsuperioresField;
            }
            set {
                if ((object.ReferenceEquals(this.DirsuperioresField, value) != true)) {
                    this.DirsuperioresField = value;
                    this.RaisePropertyChanged("Dirsuperiores");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Dirtelefono {
            get {
                return this.DirtelefonoField;
            }
            set {
                if ((object.ReferenceEquals(this.DirtelefonoField, value) != true)) {
                    this.DirtelefonoField = value;
                    this.RaisePropertyChanged("Dirtelefono");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Dirusucreacion {
            get {
                return this.DirusucreacionField;
            }
            set {
                if ((object.ReferenceEquals(this.DirusucreacionField, value) != true)) {
                    this.DirusucreacionField = value;
                    this.RaisePropertyChanged("Dirusucreacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Dirusumodificacion {
            get {
                return this.DirusumodificacionField;
            }
            set {
                if ((object.ReferenceEquals(this.DirusumodificacionField, value) != true)) {
                    this.DirusumodificacionField = value;
                    this.RaisePropertyChanged("Dirusumodificacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Extension {
            get {
                return this.ExtensionField;
            }
            set {
                if ((object.ReferenceEquals(this.ExtensionField, value) != true)) {
                    this.ExtensionField = value;
                    this.RaisePropertyChanged("Extension");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FechaCumpleanios {
            get {
                return this.FechaCumpleaniosField;
            }
            set {
                if ((object.ReferenceEquals(this.FechaCumpleaniosField, value) != true)) {
                    this.FechaCumpleaniosField = value;
                    this.RaisePropertyChanged("FechaCumpleanios");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] Imagen {
            get {
                return this.ImagenField;
            }
            set {
                if ((object.ReferenceEquals(this.ImagenField, value) != true)) {
                    this.ImagenField = value;
                    this.RaisePropertyChanged("Imagen");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IndSeleccion {
            get {
                return this.IndSeleccionField;
            }
            set {
                if ((object.ReferenceEquals(this.IndSeleccionField, value) != true)) {
                    this.IndSeleccionField = value;
                    this.RaisePropertyChanged("IndSeleccion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MesCumpleanios {
            get {
                return this.MesCumpleaniosField;
            }
            set {
                if ((this.MesCumpleaniosField.Equals(value) != true)) {
                    this.MesCumpleaniosField = value;
                    this.RaisePropertyChanged("MesCumpleanios");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombrearchivo {
            get {
                return this.NombrearchivoField;
            }
            set {
                if ((object.ReferenceEquals(this.NombrearchivoField, value) != true)) {
                    this.NombrearchivoField = value;
                    this.RaisePropertyChanged("Nombrearchivo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Patharchivo {
            get {
                return this.PatharchivoField;
            }
            set {
                if ((object.ReferenceEquals(this.PatharchivoField, value) != true)) {
                    this.PatharchivoField = value;
                    this.RaisePropertyChanged("Patharchivo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Usercode {
            get {
                return this.UsercodeField;
            }
            set {
                if ((this.UsercodeField.Equals(value) != true)) {
                    this.UsercodeField = value;
                    this.RaisePropertyChanged("Usercode");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="DirectorioServicio.IServicio")]
    public interface IServicio {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/ValidarUsuarioCOES", ReplyAction="http://tempuri.org/IServicio/ValidarUsuarioCOESResponse")]
        int ValidarUsuarioCOES(string usuario, string clave);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/ValidarUsuarioCOES", ReplyAction="http://tempuri.org/IServicio/ValidarUsuarioCOESResponse")]
        System.Threading.Tasks.Task<int> ValidarUsuarioCOESAsync(string usuario, string clave);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/ObtenerAreasExtranet", ReplyAction="http://tempuri.org/IServicio/ObtenerAreasExtranetResponse")]
        COES.MVC.Extranet.DirectorioServicio.IntAreaDTO[] ObtenerAreasExtranet();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/ObtenerAreasExtranet", ReplyAction="http://tempuri.org/IServicio/ObtenerAreasExtranetResponse")]
        System.Threading.Tasks.Task<COES.MVC.Extranet.DirectorioServicio.IntAreaDTO[]> ObtenerAreasExtranetAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/ObtenerDirectorioExtranet", ReplyAction="http://tempuri.org/IServicio/ObtenerDirectorioExtranetResponse")]
        COES.MVC.Extranet.DirectorioServicio.IntDirectorioDTO[] ObtenerDirectorioExtranet(int idArea);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/ObtenerDirectorioExtranet", ReplyAction="http://tempuri.org/IServicio/ObtenerDirectorioExtranetResponse")]
        System.Threading.Tasks.Task<COES.MVC.Extranet.DirectorioServicio.IntDirectorioDTO[]> ObtenerDirectorioExtranetAsync(int idArea);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicioChannel : COES.MVC.Extranet.DirectorioServicio.IServicio, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioClient : System.ServiceModel.ClientBase<COES.MVC.Extranet.DirectorioServicio.IServicio>, COES.MVC.Extranet.DirectorioServicio.IServicio {
        
        public ServicioClient() {
        }
        
        public ServicioClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int ValidarUsuarioCOES(string usuario, string clave) {
            return base.Channel.ValidarUsuarioCOES(usuario, clave);
        }
        
        public System.Threading.Tasks.Task<int> ValidarUsuarioCOESAsync(string usuario, string clave) {
            return base.Channel.ValidarUsuarioCOESAsync(usuario, clave);
        }
        
        public COES.MVC.Extranet.DirectorioServicio.IntAreaDTO[] ObtenerAreasExtranet() {
            return base.Channel.ObtenerAreasExtranet();
        }
        
        public System.Threading.Tasks.Task<COES.MVC.Extranet.DirectorioServicio.IntAreaDTO[]> ObtenerAreasExtranetAsync() {
            return base.Channel.ObtenerAreasExtranetAsync();
        }
        
        public COES.MVC.Extranet.DirectorioServicio.IntDirectorioDTO[] ObtenerDirectorioExtranet(int idArea) {
            return base.Channel.ObtenerDirectorioExtranet(idArea);
        }
        
        public System.Threading.Tasks.Task<COES.MVC.Extranet.DirectorioServicio.IntDirectorioDTO[]> ObtenerDirectorioExtranetAsync(int idArea) {
            return base.Channel.ObtenerDirectorioExtranetAsync(idArea);
        }
    }
}
