using System;
using System.Collections.Generic;
using COES.Base.Core;


namespace COES.Dominio.DTO.Sic
{
    public class GmmValEnergiaEntregaDTO : EntityBase
    {
        public int VALENECODI { get; set; }
        public int PERICODI { get; set; }
        public int BARRCODI { get; set; }
        public string CASDDBBARRA { get; set; }
        public int PTOMEDICODI { get; set; }
        public int TPTOMEDICODI { get; set; }
        public int TIPOINFOCODI { get; set; }
        public DateTime? MEDIFECHA { get; set; }
        public int LECTCODI { get; set; }
        public int EMPRCODI { get; set; }
        public int EMPGCODI { get; set; }
        public int VALANIO { get; set; }
        public int VALMES { get; set; }

        public decimal VALENEVALENEVAL1 { get; set; }
        public decimal VALENEVALENEVAL2 { get; set; }
        public decimal VALENEVALENEVAL3 { get; set; }
        public decimal VALENEVALENEVAL4 { get; set; }
        public decimal VALENEVALENEVAL5 { get; set; }
        public decimal VALENEVALENEVAL6 { get; set; }
        public decimal VALENEVALENEVAL7 { get; set; }
        public decimal VALENEVALENEVAL8 { get; set; }
        public decimal VALENEVALENEVAL9 { get; set; }
        public decimal VALENEVALENEVAL10 { get; set; }
        public decimal VALENEVALENEVAL11 { get; set; }
        public decimal VALENEVALENEVAL12 { get; set; }
        public decimal VALENEVALENEVAL13 { get; set; }
        public decimal VALENEVALENEVAL14{ get; set; }
        public decimal VALENEVALENEVAL15 { get; set; }
        public decimal VALENEVALENEVAL16 { get; set; }
        public decimal VALENEVALENEVAL17 { get; set; }
        public decimal VALENEVALENEVAL18 { get; set; }
        public decimal VALENEVALENEVAL19 { get; set; }
        public decimal VALENEVALENEVAL20 { get; set; }
        public decimal VALENEVALENEVAL21 { get; set; }
        public decimal VALENEVALENEVAL22 { get; set; }
        public decimal VALENEVALENEVAL23 { get; set; }
        public decimal VALENEVALENEVAL24 { get; set; }
        public decimal VALENEVALENEVAL25 { get; set; }
        public decimal VALENEVALENEVAL26 { get; set; }
        public decimal VALENEVALENEVAL27 { get; set; }
        public decimal VALENEVALENEVAL28 { get; set; }
        public decimal VALENEVALENEVAL29 { get; set; }
        public decimal VALENEVALENEVAL30 { get; set; }
        public decimal VALENEVALENEVAL31 { get; set; }
        public decimal VALENEVALENEVAL32 { get; set; }
        public decimal VALENEVALENEVAL33 { get; set; }
        public decimal VALENEVALENEVAL34 { get; set; }
        public decimal VALENEVALENEVAL35 { get; set; }
        public decimal VALENEVALENEVAL36 { get; set; }
        public decimal VALENEVALENEVAL37 { get; set; }
        public decimal VALENEVALENEVAL38 { get; set; }
        public decimal VALENEVALENEVAL39 { get; set; }
        public decimal VALENEVALENEVAL40 { get; set; }
        public decimal VALENEVALENEVAL41 { get; set; }
        public decimal VALENEVALENEVAL42 { get; set; }
        public decimal VALENEVALENEVAL43 { get; set; }
        public decimal VALENEVALENEVAL44 { get; set; }
        public decimal VALENEVALENEVAL45 { get; set; }
        public decimal VALENEVALENEVAL46 { get; set; }
        public decimal VALENEVALENEVAL47 { get; set; }
        public decimal VALENEVALENEVAL48 { get; set; }
        public decimal VALENEVALENEVAL49 { get; set; }
        public decimal VALENEVALENEVAL50 { get; set; }
        public decimal VALENEVALENEVAL51 { get; set; }
        public decimal VALENEVALENEVAL52 { get; set; }
        public decimal VALENEVALENEVAL53 { get; set; }
        public decimal VALENEVALENEVAL54 { get; set; }
        public decimal VALENEVALENEVAL55 { get; set; }
        public decimal VALENEVALENEVAL56 { get; set; }
        public decimal VALENEVALENEVAL57 { get; set; }
        public decimal VALENEVALENEVAL58 { get; set; }
        public decimal VALENEVALENEVAL59 { get; set; }
        public decimal VALENEVALENEVAL60 { get; set; }
        public decimal VALENEVALENEVAL61 { get; set; }
        public decimal VALENEVALENEVAL62 { get; set; }
        public decimal VALENEVALENEVAL63 { get; set; }
        public decimal VALENEVALENEVAL64 { get; set; }
        public decimal VALENEVALENEVAL65 { get; set; }
        public decimal VALENEVALENEVAL66 { get; set; }
        public decimal VALENEVALENEVAL67 { get; set; }
        public decimal VALENEVALENEVAL68 { get; set; }
        public decimal VALENEVALENEVAL69 { get; set; }
        public decimal VALENEVALENEVAL70 { get; set; }
        public decimal VALENEVALENEVAL71 { get; set; }
        public decimal VALENEVALENEVAL72 { get; set; }
        public decimal VALENEVALENEVAL73 { get; set; }
        public decimal VALENEVALENEVAL74 { get; set; }
        public decimal VALENEVALENEVAL75 { get; set; }
        public decimal VALENEVALENEVAL76 { get; set; }
        public decimal VALENEVALENEVAL77 { get; set; }
        public decimal VALENEVALENEVAL78 { get; set; }
        public decimal VALENEVALENEVAL79 { get; set; }
        public decimal VALENEVALENEVAL80 { get; set; }
        public decimal VALENEVALENEVAL81 { get; set; }
        public decimal VALENEVALENEVAL82 { get; set; }
        public decimal VALENEVALENEVAL83 { get; set; }
        public decimal VALENEVALENEVAL84 { get; set; }
        public decimal VALENEVALENEVAL85 { get; set; }
        public decimal VALENEVALENEVAL86 { get; set; }
        public decimal VALENEVALENEVAL87 { get; set; }
        public decimal VALENEVALENEVAL88 { get; set; }
        public decimal VALENEVALENEVAL89 { get; set; }
        public decimal VALENEVALENEVAL90 { get; set; }
        public decimal VALENEVALENEVAL91 { get; set; }
        public decimal VALENEVALENEVAL92 { get; set; }
        public decimal VALENEVALENEVAL93 { get; set; }
        public decimal VALENEVALENEVAL94 { get; set; }
        public decimal VALENEVALENEVAL95 { get; set; }
        public decimal VALENEVALENEVAL96 { get; set; }

        public decimal VALENEVALENEVALCM1 { get; set; }
        public decimal VALENEVALENEVALCM2 { get; set; }
        public decimal VALENEVALENEVALCM3 { get; set; }
        public decimal VALENEVALENEVALCM4 { get; set; }
        public decimal VALENEVALENEVALCM5 { get; set; }
        public decimal VALENEVALENEVALCM6 { get; set; }
        public decimal VALENEVALENEVALCM7 { get; set; }
        public decimal VALENEVALENEVALCM8 { get; set; }
        public decimal VALENEVALENEVALCM9 { get; set; }
        public decimal VALENEVALENEVALCM10 { get; set; }
        public decimal VALENEVALENEVALCM11 { get; set; }
        public decimal VALENEVALENEVALCM12 { get; set; }
        public decimal VALENEVALENEVALCM13 { get; set; }
        public decimal VALENEVALENEVALCM14 { get; set; }
        public decimal VALENEVALENEVALCM15 { get; set; }
        public decimal VALENEVALENEVALCM16 { get; set; }
        public decimal VALENEVALENEVALCM17 { get; set; }
        public decimal VALENEVALENEVALCM18 { get; set; }
        public decimal VALENEVALENEVALCM19 { get; set; }
        public decimal VALENEVALENEVALCM20 { get; set; }
        public decimal VALENEVALENEVALCM21 { get; set; }
        public decimal VALENEVALENEVALCM22 { get; set; }
        public decimal VALENEVALENEVALCM23 { get; set; }
        public decimal VALENEVALENEVALCM24 { get; set; }
        public decimal VALENEVALENEVALCM25 { get; set; }
        public decimal VALENEVALENEVALCM26 { get; set; }
        public decimal VALENEVALENEVALCM27 { get; set; }
        public decimal VALENEVALENEVALCM28 { get; set; }
        public decimal VALENEVALENEVALCM29 { get; set; }
        public decimal VALENEVALENEVALCM30 { get; set; }
        public decimal VALENEVALENEVALCM31 { get; set; }
        public decimal VALENEVALENEVALCM32 { get; set; }
        public decimal VALENEVALENEVALCM33 { get; set; }
        public decimal VALENEVALENEVALCM34 { get; set; }
        public decimal VALENEVALENEVALCM35 { get; set; }
        public decimal VALENEVALENEVALCM36 { get; set; }
        public decimal VALENEVALENEVALCM37 { get; set; }
        public decimal VALENEVALENEVALCM38 { get; set; }
        public decimal VALENEVALENEVALCM39 { get; set; }
        public decimal VALENEVALENEVALCM40 { get; set; }
        public decimal VALENEVALENEVALCM41 { get; set; }
        public decimal VALENEVALENEVALCM42 { get; set; }
        public decimal VALENEVALENEVALCM43 { get; set; }
        public decimal VALENEVALENEVALCM44 { get; set; }
        public decimal VALENEVALENEVALCM45 { get; set; }
        public decimal VALENEVALENEVALCM46 { get; set; }
        public decimal VALENEVALENEVALCM47 { get; set; }
        public decimal VALENEVALENEVALCM48 { get; set; }
        public decimal VALENEVALENEVALCM49 { get; set; }
        public decimal VALENEVALENEVALCM50 { get; set; }
        public decimal VALENEVALENEVALCM51 { get; set; }
        public decimal VALENEVALENEVALCM52 { get; set; }
        public decimal VALENEVALENEVALCM53 { get; set; }
        public decimal VALENEVALENEVALCM54 { get; set; }
        public decimal VALENEVALENEVALCM55 { get; set; }
        public decimal VALENEVALENEVALCM56 { get; set; }
        public decimal VALENEVALENEVALCM57 { get; set; }
        public decimal VALENEVALENEVALCM58 { get; set; }
        public decimal VALENEVALENEVALCM59 { get; set; }
        public decimal VALENEVALENEVALCM60 { get; set; }
        public decimal VALENEVALENEVALCM61 { get; set; }
        public decimal VALENEVALENEVALCM62 { get; set; }
        public decimal VALENEVALENEVALCM63 { get; set; }
        public decimal VALENEVALENEVALCM64 { get; set; }
        public decimal VALENEVALENEVALCM65 { get; set; }
        public decimal VALENEVALENEVALCM66 { get; set; }
        public decimal VALENEVALENEVALCM67 { get; set; }
        public decimal VALENEVALENEVALCM68 { get; set; }
        public decimal VALENEVALENEVALCM69 { get; set; }
        public decimal VALENEVALENEVALCM70 { get; set; }
        public decimal VALENEVALENEVALCM71 { get; set; }
        public decimal VALENEVALENEVALCM72 { get; set; }
        public decimal VALENEVALENEVALCM73 { get; set; }
        public decimal VALENEVALENEVALCM74 { get; set; }
        public decimal VALENEVALENEVALCM75 { get; set; }
        public decimal VALENEVALENEVALCM76 { get; set; }
        public decimal VALENEVALENEVALCM77 { get; set; }
        public decimal VALENEVALENEVALCM78 { get; set; }
        public decimal VALENEVALENEVALCM79 { get; set; }
        public decimal VALENEVALENEVALCM80 { get; set; }
        public decimal VALENEVALENEVALCM81 { get; set; }
        public decimal VALENEVALENEVALCM82 { get; set; }
        public decimal VALENEVALENEVALCM83 { get; set; }
        public decimal VALENEVALENEVALCM84 { get; set; }
        public decimal VALENEVALENEVALCM85 { get; set; }
        public decimal VALENEVALENEVALCM86 { get; set; }
        public decimal VALENEVALENEVALCM87 { get; set; }
        public decimal VALENEVALENEVALCM88 { get; set; }
        public decimal VALENEVALENEVALCM89 { get; set; }
        public decimal VALENEVALENEVALCM90 { get; set; }
        public decimal VALENEVALENEVALCM91 { get; set; }
        public decimal VALENEVALENEVALCM92 { get; set; }
        public decimal VALENEVALENEVALCM93 { get; set; }
        public decimal VALENEVALENEVALCM94 { get; set; }
        public decimal VALENEVALENEVALCM95 { get; set; }
        public decimal VALENEVALENEVALCM96 { get; set; }

        public String VALUSUCREACION { get; set; }
        
        public int formatoEnergiaTrimestral { get; set; }
        public int formatoEnergiaMensual { get; set; }
        public bool EmpgPrimerMes { get; set; }
    
        public int MEDINTBLQNUMERO { get; set; }
        public DateTime MEDINTFECHAINI { get; set; }
        public Decimal MEDINTH1 { get; set; }


}
}
