using System;
using System.Collections.Generic;
using COES.Base.Core;


namespace COES.Dominio.DTO.Sic
{
    public class GmmValEnergiaDTO : EntityBase
    {
        public int VALOCODI { get; set; }
        public int PERICODI { get; set; }
        public int BARRCODI { get; set; }
        public string CASDDBBARRA { get; set; }
        public int PTOMEDICODI { get; set; }
        public int TPTOMEDICODI { get; set; }
        public int TIPOINFOCODI { get; set; }
        public DateTime? MEDIFECHA { get; set; }
        public int LECTCODI { get; set; }
        public int EMPRCODI { get; set; }
        public int EMPGCODI { get; set; }
        public int VALANIO { get; set; }
        public int VALMES { get; set; }

        public decimal VALOVALOR1 { get; set; }
        public decimal VALOVALOR2 { get; set; }
        public decimal VALOVALOR3 { get; set; }
        public decimal VALOVALOR4 { get; set; }
        public decimal VALOVALOR5 { get; set; }
        public decimal VALOVALOR6 { get; set; }
        public decimal VALOVALOR7 { get; set; }
        public decimal VALOVALOR8 { get; set; }
        public decimal VALOVALOR9 { get; set; }
        public decimal VALOVALOR10 { get; set; }
        public decimal VALOVALOR11 { get; set; }
        public decimal VALOVALOR12 { get; set; }
        public decimal VALOVALOR13 { get; set; }
        public decimal VALOVALOR14{ get; set; }
        public decimal VALOVALOR15 { get; set; }
        public decimal VALOVALOR16 { get; set; }
        public decimal VALOVALOR17 { get; set; }
        public decimal VALOVALOR18 { get; set; }
        public decimal VALOVALOR19 { get; set; }
        public decimal VALOVALOR20 { get; set; }
        public decimal VALOVALOR21 { get; set; }
        public decimal VALOVALOR22 { get; set; }
        public decimal VALOVALOR23 { get; set; }
        public decimal VALOVALOR24 { get; set; }
        public decimal VALOVALOR25 { get; set; }
        public decimal VALOVALOR26 { get; set; }
        public decimal VALOVALOR27 { get; set; }
        public decimal VALOVALOR28 { get; set; }
        public decimal VALOVALOR29 { get; set; }
        public decimal VALOVALOR30 { get; set; }
        public decimal VALOVALOR31 { get; set; }
        public decimal VALOVALOR32 { get; set; }
        public decimal VALOVALOR33 { get; set; }
        public decimal VALOVALOR34 { get; set; }
        public decimal VALOVALOR35 { get; set; }
        public decimal VALOVALOR36 { get; set; }
        public decimal VALOVALOR37 { get; set; }
        public decimal VALOVALOR38 { get; set; }
        public decimal VALOVALOR39 { get; set; }
        public decimal VALOVALOR40 { get; set; }
        public decimal VALOVALOR41 { get; set; }
        public decimal VALOVALOR42 { get; set; }
        public decimal VALOVALOR43 { get; set; }
        public decimal VALOVALOR44 { get; set; }
        public decimal VALOVALOR45 { get; set; }
        public decimal VALOVALOR46 { get; set; }
        public decimal VALOVALOR47 { get; set; }
        public decimal VALOVALOR48 { get; set; }
        public decimal VALOVALOR49 { get; set; }
        public decimal VALOVALOR50 { get; set; }
        public decimal VALOVALOR51 { get; set; }
        public decimal VALOVALOR52 { get; set; }
        public decimal VALOVALOR53 { get; set; }
        public decimal VALOVALOR54 { get; set; }
        public decimal VALOVALOR55 { get; set; }
        public decimal VALOVALOR56 { get; set; }
        public decimal VALOVALOR57 { get; set; }
        public decimal VALOVALOR58 { get; set; }
        public decimal VALOVALOR59 { get; set; }
        public decimal VALOVALOR60 { get; set; }
        public decimal VALOVALOR61 { get; set; }
        public decimal VALOVALOR62 { get; set; }
        public decimal VALOVALOR63 { get; set; }
        public decimal VALOVALOR64 { get; set; }
        public decimal VALOVALOR65 { get; set; }
        public decimal VALOVALOR66 { get; set; }
        public decimal VALOVALOR67 { get; set; }
        public decimal VALOVALOR68 { get; set; }
        public decimal VALOVALOR69 { get; set; }
        public decimal VALOVALOR70 { get; set; }
        public decimal VALOVALOR71 { get; set; }
        public decimal VALOVALOR72 { get; set; }
        public decimal VALOVALOR73 { get; set; }
        public decimal VALOVALOR74 { get; set; }
        public decimal VALOVALOR75 { get; set; }
        public decimal VALOVALOR76 { get; set; }
        public decimal VALOVALOR77 { get; set; }
        public decimal VALOVALOR78 { get; set; }
        public decimal VALOVALOR79 { get; set; }
        public decimal VALOVALOR80 { get; set; }
        public decimal VALOVALOR81 { get; set; }
        public decimal VALOVALOR82 { get; set; }
        public decimal VALOVALOR83 { get; set; }
        public decimal VALOVALOR84 { get; set; }
        public decimal VALOVALOR85 { get; set; }
        public decimal VALOVALOR86 { get; set; }
        public decimal VALOVALOR87 { get; set; }
        public decimal VALOVALOR88 { get; set; }
        public decimal VALOVALOR89 { get; set; }
        public decimal VALOVALOR90 { get; set; }
        public decimal VALOVALOR91 { get; set; }
        public decimal VALOVALOR92 { get; set; }
        public decimal VALOVALOR93 { get; set; }
        public decimal VALOVALOR94 { get; set; }
        public decimal VALOVALOR95 { get; set; }
        public decimal VALOVALOR96 { get; set; }

        public decimal VALOVALORCM1 { get; set; }
        public decimal VALOVALORCM2 { get; set; }
        public decimal VALOVALORCM3 { get; set; }
        public decimal VALOVALORCM4 { get; set; }
        public decimal VALOVALORCM5 { get; set; }
        public decimal VALOVALORCM6 { get; set; }
        public decimal VALOVALORCM7 { get; set; }
        public decimal VALOVALORCM8 { get; set; }
        public decimal VALOVALORCM9 { get; set; }
        public decimal VALOVALORCM10 { get; set; }
        public decimal VALOVALORCM11 { get; set; }
        public decimal VALOVALORCM12 { get; set; }
        public decimal VALOVALORCM13 { get; set; }
        public decimal VALOVALORCM14 { get; set; }
        public decimal VALOVALORCM15 { get; set; }
        public decimal VALOVALORCM16 { get; set; }
        public decimal VALOVALORCM17 { get; set; }
        public decimal VALOVALORCM18 { get; set; }
        public decimal VALOVALORCM19 { get; set; }
        public decimal VALOVALORCM20 { get; set; }
        public decimal VALOVALORCM21 { get; set; }
        public decimal VALOVALORCM22 { get; set; }
        public decimal VALOVALORCM23 { get; set; }
        public decimal VALOVALORCM24 { get; set; }
        public decimal VALOVALORCM25 { get; set; }
        public decimal VALOVALORCM26 { get; set; }
        public decimal VALOVALORCM27 { get; set; }
        public decimal VALOVALORCM28 { get; set; }
        public decimal VALOVALORCM29 { get; set; }
        public decimal VALOVALORCM30 { get; set; }
        public decimal VALOVALORCM31 { get; set; }
        public decimal VALOVALORCM32 { get; set; }
        public decimal VALOVALORCM33 { get; set; }
        public decimal VALOVALORCM34 { get; set; }
        public decimal VALOVALORCM35 { get; set; }
        public decimal VALOVALORCM36 { get; set; }
        public decimal VALOVALORCM37 { get; set; }
        public decimal VALOVALORCM38 { get; set; }
        public decimal VALOVALORCM39 { get; set; }
        public decimal VALOVALORCM40 { get; set; }
        public decimal VALOVALORCM41 { get; set; }
        public decimal VALOVALORCM42 { get; set; }
        public decimal VALOVALORCM43 { get; set; }
        public decimal VALOVALORCM44 { get; set; }
        public decimal VALOVALORCM45 { get; set; }
        public decimal VALOVALORCM46 { get; set; }
        public decimal VALOVALORCM47 { get; set; }
        public decimal VALOVALORCM48 { get; set; }
        public decimal VALOVALORCM49 { get; set; }
        public decimal VALOVALORCM50 { get; set; }
        public decimal VALOVALORCM51 { get; set; }
        public decimal VALOVALORCM52 { get; set; }
        public decimal VALOVALORCM53 { get; set; }
        public decimal VALOVALORCM54 { get; set; }
        public decimal VALOVALORCM55 { get; set; }
        public decimal VALOVALORCM56 { get; set; }
        public decimal VALOVALORCM57 { get; set; }
        public decimal VALOVALORCM58 { get; set; }
        public decimal VALOVALORCM59 { get; set; }
        public decimal VALOVALORCM60 { get; set; }
        public decimal VALOVALORCM61 { get; set; }
        public decimal VALOVALORCM62 { get; set; }
        public decimal VALOVALORCM63 { get; set; }
        public decimal VALOVALORCM64 { get; set; }
        public decimal VALOVALORCM65 { get; set; }
        public decimal VALOVALORCM66 { get; set; }
        public decimal VALOVALORCM67 { get; set; }
        public decimal VALOVALORCM68 { get; set; }
        public decimal VALOVALORCM69 { get; set; }
        public decimal VALOVALORCM70 { get; set; }
        public decimal VALOVALORCM71 { get; set; }
        public decimal VALOVALORCM72 { get; set; }
        public decimal VALOVALORCM73 { get; set; }
        public decimal VALOVALORCM74 { get; set; }
        public decimal VALOVALORCM75 { get; set; }
        public decimal VALOVALORCM76 { get; set; }
        public decimal VALOVALORCM77 { get; set; }
        public decimal VALOVALORCM78 { get; set; }
        public decimal VALOVALORCM79 { get; set; }
        public decimal VALOVALORCM80 { get; set; }
        public decimal VALOVALORCM81 { get; set; }
        public decimal VALOVALORCM82 { get; set; }
        public decimal VALOVALORCM83 { get; set; }
        public decimal VALOVALORCM84 { get; set; }
        public decimal VALOVALORCM85 { get; set; }
        public decimal VALOVALORCM86 { get; set; }
        public decimal VALOVALORCM87 { get; set; }
        public decimal VALOVALORCM88 { get; set; }
        public decimal VALOVALORCM89 { get; set; }
        public decimal VALOVALORCM90 { get; set; }
        public decimal VALOVALORCM91 { get; set; }
        public decimal VALOVALORCM92 { get; set; }
        public decimal VALOVALORCM93 { get; set; }
        public decimal VALOVALORCM94 { get; set; }
        public decimal VALOVALORCM95 { get; set; }
        public decimal VALOVALORCM96 { get; set; }

        public String VALUSUCREACION { get; set; }
        
        public int formatoEnergiaTrimestral { get; set; }
        public int formatoEnergiaMensual { get; set; }
        public bool EmpgPrimerMes { get; set; }
    
        public int MEDINTBLQNUMERO { get; set; }
        public DateTime MEDINTFECHAINI { get; set; }
        public Decimal MEDINTH1 { get; set; }


}
}
