//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COES.Service.YupanaContinuo.ServiceReferenceYupanaContinuo {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="www.coes.org.pe", ConfigurationName="ServiceReferenceYupanaContinuo.IYupanaContinuoServicio")]
    public interface IYupanaContinuoServicio {
        
        [System.ServiceModel.OperationContractAttribute(Action="www.coes.org.pe/IYupanaContinuoServicio/EjecutarYupanaContinuoAutomatico", ReplyAction="www.coes.org.pe/IYupanaContinuoServicio/EjecutarYupanaContinuoAutomaticoResponse")]
        void EjecutarYupanaContinuoAutomatico(string fecha, int hora);
        
        [System.ServiceModel.OperationContractAttribute(Action="www.coes.org.pe/IYupanaContinuoServicio/EjecutarYupanaContinuoAutomatico", ReplyAction="www.coes.org.pe/IYupanaContinuoServicio/EjecutarYupanaContinuoAutomaticoResponse")]
        System.Threading.Tasks.Task EjecutarYupanaContinuoAutomaticoAsync(string fecha, int hora);
        
        [System.ServiceModel.OperationContractAttribute(Action="www.coes.org.pe/IYupanaContinuoServicio/EjecutarYupanaContinuoManual", ReplyAction="www.coes.org.pe/IYupanaContinuoServicio/EjecutarYupanaContinuoManualResponse")]
        void EjecutarYupanaContinuoManual(string fecha, int hora, string usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="www.coes.org.pe/IYupanaContinuoServicio/EjecutarYupanaContinuoManual", ReplyAction="www.coes.org.pe/IYupanaContinuoServicio/EjecutarYupanaContinuoManualResponse")]
        System.Threading.Tasks.Task EjecutarYupanaContinuoManualAsync(string fecha, int hora, string usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="www.coes.org.pe/IYupanaContinuoServicio/VerificarEstadoYupanaContinuo", ReplyAction="www.coes.org.pe/IYupanaContinuoServicio/VerificarEstadoYupanaContinuoResponse")]
        void VerificarEstadoYupanaContinuo();
        
        [System.ServiceModel.OperationContractAttribute(Action="www.coes.org.pe/IYupanaContinuoServicio/VerificarEstadoYupanaContinuo", ReplyAction="www.coes.org.pe/IYupanaContinuoServicio/VerificarEstadoYupanaContinuoResponse")]
        System.Threading.Tasks.Task VerificarEstadoYupanaContinuoAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="www.coes.org.pe/IYupanaContinuoServicio/TerminarEjecucionGams", ReplyAction="www.coes.org.pe/IYupanaContinuoServicio/TerminarEjecucionGamsResponse")]
        void TerminarEjecucionGams();
        
        [System.ServiceModel.OperationContractAttribute(Action="www.coes.org.pe/IYupanaContinuoServicio/TerminarEjecucionGams", ReplyAction="www.coes.org.pe/IYupanaContinuoServicio/TerminarEjecucionGamsResponse")]
        System.Threading.Tasks.Task TerminarEjecucionGamsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="www.coes.org.pe/IYupanaContinuoServicio/SimularArbolYupanaContinuo", ReplyAction="www.coes.org.pe/IYupanaContinuoServicio/SimularArbolYupanaContinuoResponse")]
        void SimularArbolYupanaContinuo();
        
        [System.ServiceModel.OperationContractAttribute(Action="www.coes.org.pe/IYupanaContinuoServicio/SimularArbolYupanaContinuo", ReplyAction="www.coes.org.pe/IYupanaContinuoServicio/SimularArbolYupanaContinuoResponse")]
        System.Threading.Tasks.Task SimularArbolYupanaContinuoAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IYupanaContinuoServicioChannel : COES.Service.YupanaContinuo.ServiceReferenceYupanaContinuo.IYupanaContinuoServicio, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class YupanaContinuoServicioClient : System.ServiceModel.ClientBase<COES.Service.YupanaContinuo.ServiceReferenceYupanaContinuo.IYupanaContinuoServicio>, COES.Service.YupanaContinuo.ServiceReferenceYupanaContinuo.IYupanaContinuoServicio {
        
        public YupanaContinuoServicioClient() {
        }
        
        public YupanaContinuoServicioClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public YupanaContinuoServicioClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public YupanaContinuoServicioClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public YupanaContinuoServicioClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void EjecutarYupanaContinuoAutomatico(string fecha, int hora) {
            base.Channel.EjecutarYupanaContinuoAutomatico(fecha, hora);
        }
        
        public System.Threading.Tasks.Task EjecutarYupanaContinuoAutomaticoAsync(string fecha, int hora) {
            return base.Channel.EjecutarYupanaContinuoAutomaticoAsync(fecha, hora);
        }
        
        public void EjecutarYupanaContinuoManual(string fecha, int hora, string usuario) {
            base.Channel.EjecutarYupanaContinuoManual(fecha, hora, usuario);
        }
        
        public System.Threading.Tasks.Task EjecutarYupanaContinuoManualAsync(string fecha, int hora, string usuario) {
            return base.Channel.EjecutarYupanaContinuoManualAsync(fecha, hora, usuario);
        }
        
        public void VerificarEstadoYupanaContinuo() {
            base.Channel.VerificarEstadoYupanaContinuo();
        }
        
        public System.Threading.Tasks.Task VerificarEstadoYupanaContinuoAsync() {
            return base.Channel.VerificarEstadoYupanaContinuoAsync();
        }
        
        public void TerminarEjecucionGams() {
            base.Channel.TerminarEjecucionGams();
        }
        
        public System.Threading.Tasks.Task TerminarEjecucionGamsAsync() {
            return base.Channel.TerminarEjecucionGamsAsync();
        }
        
        public void SimularArbolYupanaContinuo() {
            base.Channel.SimularArbolYupanaContinuo();
        }
        
        public System.Threading.Tasks.Task SimularArbolYupanaContinuoAsync() {
            return base.Channel.SimularArbolYupanaContinuoAsync();
        }
    }
}
