//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COES.MVC.Extranet.wsDemanda {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="wsDemanda.IDemanda")]
    public interface IDemanda {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDemanda/EmpresasRepxUsuario", ReplyAction="http://tempuri.org/IDemanda/EmpresasRepxUsuarioResponse")]
        System.Data.DataTable EmpresasRepxUsuario(string[] as_arr_emp, string as_credencial);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDemanda/EmpresasRepxUsuario", ReplyAction="http://tempuri.org/IDemanda/EmpresasRepxUsuarioResponse")]
        System.Threading.Tasks.Task<System.Data.DataTable> EmpresasRepxUsuarioAsync(string[] as_arr_emp, string as_credencial);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDemanda/PuntoMedicionBarraxEmp", ReplyAction="http://tempuri.org/IDemanda/PuntoMedicionBarraxEmpResponse")]
        System.Data.DataTable PuntoMedicionBarraxEmp(int ai_emprcodi, string as_credencial);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDemanda/PuntoMedicionBarraxEmp", ReplyAction="http://tempuri.org/IDemanda/PuntoMedicionBarraxEmpResponse")]
        System.Threading.Tasks.Task<System.Data.DataTable> PuntoMedicionBarraxEmpAsync(int ai_emprcodi, string as_credencial);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDemanda/PuntoMedicionBarraDescxEmp", ReplyAction="http://tempuri.org/IDemanda/PuntoMedicionBarraDescxEmpResponse")]
        System.Data.DataTable PuntoMedicionBarraDescxEmp(int ai_emprcodi, string as_credencial);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDemanda/PuntoMedicionBarraDescxEmp", ReplyAction="http://tempuri.org/IDemanda/PuntoMedicionBarraDescxEmpResponse")]
        System.Threading.Tasks.Task<System.Data.DataTable> PuntoMedicionBarraDescxEmpAsync(int ai_emprcodi, string as_credencial);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDemanda/PuntoMedicionBarraDesc", ReplyAction="http://tempuri.org/IDemanda/PuntoMedicionBarraDescResponse")]
        System.Data.DataTable PuntoMedicionBarraDesc(int ai_ptomedicodi, string as_credencial);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDemanda/PuntoMedicionBarraDesc", ReplyAction="http://tempuri.org/IDemanda/PuntoMedicionBarraDescResponse")]
        System.Threading.Tasks.Task<System.Data.DataTable> PuntoMedicionBarraDescAsync(int ai_ptomedicodi, string as_credencial);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDemanda/ObtenerDemandaFuente", ReplyAction="http://tempuri.org/IDemanda/ObtenerDemandaFuenteResponse")]
        System.Data.DataTable ObtenerDemandaFuente(int ai_etacodi, System.DateTime adt_fecha_rep, int ai_ptomedicodi, string as_credencial);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDemanda/ObtenerDemandaFuente", ReplyAction="http://tempuri.org/IDemanda/ObtenerDemandaFuenteResponse")]
        System.Threading.Tasks.Task<System.Data.DataTable> ObtenerDemandaFuenteAsync(int ai_etacodi, System.DateTime adt_fecha_rep, int ai_ptomedicodi, string as_credencial);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDemanda/ListarEnviosxEmpresas", ReplyAction="http://tempuri.org/IDemanda/ListarEnviosxEmpresasResponse")]
        System.Data.DataTable ListarEnviosxEmpresas(System.DateTime adt_f_ini, System.DateTime adt_f_fin, int ai_emprcodi, int ai_tipempr, string as_credencial);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDemanda/ListarEnviosxEmpresas", ReplyAction="http://tempuri.org/IDemanda/ListarEnviosxEmpresasResponse")]
        System.Threading.Tasks.Task<System.Data.DataTable> ListarEnviosxEmpresasAsync(System.DateTime adt_f_ini, System.DateTime adt_f_fin, int ai_emprcodi, int ai_tipempr, string as_credencial);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDemanda/ListarEnviosxEmpresaHistorico", ReplyAction="http://tempuri.org/IDemanda/ListarEnviosxEmpresaHistoricoResponse")]
        System.Data.DataTable ListarEnviosxEmpresaHistorico(System.DateTime adt_f_ini, System.DateTime adt_f_fin, int ai_tipo_empr, int ai_tipo, string as_credencial);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDemanda/ListarEnviosxEmpresaHistorico", ReplyAction="http://tempuri.org/IDemanda/ListarEnviosxEmpresaHistoricoResponse")]
        System.Threading.Tasks.Task<System.Data.DataTable> ListarEnviosxEmpresaHistoricoAsync(System.DateTime adt_f_ini, System.DateTime adt_f_fin, int ai_tipo_empr, int ai_tipo, string as_credencial);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDemanda/ObtenerDemandaBarraDiario96Fhora", ReplyAction="http://tempuri.org/IDemanda/ObtenerDemandaBarraDiario96FhoraResponse")]
        System.Data.DataTable ObtenerDemandaBarraDiario96Fhora(System.DateTime adt_fecha_rep, int ai_lectcodi_real, int ai_lectcodi_prog, int ai_tipoinf, int ai_ptomedicodi, string as_credencial);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDemanda/ObtenerDemandaBarraDiario96Fhora", ReplyAction="http://tempuri.org/IDemanda/ObtenerDemandaBarraDiario96FhoraResponse")]
        System.Threading.Tasks.Task<System.Data.DataTable> ObtenerDemandaBarraDiario96FhoraAsync(System.DateTime adt_fecha_rep, int ai_lectcodi_real, int ai_lectcodi_prog, int ai_tipoinf, int ai_ptomedicodi, string as_credencial);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDemanda/ObtenerDemandaBarraDiario96Fhora2", ReplyAction="http://tempuri.org/IDemanda/ObtenerDemandaBarraDiario96Fhora2Response")]
        System.Data.DataTable ObtenerDemandaBarraDiario96Fhora2(System.DateTime adt_fini, System.DateTime adt_ffin, int ai_lectcodi, int ai_tipoinf, int ai_ptomedicodi, int ai_etacodi, string as_credencial);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDemanda/ObtenerDemandaBarraDiario96Fhora2", ReplyAction="http://tempuri.org/IDemanda/ObtenerDemandaBarraDiario96Fhora2Response")]
        System.Threading.Tasks.Task<System.Data.DataTable> ObtenerDemandaBarraDiario96Fhora2Async(System.DateTime adt_fini, System.DateTime adt_ffin, int ai_lectcodi, int ai_tipoinf, int ai_ptomedicodi, int ai_etacodi, string as_credencial);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDemanda/ObtenerDemandaBarraSemanal96Fhora", ReplyAction="http://tempuri.org/IDemanda/ObtenerDemandaBarraSemanal96FhoraResponse")]
        System.Data.DataTable ObtenerDemandaBarraSemanal96Fhora(System.DateTime adt_fecha_rep, int ai_lectcodi, int ai_tipoinf, int ai_ptomedicodi, string as_credencial);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDemanda/ObtenerDemandaBarraSemanal96Fhora", ReplyAction="http://tempuri.org/IDemanda/ObtenerDemandaBarraSemanal96FhoraResponse")]
        System.Threading.Tasks.Task<System.Data.DataTable> ObtenerDemandaBarraSemanal96FhoraAsync(System.DateTime adt_fecha_rep, int ai_lectcodi, int ai_tipoinf, int ai_ptomedicodi, string as_credencial);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDemanda/DemandaBarraDiariaReportada96", ReplyAction="http://tempuri.org/IDemanda/DemandaBarraDiariaReportada96Response")]
        System.Data.DataTable DemandaBarraDiariaReportada96(System.DateTime adt_fecha_rep, int ai_lectcodi_real, int ai_lectcodi_prog, int ai_tipoinf, int ai_ptomedicodi, int ai_canalcodi, string as_credencial);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDemanda/DemandaBarraDiariaReportada96", ReplyAction="http://tempuri.org/IDemanda/DemandaBarraDiariaReportada96Response")]
        System.Threading.Tasks.Task<System.Data.DataTable> DemandaBarraDiariaReportada96Async(System.DateTime adt_fecha_rep, int ai_lectcodi_real, int ai_lectcodi_prog, int ai_tipoinf, int ai_ptomedicodi, int ai_canalcodi, string as_credencial);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDemanda/DemandaBarraSemanalReportada96", ReplyAction="http://tempuri.org/IDemanda/DemandaBarraSemanalReportada96Response")]
        System.Data.DataTable DemandaBarraSemanalReportada96(System.DateTime adt_fecha_rep, int ai_lectcodi, int ai_tipoinf, int ai_ptomedicodi, string as_credencial);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDemanda/DemandaBarraSemanalReportada96", ReplyAction="http://tempuri.org/IDemanda/DemandaBarraSemanalReportada96Response")]
        System.Threading.Tasks.Task<System.Data.DataTable> DemandaBarraSemanalReportada96Async(System.DateTime adt_fecha_rep, int ai_lectcodi, int ai_tipoinf, int ai_ptomedicodi, string as_credencial);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDemanda/DemandaBarraReporte48from48T", ReplyAction="http://tempuri.org/IDemanda/DemandaBarraReporte48from48TResponse")]
        System.Data.DataTable DemandaBarraReporte48from48T(System.DateTime adt_fi, System.DateTime adt_ff, int ai_lectcodi, int ai_tipoinf, int ai_ptomedicodi, int ai_emprecodi, string as_credencial);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDemanda/DemandaBarraReporte48from48T", ReplyAction="http://tempuri.org/IDemanda/DemandaBarraReporte48from48TResponse")]
        System.Threading.Tasks.Task<System.Data.DataTable> DemandaBarraReporte48from48TAsync(System.DateTime adt_fi, System.DateTime adt_ff, int ai_lectcodi, int ai_tipoinf, int ai_ptomedicodi, int ai_emprecodi, string as_credencial);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDemanda/DemandaBarraReporte48from48T2", ReplyAction="http://tempuri.org/IDemanda/DemandaBarraReporte48from48T2Response")]
        System.Data.DataTable DemandaBarraReporte48from48T2(System.DateTime adt_fi, System.DateTime adt_ff, int ai_lectcodi, int ai_tipoinf, string ai_emprecodi, string as_credencial);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDemanda/DemandaBarraReporte48from48T2", ReplyAction="http://tempuri.org/IDemanda/DemandaBarraReporte48from48T2Response")]
        System.Threading.Tasks.Task<System.Data.DataTable> DemandaBarraReporte48from48T2Async(System.DateTime adt_fi, System.DateTime adt_ff, int ai_lectcodi, int ai_tipoinf, string ai_emprecodi, string as_credencial);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDemanda/DemandaBarraReporte48from96T", ReplyAction="http://tempuri.org/IDemanda/DemandaBarraReporte48from96TResponse")]
        System.Data.DataTable DemandaBarraReporte48from96T(System.DateTime adt_fi, System.DateTime adt_ff, int ai_lectcodi, int ai_tipoinf, int ai_ptomedicodi, int ai_emprecodi, string as_credencial);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDemanda/DemandaBarraReporte48from96T", ReplyAction="http://tempuri.org/IDemanda/DemandaBarraReporte48from96TResponse")]
        System.Threading.Tasks.Task<System.Data.DataTable> DemandaBarraReporte48from96TAsync(System.DateTime adt_fi, System.DateTime adt_ff, int ai_lectcodi, int ai_tipoinf, int ai_ptomedicodi, int ai_emprecodi, string as_credencial);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDemanda/DemandaBarraReporte96from96T", ReplyAction="http://tempuri.org/IDemanda/DemandaBarraReporte96from96TResponse")]
        System.Data.DataTable DemandaBarraReporte96from96T(System.DateTime adt_fi, System.DateTime adt_ff, int ai_lectcodi, int ai_tipoinf, int ai_ptomedicodi, int ai_emprecodi, string as_credencial);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDemanda/DemandaBarraReporte96from96T", ReplyAction="http://tempuri.org/IDemanda/DemandaBarraReporte96from96TResponse")]
        System.Threading.Tasks.Task<System.Data.DataTable> DemandaBarraReporte96from96TAsync(System.DateTime adt_fi, System.DateTime adt_ff, int ai_lectcodi, int ai_tipoinf, int ai_ptomedicodi, int ai_emprecodi, string as_credencial);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDemanda/AgregarDemanda48", ReplyAction="http://tempuri.org/IDemanda/AgregarDemanda48Response")]
        int AgregarDemanda48(System.DateTime adt_fecha, int ai_lectcodi, int ai_tipoinf, int ai_ptomedicodi, double[] arr_valores48, string as_credencial);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDemanda/AgregarDemanda48", ReplyAction="http://tempuri.org/IDemanda/AgregarDemanda48Response")]
        System.Threading.Tasks.Task<int> AgregarDemanda48Async(System.DateTime adt_fecha, int ai_lectcodi, int ai_tipoinf, int ai_ptomedicodi, double[] arr_valores48, string as_credencial);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDemanda/AgregarDemanda96", ReplyAction="http://tempuri.org/IDemanda/AgregarDemanda96Response")]
        int AgregarDemanda96(System.DateTime adt_fecha, int ai_lectcodi, int ai_tipoinf, int ai_ptomedicodi, double[] arr_valores96, string as_credencial);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDemanda/AgregarDemanda96", ReplyAction="http://tempuri.org/IDemanda/AgregarDemanda96Response")]
        System.Threading.Tasks.Task<int> AgregarDemanda96Async(System.DateTime adt_fecha, int ai_lectcodi, int ai_tipoinf, int ai_ptomedicodi, double[] arr_valores96, string as_credencial);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDemanda/EliminarDemanda96DiaExe", ReplyAction="http://tempuri.org/IDemanda/EliminarDemanda96DiaExeResponse")]
        int EliminarDemanda96DiaExe(System.DateTime adt_f_ini, System.DateTime adt_f_fin, int ai_emprcodi, string as_credencial);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDemanda/EliminarDemanda96DiaExe", ReplyAction="http://tempuri.org/IDemanda/EliminarDemanda96DiaExeResponse")]
        System.Threading.Tasks.Task<int> EliminarDemanda96DiaExeAsync(System.DateTime adt_f_ini, System.DateTime adt_f_fin, int ai_emprcodi, string as_credencial);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDemanda/EliminarDemanda96DiaPro", ReplyAction="http://tempuri.org/IDemanda/EliminarDemanda96DiaProResponse")]
        int EliminarDemanda96DiaPro(System.DateTime adt_f_ini, System.DateTime adt_f_fin, int ai_emprcodi, string as_credencial);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDemanda/EliminarDemanda96DiaPro", ReplyAction="http://tempuri.org/IDemanda/EliminarDemanda96DiaProResponse")]
        System.Threading.Tasks.Task<int> EliminarDemanda96DiaProAsync(System.DateTime adt_f_ini, System.DateTime adt_f_fin, int ai_emprcodi, string as_credencial);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDemanda/EliminarDemanda96SemPro", ReplyAction="http://tempuri.org/IDemanda/EliminarDemanda96SemProResponse")]
        int EliminarDemanda96SemPro(System.DateTime adt_f_ini, System.DateTime adt_f_fin, int ai_emprcodi, string as_credencial);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDemanda/EliminarDemanda96SemPro", ReplyAction="http://tempuri.org/IDemanda/EliminarDemanda96SemProResponse")]
        System.Threading.Tasks.Task<int> EliminarDemanda96SemProAsync(System.DateTime adt_f_ini, System.DateTime adt_f_fin, int ai_emprcodi, string as_credencial);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDemanda/ReporteCumplimiento", ReplyAction="http://tempuri.org/IDemanda/ReporteCumplimientoResponse")]
        wcfSicOperacion.Cumplimiento[] ReporteCumplimiento(System.DateTime adt_ini, System.DateTime adt_fin, int ai_tipo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDemanda/ReporteCumplimiento", ReplyAction="http://tempuri.org/IDemanda/ReporteCumplimientoResponse")]
        System.Threading.Tasks.Task<wcfSicOperacion.Cumplimiento[]> ReporteCumplimientoAsync(System.DateTime adt_ini, System.DateTime adt_fin, int ai_tipo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDemanda/ReporteCumplimientoDet", ReplyAction="http://tempuri.org/IDemanda/ReporteCumplimientoDetResponse")]
        wcfSicOperacion.CumplimientoDetalle[] ReporteCumplimientoDet(System.DateTime adt_ini, System.DateTime adt_fin, int ai_emprcodi, int ai_tipo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDemanda/ReporteCumplimientoDet", ReplyAction="http://tempuri.org/IDemanda/ReporteCumplimientoDetResponse")]
        System.Threading.Tasks.Task<wcfSicOperacion.CumplimientoDetalle[]> ReporteCumplimientoDetAsync(System.DateTime adt_ini, System.DateTime adt_fin, int ai_emprcodi, int ai_tipo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDemanda/ReporteCumplimientoDiario", ReplyAction="http://tempuri.org/IDemanda/ReporteCumplimientoDiarioResponse")]
        wcfSicOperacion.CumplimientoDiario[] ReporteCumplimientoDiario(System.DateTime adt_ini, System.DateTime adt_fin, int ai_emprcodi);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDemanda/ReporteCumplimientoDiario", ReplyAction="http://tempuri.org/IDemanda/ReporteCumplimientoDiarioResponse")]
        System.Threading.Tasks.Task<wcfSicOperacion.CumplimientoDiario[]> ReporteCumplimientoDiarioAsync(System.DateTime adt_ini, System.DateTime adt_fin, int ai_emprcodi);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDemanda/ReporteCumplimientoDiario2", ReplyAction="http://tempuri.org/IDemanda/ReporteCumplimientoDiario2Response")]
        wcfSicOperacion.CumplimientoDiario[] ReporteCumplimientoDiario2(System.DateTime adt_ini, System.DateTime adt_fin, int ai_emprcodi);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDemanda/ReporteCumplimientoDiario2", ReplyAction="http://tempuri.org/IDemanda/ReporteCumplimientoDiario2Response")]
        System.Threading.Tasks.Task<wcfSicOperacion.CumplimientoDiario[]> ReporteCumplimientoDiario2Async(System.DateTime adt_ini, System.DateTime adt_fin, int ai_emprcodi);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDemanda/ReporteCumplimientoPorc", ReplyAction="http://tempuri.org/IDemanda/ReporteCumplimientoPorcResponse")]
        wcfSicOperacion.CumplimientoPorcEmp[] ReporteCumplimientoPorc(System.DateTime adt_ini, System.DateTime adt_fin, int ai_tipo_emp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDemanda/ReporteCumplimientoPorc", ReplyAction="http://tempuri.org/IDemanda/ReporteCumplimientoPorcResponse")]
        System.Threading.Tasks.Task<wcfSicOperacion.CumplimientoPorcEmp[]> ReporteCumplimientoPorcAsync(System.DateTime adt_ini, System.DateTime adt_fin, int ai_tipo_emp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDemanda/ReporteCumplimientoxEmpresa", ReplyAction="http://tempuri.org/IDemanda/ReporteCumplimientoxEmpresaResponse")]
        wcfSicOperacion.CumplimientoDiarioxEmp[] ReporteCumplimientoxEmpresa(System.DateTime adt_fini, System.DateTime adt_ffin, int ai_tipo, int ai_tipo_em, int ai_frec);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDemanda/ReporteCumplimientoxEmpresa", ReplyAction="http://tempuri.org/IDemanda/ReporteCumplimientoxEmpresaResponse")]
        System.Threading.Tasks.Task<wcfSicOperacion.CumplimientoDiarioxEmp[]> ReporteCumplimientoxEmpresaAsync(System.DateTime adt_fini, System.DateTime adt_ffin, int ai_tipo, int ai_tipo_em, int ai_frec);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDemanda/Version", ReplyAction="http://tempuri.org/IDemanda/VersionResponse")]
        string Version();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDemanda/Version", ReplyAction="http://tempuri.org/IDemanda/VersionResponse")]
        System.Threading.Tasks.Task<string> VersionAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDemandaChannel : COES.MVC.Extranet.wsDemanda.IDemanda, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DemandaClient : System.ServiceModel.ClientBase<COES.MVC.Extranet.wsDemanda.IDemanda>, COES.MVC.Extranet.wsDemanda.IDemanda {
        
        public DemandaClient() {
        }
        
        public DemandaClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DemandaClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DemandaClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DemandaClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataTable EmpresasRepxUsuario(string[] as_arr_emp, string as_credencial) {
            return base.Channel.EmpresasRepxUsuario(as_arr_emp, as_credencial);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> EmpresasRepxUsuarioAsync(string[] as_arr_emp, string as_credencial) {
            return base.Channel.EmpresasRepxUsuarioAsync(as_arr_emp, as_credencial);
        }
        
        public System.Data.DataTable PuntoMedicionBarraxEmp(int ai_emprcodi, string as_credencial) {
            return base.Channel.PuntoMedicionBarraxEmp(ai_emprcodi, as_credencial);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> PuntoMedicionBarraxEmpAsync(int ai_emprcodi, string as_credencial) {
            return base.Channel.PuntoMedicionBarraxEmpAsync(ai_emprcodi, as_credencial);
        }
        
        public System.Data.DataTable PuntoMedicionBarraDescxEmp(int ai_emprcodi, string as_credencial) {
            return base.Channel.PuntoMedicionBarraDescxEmp(ai_emprcodi, as_credencial);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> PuntoMedicionBarraDescxEmpAsync(int ai_emprcodi, string as_credencial) {
            return base.Channel.PuntoMedicionBarraDescxEmpAsync(ai_emprcodi, as_credencial);
        }
        
        public System.Data.DataTable PuntoMedicionBarraDesc(int ai_ptomedicodi, string as_credencial) {
            return base.Channel.PuntoMedicionBarraDesc(ai_ptomedicodi, as_credencial);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> PuntoMedicionBarraDescAsync(int ai_ptomedicodi, string as_credencial) {
            return base.Channel.PuntoMedicionBarraDescAsync(ai_ptomedicodi, as_credencial);
        }
        
        public System.Data.DataTable ObtenerDemandaFuente(int ai_etacodi, System.DateTime adt_fecha_rep, int ai_ptomedicodi, string as_credencial) {
            return base.Channel.ObtenerDemandaFuente(ai_etacodi, adt_fecha_rep, ai_ptomedicodi, as_credencial);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> ObtenerDemandaFuenteAsync(int ai_etacodi, System.DateTime adt_fecha_rep, int ai_ptomedicodi, string as_credencial) {
            return base.Channel.ObtenerDemandaFuenteAsync(ai_etacodi, adt_fecha_rep, ai_ptomedicodi, as_credencial);
        }
        
        public System.Data.DataTable ListarEnviosxEmpresas(System.DateTime adt_f_ini, System.DateTime adt_f_fin, int ai_emprcodi, int ai_tipempr, string as_credencial) {
            return base.Channel.ListarEnviosxEmpresas(adt_f_ini, adt_f_fin, ai_emprcodi, ai_tipempr, as_credencial);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> ListarEnviosxEmpresasAsync(System.DateTime adt_f_ini, System.DateTime adt_f_fin, int ai_emprcodi, int ai_tipempr, string as_credencial) {
            return base.Channel.ListarEnviosxEmpresasAsync(adt_f_ini, adt_f_fin, ai_emprcodi, ai_tipempr, as_credencial);
        }
        
        public System.Data.DataTable ListarEnviosxEmpresaHistorico(System.DateTime adt_f_ini, System.DateTime adt_f_fin, int ai_tipo_empr, int ai_tipo, string as_credencial) {
            return base.Channel.ListarEnviosxEmpresaHistorico(adt_f_ini, adt_f_fin, ai_tipo_empr, ai_tipo, as_credencial);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> ListarEnviosxEmpresaHistoricoAsync(System.DateTime adt_f_ini, System.DateTime adt_f_fin, int ai_tipo_empr, int ai_tipo, string as_credencial) {
            return base.Channel.ListarEnviosxEmpresaHistoricoAsync(adt_f_ini, adt_f_fin, ai_tipo_empr, ai_tipo, as_credencial);
        }
        
        public System.Data.DataTable ObtenerDemandaBarraDiario96Fhora(System.DateTime adt_fecha_rep, int ai_lectcodi_real, int ai_lectcodi_prog, int ai_tipoinf, int ai_ptomedicodi, string as_credencial) {
            return base.Channel.ObtenerDemandaBarraDiario96Fhora(adt_fecha_rep, ai_lectcodi_real, ai_lectcodi_prog, ai_tipoinf, ai_ptomedicodi, as_credencial);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> ObtenerDemandaBarraDiario96FhoraAsync(System.DateTime adt_fecha_rep, int ai_lectcodi_real, int ai_lectcodi_prog, int ai_tipoinf, int ai_ptomedicodi, string as_credencial) {
            return base.Channel.ObtenerDemandaBarraDiario96FhoraAsync(adt_fecha_rep, ai_lectcodi_real, ai_lectcodi_prog, ai_tipoinf, ai_ptomedicodi, as_credencial);
        }
        
        public System.Data.DataTable ObtenerDemandaBarraDiario96Fhora2(System.DateTime adt_fini, System.DateTime adt_ffin, int ai_lectcodi, int ai_tipoinf, int ai_ptomedicodi, int ai_etacodi, string as_credencial) {
            return base.Channel.ObtenerDemandaBarraDiario96Fhora2(adt_fini, adt_ffin, ai_lectcodi, ai_tipoinf, ai_ptomedicodi, ai_etacodi, as_credencial);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> ObtenerDemandaBarraDiario96Fhora2Async(System.DateTime adt_fini, System.DateTime adt_ffin, int ai_lectcodi, int ai_tipoinf, int ai_ptomedicodi, int ai_etacodi, string as_credencial) {
            return base.Channel.ObtenerDemandaBarraDiario96Fhora2Async(adt_fini, adt_ffin, ai_lectcodi, ai_tipoinf, ai_ptomedicodi, ai_etacodi, as_credencial);
        }
        
        public System.Data.DataTable ObtenerDemandaBarraSemanal96Fhora(System.DateTime adt_fecha_rep, int ai_lectcodi, int ai_tipoinf, int ai_ptomedicodi, string as_credencial) {
            return base.Channel.ObtenerDemandaBarraSemanal96Fhora(adt_fecha_rep, ai_lectcodi, ai_tipoinf, ai_ptomedicodi, as_credencial);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> ObtenerDemandaBarraSemanal96FhoraAsync(System.DateTime adt_fecha_rep, int ai_lectcodi, int ai_tipoinf, int ai_ptomedicodi, string as_credencial) {
            return base.Channel.ObtenerDemandaBarraSemanal96FhoraAsync(adt_fecha_rep, ai_lectcodi, ai_tipoinf, ai_ptomedicodi, as_credencial);
        }
        
        public System.Data.DataTable DemandaBarraDiariaReportada96(System.DateTime adt_fecha_rep, int ai_lectcodi_real, int ai_lectcodi_prog, int ai_tipoinf, int ai_ptomedicodi, int ai_canalcodi, string as_credencial) {
            return base.Channel.DemandaBarraDiariaReportada96(adt_fecha_rep, ai_lectcodi_real, ai_lectcodi_prog, ai_tipoinf, ai_ptomedicodi, ai_canalcodi, as_credencial);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> DemandaBarraDiariaReportada96Async(System.DateTime adt_fecha_rep, int ai_lectcodi_real, int ai_lectcodi_prog, int ai_tipoinf, int ai_ptomedicodi, int ai_canalcodi, string as_credencial) {
            return base.Channel.DemandaBarraDiariaReportada96Async(adt_fecha_rep, ai_lectcodi_real, ai_lectcodi_prog, ai_tipoinf, ai_ptomedicodi, ai_canalcodi, as_credencial);
        }
        
        public System.Data.DataTable DemandaBarraSemanalReportada96(System.DateTime adt_fecha_rep, int ai_lectcodi, int ai_tipoinf, int ai_ptomedicodi, string as_credencial) {
            return base.Channel.DemandaBarraSemanalReportada96(adt_fecha_rep, ai_lectcodi, ai_tipoinf, ai_ptomedicodi, as_credencial);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> DemandaBarraSemanalReportada96Async(System.DateTime adt_fecha_rep, int ai_lectcodi, int ai_tipoinf, int ai_ptomedicodi, string as_credencial) {
            return base.Channel.DemandaBarraSemanalReportada96Async(adt_fecha_rep, ai_lectcodi, ai_tipoinf, ai_ptomedicodi, as_credencial);
        }
        
        public System.Data.DataTable DemandaBarraReporte48from48T(System.DateTime adt_fi, System.DateTime adt_ff, int ai_lectcodi, int ai_tipoinf, int ai_ptomedicodi, int ai_emprecodi, string as_credencial) {
            return base.Channel.DemandaBarraReporte48from48T(adt_fi, adt_ff, ai_lectcodi, ai_tipoinf, ai_ptomedicodi, ai_emprecodi, as_credencial);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> DemandaBarraReporte48from48TAsync(System.DateTime adt_fi, System.DateTime adt_ff, int ai_lectcodi, int ai_tipoinf, int ai_ptomedicodi, int ai_emprecodi, string as_credencial) {
            return base.Channel.DemandaBarraReporte48from48TAsync(adt_fi, adt_ff, ai_lectcodi, ai_tipoinf, ai_ptomedicodi, ai_emprecodi, as_credencial);
        }
        
        public System.Data.DataTable DemandaBarraReporte48from48T2(System.DateTime adt_fi, System.DateTime adt_ff, int ai_lectcodi, int ai_tipoinf, string ai_emprecodi, string as_credencial) {
            return base.Channel.DemandaBarraReporte48from48T2(adt_fi, adt_ff, ai_lectcodi, ai_tipoinf, ai_emprecodi, as_credencial);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> DemandaBarraReporte48from48T2Async(System.DateTime adt_fi, System.DateTime adt_ff, int ai_lectcodi, int ai_tipoinf, string ai_emprecodi, string as_credencial) {
            return base.Channel.DemandaBarraReporte48from48T2Async(adt_fi, adt_ff, ai_lectcodi, ai_tipoinf, ai_emprecodi, as_credencial);
        }
        
        public System.Data.DataTable DemandaBarraReporte48from96T(System.DateTime adt_fi, System.DateTime adt_ff, int ai_lectcodi, int ai_tipoinf, int ai_ptomedicodi, int ai_emprecodi, string as_credencial) {
            return base.Channel.DemandaBarraReporte48from96T(adt_fi, adt_ff, ai_lectcodi, ai_tipoinf, ai_ptomedicodi, ai_emprecodi, as_credencial);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> DemandaBarraReporte48from96TAsync(System.DateTime adt_fi, System.DateTime adt_ff, int ai_lectcodi, int ai_tipoinf, int ai_ptomedicodi, int ai_emprecodi, string as_credencial) {
            return base.Channel.DemandaBarraReporte48from96TAsync(adt_fi, adt_ff, ai_lectcodi, ai_tipoinf, ai_ptomedicodi, ai_emprecodi, as_credencial);
        }
        
        public System.Data.DataTable DemandaBarraReporte96from96T(System.DateTime adt_fi, System.DateTime adt_ff, int ai_lectcodi, int ai_tipoinf, int ai_ptomedicodi, int ai_emprecodi, string as_credencial) {
            return base.Channel.DemandaBarraReporte96from96T(adt_fi, adt_ff, ai_lectcodi, ai_tipoinf, ai_ptomedicodi, ai_emprecodi, as_credencial);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> DemandaBarraReporte96from96TAsync(System.DateTime adt_fi, System.DateTime adt_ff, int ai_lectcodi, int ai_tipoinf, int ai_ptomedicodi, int ai_emprecodi, string as_credencial) {
            return base.Channel.DemandaBarraReporte96from96TAsync(adt_fi, adt_ff, ai_lectcodi, ai_tipoinf, ai_ptomedicodi, ai_emprecodi, as_credencial);
        }
        
        public int AgregarDemanda48(System.DateTime adt_fecha, int ai_lectcodi, int ai_tipoinf, int ai_ptomedicodi, double[] arr_valores48, string as_credencial) {
            return base.Channel.AgregarDemanda48(adt_fecha, ai_lectcodi, ai_tipoinf, ai_ptomedicodi, arr_valores48, as_credencial);
        }
        
        public System.Threading.Tasks.Task<int> AgregarDemanda48Async(System.DateTime adt_fecha, int ai_lectcodi, int ai_tipoinf, int ai_ptomedicodi, double[] arr_valores48, string as_credencial) {
            return base.Channel.AgregarDemanda48Async(adt_fecha, ai_lectcodi, ai_tipoinf, ai_ptomedicodi, arr_valores48, as_credencial);
        }
        
        public int AgregarDemanda96(System.DateTime adt_fecha, int ai_lectcodi, int ai_tipoinf, int ai_ptomedicodi, double[] arr_valores96, string as_credencial) {
            return base.Channel.AgregarDemanda96(adt_fecha, ai_lectcodi, ai_tipoinf, ai_ptomedicodi, arr_valores96, as_credencial);
        }
        
        public System.Threading.Tasks.Task<int> AgregarDemanda96Async(System.DateTime adt_fecha, int ai_lectcodi, int ai_tipoinf, int ai_ptomedicodi, double[] arr_valores96, string as_credencial) {
            return base.Channel.AgregarDemanda96Async(adt_fecha, ai_lectcodi, ai_tipoinf, ai_ptomedicodi, arr_valores96, as_credencial);
        }
        
        public int EliminarDemanda96DiaExe(System.DateTime adt_f_ini, System.DateTime adt_f_fin, int ai_emprcodi, string as_credencial) {
            return base.Channel.EliminarDemanda96DiaExe(adt_f_ini, adt_f_fin, ai_emprcodi, as_credencial);
        }
        
        public System.Threading.Tasks.Task<int> EliminarDemanda96DiaExeAsync(System.DateTime adt_f_ini, System.DateTime adt_f_fin, int ai_emprcodi, string as_credencial) {
            return base.Channel.EliminarDemanda96DiaExeAsync(adt_f_ini, adt_f_fin, ai_emprcodi, as_credencial);
        }
        
        public int EliminarDemanda96DiaPro(System.DateTime adt_f_ini, System.DateTime adt_f_fin, int ai_emprcodi, string as_credencial) {
            return base.Channel.EliminarDemanda96DiaPro(adt_f_ini, adt_f_fin, ai_emprcodi, as_credencial);
        }
        
        public System.Threading.Tasks.Task<int> EliminarDemanda96DiaProAsync(System.DateTime adt_f_ini, System.DateTime adt_f_fin, int ai_emprcodi, string as_credencial) {
            return base.Channel.EliminarDemanda96DiaProAsync(adt_f_ini, adt_f_fin, ai_emprcodi, as_credencial);
        }
        
        public int EliminarDemanda96SemPro(System.DateTime adt_f_ini, System.DateTime adt_f_fin, int ai_emprcodi, string as_credencial) {
            return base.Channel.EliminarDemanda96SemPro(adt_f_ini, adt_f_fin, ai_emprcodi, as_credencial);
        }
        
        public System.Threading.Tasks.Task<int> EliminarDemanda96SemProAsync(System.DateTime adt_f_ini, System.DateTime adt_f_fin, int ai_emprcodi, string as_credencial) {
            return base.Channel.EliminarDemanda96SemProAsync(adt_f_ini, adt_f_fin, ai_emprcodi, as_credencial);
        }
        
        public wcfSicOperacion.Cumplimiento[] ReporteCumplimiento(System.DateTime adt_ini, System.DateTime adt_fin, int ai_tipo) {
            return base.Channel.ReporteCumplimiento(adt_ini, adt_fin, ai_tipo);
        }
        
        public System.Threading.Tasks.Task<wcfSicOperacion.Cumplimiento[]> ReporteCumplimientoAsync(System.DateTime adt_ini, System.DateTime adt_fin, int ai_tipo) {
            return base.Channel.ReporteCumplimientoAsync(adt_ini, adt_fin, ai_tipo);
        }
        
        public wcfSicOperacion.CumplimientoDetalle[] ReporteCumplimientoDet(System.DateTime adt_ini, System.DateTime adt_fin, int ai_emprcodi, int ai_tipo) {
            return base.Channel.ReporteCumplimientoDet(adt_ini, adt_fin, ai_emprcodi, ai_tipo);
        }
        
        public System.Threading.Tasks.Task<wcfSicOperacion.CumplimientoDetalle[]> ReporteCumplimientoDetAsync(System.DateTime adt_ini, System.DateTime adt_fin, int ai_emprcodi, int ai_tipo) {
            return base.Channel.ReporteCumplimientoDetAsync(adt_ini, adt_fin, ai_emprcodi, ai_tipo);
        }
        
        public wcfSicOperacion.CumplimientoDiario[] ReporteCumplimientoDiario(System.DateTime adt_ini, System.DateTime adt_fin, int ai_emprcodi) {
            return base.Channel.ReporteCumplimientoDiario(adt_ini, adt_fin, ai_emprcodi);
        }
        
        public System.Threading.Tasks.Task<wcfSicOperacion.CumplimientoDiario[]> ReporteCumplimientoDiarioAsync(System.DateTime adt_ini, System.DateTime adt_fin, int ai_emprcodi) {
            return base.Channel.ReporteCumplimientoDiarioAsync(adt_ini, adt_fin, ai_emprcodi);
        }
        
        public wcfSicOperacion.CumplimientoDiario[] ReporteCumplimientoDiario2(System.DateTime adt_ini, System.DateTime adt_fin, int ai_emprcodi) {
            return base.Channel.ReporteCumplimientoDiario2(adt_ini, adt_fin, ai_emprcodi);
        }
        
        public System.Threading.Tasks.Task<wcfSicOperacion.CumplimientoDiario[]> ReporteCumplimientoDiario2Async(System.DateTime adt_ini, System.DateTime adt_fin, int ai_emprcodi) {
            return base.Channel.ReporteCumplimientoDiario2Async(adt_ini, adt_fin, ai_emprcodi);
        }
        
        public wcfSicOperacion.CumplimientoPorcEmp[] ReporteCumplimientoPorc(System.DateTime adt_ini, System.DateTime adt_fin, int ai_tipo_emp) {
            return base.Channel.ReporteCumplimientoPorc(adt_ini, adt_fin, ai_tipo_emp);
        }
        
        public System.Threading.Tasks.Task<wcfSicOperacion.CumplimientoPorcEmp[]> ReporteCumplimientoPorcAsync(System.DateTime adt_ini, System.DateTime adt_fin, int ai_tipo_emp) {
            return base.Channel.ReporteCumplimientoPorcAsync(adt_ini, adt_fin, ai_tipo_emp);
        }
        
        public wcfSicOperacion.CumplimientoDiarioxEmp[] ReporteCumplimientoxEmpresa(System.DateTime adt_fini, System.DateTime adt_ffin, int ai_tipo, int ai_tipo_em, int ai_frec) {
            return base.Channel.ReporteCumplimientoxEmpresa(adt_fini, adt_ffin, ai_tipo, ai_tipo_em, ai_frec);
        }
        
        public System.Threading.Tasks.Task<wcfSicOperacion.CumplimientoDiarioxEmp[]> ReporteCumplimientoxEmpresaAsync(System.DateTime adt_fini, System.DateTime adt_ffin, int ai_tipo, int ai_tipo_em, int ai_frec) {
            return base.Channel.ReporteCumplimientoxEmpresaAsync(adt_fini, adt_ffin, ai_tipo, ai_tipo_em, ai_frec);
        }
        
        public string Version() {
            return base.Channel.Version();
        }
        
        public System.Threading.Tasks.Task<string> VersionAsync() {
            return base.Channel.VersionAsync();
        }
    }
}
