//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COES.MVC.Intranet.ServiceReferencePotenciaFirme {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="www.coes.org.pe", ConfigurationName="ServiceReferencePotenciaFirme.IPotenciaFirmeServicio")]
    public interface IPotenciaFirmeServicio {
        
        [System.ServiceModel.OperationContractAttribute(Action="www.coes.org.pe/IPotenciaFirmeServicio/EjecutarPotenciaRemunerable", ReplyAction="www.coes.org.pe/IPotenciaFirmeServicio/EjecutarPotenciaRemunerableResponse")]
        int EjecutarPotenciaRemunerable(int pfpericodi, int pfrecacodi, int indrecacodiant, int recpotcodi, string usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="www.coes.org.pe/IPotenciaFirmeServicio/EjecutarPotenciaRemunerable", ReplyAction="www.coes.org.pe/IPotenciaFirmeServicio/EjecutarPotenciaRemunerableResponse")]
        System.Threading.Tasks.Task<int> EjecutarPotenciaRemunerableAsync(int pfpericodi, int pfrecacodi, int indrecacodiant, int recpotcodi, string usuario);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPotenciaFirmeServicioChannel : COES.MVC.Intranet.ServiceReferencePotenciaFirme.IPotenciaFirmeServicio, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PotenciaFirmeServicioClient : System.ServiceModel.ClientBase<COES.MVC.Intranet.ServiceReferencePotenciaFirme.IPotenciaFirmeServicio>, COES.MVC.Intranet.ServiceReferencePotenciaFirme.IPotenciaFirmeServicio {
        
        public PotenciaFirmeServicioClient() {
        }
        
        public PotenciaFirmeServicioClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PotenciaFirmeServicioClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PotenciaFirmeServicioClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PotenciaFirmeServicioClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int EjecutarPotenciaRemunerable(int pfpericodi, int pfrecacodi, int indrecacodiant, int recpotcodi, string usuario) {
            return base.Channel.EjecutarPotenciaRemunerable(pfpericodi, pfrecacodi, indrecacodiant, recpotcodi, usuario);
        }
        
        public System.Threading.Tasks.Task<int> EjecutarPotenciaRemunerableAsync(int pfpericodi, int pfrecacodi, int indrecacodiant, int recpotcodi, string usuario) {
            return base.Channel.EjecutarPotenciaRemunerableAsync(pfpericodi, pfrecacodi, indrecacodiant, recpotcodi, usuario);
        }
    }
}
